export { AboutSection, SupportSection } from './AboutSection';
export type { AboutSectionProps, SupportSectionProps } from './AboutSection';
export { AppearanceSection } from './AppearanceSection';
export { DownloadsSection } from './DownloadsSection';
export { GeneralSection } from './GeneralSection';
export { HowToUseSection } from './HowToUseSection';
export { LegalSection } from './LegalSection';
export { PrivacySection } from './PrivacySection';
export type { PrivacySectionProps } from './PrivacySection';
export { SettingsComingSoonBadge } from './SettingsComingSoonBadge';
export { SettingsFeedbackBanner } from './SettingsFeedbackBanner';
export { SettingsHeader } from './SettingsHeader';
export { SettingsRow } from './SettingsRow';
export type { SettingsRowProps } from './SettingsRow';
export { SettingsSection } from './SettingsSection';
export type { SettingsSectionProps } from './SettingsSection';
export { SettingsSkeleton } from './SettingsSkeleton';
export { SettingsStaggerItem } from './SettingsStaggerItem';
export { StorageSection } from './StorageSection';
export type { StorageSectionProps } from './StorageSection';
