import { detectionEn } from './catalogs/detection.en';
import { shellEn } from './catalogs/shell.en';
import { videoPlayerEn } from './catalogs/videoPlayer.en';

export const en = {
  common: {
    ok: 'OK',
    cancel: 'Cancel',
    close: 'Close',
    retry: 'Try again',
    save: 'Save',
    saved: 'Saved',
    delete: 'Delete',
    remove: 'Remove',
    rename: 'Rename',
    share: 'Share',
    open: 'Open',
    play: 'Play',
    pause: 'Pause',
    resume: 'Resume',
    back: 'Back',
    goBack: 'Go back',
    next: 'Next',
    continue: 'Continue',
    skip: 'Skip',
    done: 'Done',
    loading: 'Loading',
    search: 'Search',
    reset: 'Reset',
    dismiss: 'Dismiss',
    comingSoon: 'Coming Soon',
    on: 'On',
    off: 'Off',
    default: 'Default',
    selected: 'Selected',
    version: 'Version {version}',
    brand: 'VidoraX',
    or: 'OR',
    create: 'Create',
    yes: 'Yes',
    no: 'No',
    clearInput: 'Clear input',
    closeModal: 'Close modal',
    loadingPlaceholder: 'Loading',
    refreshProfile: 'Refresh profile',
    refreshA11y: 'Refresh',
    dismissDiscoveryA11y: 'Dismiss media discovery',
    dismissDiscoveryHint: 'Hides detected media until you open a new page',
    logoA11y: 'VidoraX logo',
    loadingScreenA11y: 'VidoraX loading screen',
  },
  nav: {
    home: 'Home',
    homeTab: 'Home tab',
    browser: 'Browser',
    browserTab: 'Browser tab',
    downloads: 'Downloads',
    downloadsTab: 'Downloads tab',
    library: 'Player',
    libraryTab: 'Player tab',
    settings: 'Settings',
    settingsTab: 'Settings tab',
    about: 'About',
    support: 'Support',
    reportProblem: 'Report a Problem',
    privacy: 'Privacy',
    terms: 'Terms',
    history: 'History',
    watchHistory: 'Watch History',
    bookmarks: 'Bookmarks',
    favorites: 'Favorites',
    downloadSettings: 'Download Settings',
    appLockSetup: 'Set App Lock',
    appLockDisable: 'Disable App Lock',
    appLockChangePin: 'Change PIN',
    appLockRotateRecovery: 'New Recovery Code',
    downloadDetails: 'Download Details',
    storage: 'Storage',
  },
  storage: {
    title: 'Storage',
    subtitle: 'Device capacity and VidoraX file locations on this device',
    loading: 'Calculating storage…',
    loadFailed: 'Unable to read storage details right now.',
    refresh: 'Refresh',
    refreshA11y: 'Refresh storage details',
    unavailable: 'Unavailable',
    zeroBytes: '0 B',
    estimatedNote: 'Some values are estimated from app-managed folders.',
    partialScan: 'Some folders could not be scanned completely.',
    deviceOverview: 'Device Storage',
    storageUsed: 'Storage used',
    deviceUsageA11y: 'Device storage {percent} percent used',
    deviceUnavailable: 'Device storage details are unavailable on this device.',
    total: 'Total',
    used: 'Used',
    free: 'Free',
    appUsage: 'VidoraX Storage',
    appUsageSection: 'VidoraX Usage',
    locationsSection: 'Download Locations',
    locationsSubtitle: 'Where VidoraX saves files on this device',
    actionsSection: 'Storage Actions',
    videos: 'Videos',
    images: 'Images / Thumbnails',
    cache: 'Cache',
    temp: 'Temporary files',
    other: 'Other app data',
    userVisible: 'User-visible on device',
    appPrivate: 'Private to VidoraX (app storage)',
    createdWhenNeeded: 'Created automatically when first needed',
    openDownloads: 'Open Downloads',
    openLibrary: 'Open Player',
    clearCache: 'Clear Cache',
    clearCacheTitle: 'Clear cache?',
    clearCacheMessage:
      'This removes temporary cached files only. Completed downloads and your media library are not deleted.',
    clearCacheConfirm: 'Clear cache',
    locations: {
      downloadedVideos: 'Downloaded Videos',
      downloadedVideosDescription:
        'Completed media files saved by VidoraX inside app document storage.',
      thumbnails: 'Thumbnails & Cached Images',
      thumbnailsDescription:
        'Website thumbnails and image previews cached locally. Stored in app cache, not as separate downloads.',
      temporaryFiles: 'Temporary HLS Files',
      temporaryFilesDescription:
        'HLS segment workspaces used while a stream download is in progress.',
      temporaryDownloadParts: 'Temporary Download Parts',
      temporaryDownloadPartsDescription:
        'Partial range files used while a progressive download is in progress.',
      appCache: 'App Cache',
      appCacheDescription:
        'Temporary cached data including image previews. Safe to clear without removing completed downloads.',
      appDocuments: 'App Documents',
      appDocumentsDescription:
        'Preferences, playback state, and other VidoraX data stored on this device.',
    },
  },
  dates: {
    justNow: 'Just now',
    minutesAgo: '{count}m ago',
    hoursAgo: '{count}h ago',
    yesterday: 'Yesterday',
    daysAgo: '{count}d ago',
    remainingSeconds: '{count}s remaining',
    remainingMinutes: '{count} min remaining',
    remainingHours: '{count}h remaining',
    remainingHoursMinutes: '{hours}h {minutes}m remaining',
  },
  plurals: {
    downloadsZero: 'No downloads',
    downloadsOne: '{count} download',
    downloadsOther: '{count} downloads',
    videosZero: 'No videos',
    videosOne: '{count} video',
    videosOther: '{count} videos',
    itemsZero: 'No items',
    itemsOne: '{count} item',
    itemsOther: '{count} items',
    simultaneousDownloadsOne: '{count} simultaneous download',
    simultaneousDownloadsOther: '{count} simultaneous downloads',
  },
  errors: {
    unexpectedTitle: 'Something went wrong',
    unexpected: 'Something went wrong. Please try again.',
    retry: 'Try again',
    networkTitle: 'Connection problem',
    network: 'We could not reach the website or media source. Check your internet connection and try again.',
    timeout: 'The connection timed out. Please try again.',
    serverTitle: 'Source unavailable',
    server: 'The website or media source is having trouble right now. Please try again in a moment.',
    unauthorizedTitle: 'Access denied',
    unauthorized: 'The media source refused this request.',
    forbiddenTitle: 'Action not allowed',
    forbidden: 'You do not have permission to do that.',
    notFoundTitle: 'Not found',
    notFound: 'This item could not be found.',
    validationTitle: 'Invalid request',
    validation: 'Please check your information and try again.',
    offline: 'You appear to be offline. Some actions may be unavailable.',
    storage: 'Unable to use device storage right now.',
    fileNotFound: 'This file is no longer available on this device.',
    unsupportedMedia: "This video's format or codec isn't supported on this device.",
    downloadFailed: 'This download could not be completed.',
    authRequired: 'The media source requires authentication in its own website or app.',
    renameFailed: 'Couldn’t rename this item. Try again.',
    deleteFailed: 'Couldn’t delete this item. Try again.',
    shareFailed: 'Couldn’t share this file. Try again.',
    openFailed: 'Couldn’t open this file.',
    unknown: 'Something unexpected happened. Please try again.',
    codes: {
      NETWORK_ERROR: 'Network connection was lost.',
      NETWORK_TIMEOUT: 'The connection timed out.',
      RATE_LIMITED: 'The media source is temporarily busy. Try again shortly.',
      HTTP_ERROR: 'The download source could not be reached.',
      FILE_SYSTEM_ERROR: 'Unable to save this file.',
      FILE_WRITE_FAILED: 'Unable to save this file.',
      FILE_APPEND_FAILED: 'Unable to continue saving this file.',
      FILE_FINALIZE_FAILED: 'Unable to finalize the downloaded file.',
      INSUFFICIENT_STORAGE: 'Not enough storage space to complete this download.',
      INVALID_DESTINATION: 'Unable to save this file to storage.',
      PERMISSION_DENIED: 'Storage permission is required to save this download.',
      PARTIAL_FILE_CORRUPT: 'The partial download file is damaged and can’t be continued.',
      FINAL_FILE_INVALID: 'The downloaded file failed integrity checks.',
      CANCELLED: 'Download cancelled.',
      INVALID_RESOURCE: 'This media can’t be downloaded.',
      TRANSFER_INTERRUPTED: 'The download was interrupted.',
      PAUSE_FAILED: 'Couldn’t pause this download right now. Try again in a moment.',
      RESUME_FAILED: 'Unable to resume this download.',
      RESUME_UNSUPPORTED:
        'This media source doesn’t allow resuming a partial download.',
      RESUME_STATE_MISSING: 'Unable to resume this download.',
      RESUME_STATE_CONFLICT: 'Unable to resume this download.',
      QUEUE_ADMISSION_FAILED: 'Unable to resume this download.',
      PARTIAL_FILE_MISSING: 'The partial download file is no longer available.',
      RANGE_REJECTED:
        'This media source refused to continue from where the download stopped.',
      INVALID_RANGE_RESPONSE:
        'The media source returned an invalid resume response.',
      SOURCE_CHANGED: 'The source file changed and can’t be safely resumed.',
      RETRY_EXHAUSTED: 'This download failed after several automatic retries.',
      MERGE_FAILED: 'Unable to assemble the downloaded file.',
      PART_SIZE_MISMATCH: 'A download part failed integrity checks.',
      FINAL_SIZE_MISMATCH: 'The downloaded file size does not match the source.',
      CANCEL_FAILED: 'Couldn’t cancel this download.',
      WORKER_NOT_FOUND: 'Couldn’t pause this download right now. Try again in a moment.',
      AUTH_ERROR: 'The media source requires authentication to continue downloading.',
      AUTH_REQUIRED: 'The media source requires authentication in its own website or app.',
      SESSION_CONTEXT_LOST:
        'This authenticated download needs the active website session. Open the website and retry.',
      SESSION_CHANGED: 'Your website account changed. Open the website and try again.',
      SESSION_EXPIRED: 'Your website session expired. Open the website and try again.',
      AUTH_CONTEXT_UNAVAILABLE:
        'This protected media cannot be downloaded with the available session.',
      HLS_UNSUPPORTED: 'This stream format can’t be downloaded on this device.',
      HLS_ENCRYPTED: 'This stream is encrypted and can’t be downloaded.',
      UNSUPPORTED_DRM: 'Protected media can’t be downloaded.',
      UNSUPPORTED_HLS_ENCRYPTION: 'This encrypted stream can’t be downloaded.',
      LIVE_HLS_UNSUPPORTED: 'Live streams can’t be downloaded.',
      UNSUPPORTED_HLS_BYTERANGE: 'This stream can’t be downloaded.',
      INVALID_HLS_PLAYLIST: 'This stream playlist can’t be read.',
      UNKNOWN_ERROR: 'Something went wrong. Please try again.',
      FILE_NOT_FOUND: 'This file is no longer available on this device.',
      UNSUPPORTED_MEDIA: "This video's format or codec isn't supported on this device.",
      DOWNLOAD_FAILED: 'This download could not be completed.',
      RENAME_FAILED: 'Couldn’t rename this item. Try again.',
      STORAGE_ERROR: 'Unable to use device storage right now.',
      NOT_FOUND: 'This item could not be found.',
      VALIDATION_ERROR: 'Please check your information and try again.',
      SERVER_ERROR: 'The website or media source is having trouble right now. Please try again in a moment.',
      UNAUTHORIZED: 'The media source refused this request.',
      FORBIDDEN: 'You do not have permission to do that.',
      TIMEOUT: 'The connection timed out. Please try again.',
    },
  },
  emptyStates: {
    retry: 'Try again',
    genericTitle: 'Nothing here yet',
    genericDescription: 'When there is something to show, it will appear here.',
  },
  dialogs: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
  },
  files: {
    actionsTitle: 'File actions',
    actionsSubtitle: 'Rename, delete, open, or share',
    rename: 'Rename',
    renameFile: 'Rename file',
    renameFolder: 'Rename folder',
    delete: 'Delete',
    deleteFile: 'Delete file',
    open: 'Open',
    share: 'Share',
    play: 'Play',
    emptyName: 'New name cannot be empty.',
    emptyFolderName: 'Folder name cannot be empty.',
    unavailable: "Downloaded file couldn't be found.",
    unreadable: "VidoraX couldn't open this downloaded file.",
    noCompatibleApp: 'No compatible video app is installed.',
    shareFailed: 'Unable to share this video.',
    openFailed: "VidoraX couldn't open this downloaded file.",
    uriFailed: 'Unable to prepare this file for sharing.',
    notCompleted: 'This download is not completed yet.',
  },
  splash: {
    brandName: 'VidoraX',
    taglineFast: 'Fast',
    taglineReliable: 'Reliable',
    taglineSecure: 'Secure',
    loadingA11y: 'Loading',
    loadingScreenA11y: 'VidoraX loading screen',
  },
  onboarding: {
    skip: 'Skip',
    skipA11y: 'Skip onboarding',
    continue: 'Continue',
    getStarted: 'Get Started',
    gatewayTitleLead: 'Download',
    gatewayTitleAccent: 'Supported Media',
    gatewaySubtitle:
      'Browse your favorite websites or paste a link.\nVidoraX intelligently detects compatible downloadable videos.',
    trustTitleLead: 'Fast.',
    trustTitleAccent: 'Reliable.',
    trustTitleTrail: 'Always in Control.',
    trustSubtitle:
      'Pause, resume, queue and manage your downloads effortlessly while VidoraX keeps everything running in the background.',
    trustA11y:
      'Fast. Reliable. Always in Control. VidoraX manages every download from start to finish while keeping you in control.',
    trustDetected: 'Video Detected',
    trustCardTitle: 'Movie Trailer',
    trustCompleted: 'Completed',
    trustLibrary: 'Offline Library',
    trustPause: 'Pause',
    trustResume: 'Resume',
    trustQueue: 'Queue',
    trustNotifications: 'Notifications',
    trustRetry: 'Retry',
    trustBackground: 'Background',
    libraryTitleLead: 'Everything',
    libraryTitleAccent: 'Organized.',
    libraryTitleTrail: 'Instantly Accessible.',
    librarySubtitle:
      'Search, play, organize and manage every download from one beautiful offline library.',
    libraryA11y:
      'Everything Organized. Instantly Accessible. Your offline media library stays organized, searchable, and ready to watch.',
    librarySearchPlaceholder: 'Search downloads...',
    libraryPlaying: 'Playing Offline',
    libraryFavorites: 'Favorites',
    libraryHistory: 'History',
    librarySearch: 'Smart Search',
    libraryPlayer: 'Offline Player',
    libraryOrganized: 'Organized Library',
    librarySettings: 'Settings',
    libraryMovie: 'Movie Trailer',
    libraryTravel: 'Travel Vlog',
    libraryCourse: 'React Course',
    libraryVacation: 'Vacation Reel',
    libraryMetaCompleted: 'Completed',
    libraryMetaSaved: 'Saved',
    libraryMetaOffline: 'Offline',
    gatewayA11y:
      'Download supported media. VidoraX connects your download workflow into one experience.',
    downloadWorkflowA11y:
      'Download workflow: paste link, video detected, downloading, saved offline',
    progressA11y: 'Download progress',
    libraryHeroA11y:
      'Offline media library organizing itself into a searchable personal hub',
  },
  auth: {
    signInTitle: 'Welcome Back',
    signInSubtitle:
      'Continue to your secure download workspace and access your personal offline media library.',
    signInA11y:
      'Welcome back. Sign in to continue to your secure VidoraX download workspace.',
    signIn: 'Sign In',
    signInInstead: 'Sign In Instead',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password',
    noAccount: "Don't have an account?",
    createAccount: 'Create Account',
    signUpTitle: 'Create Your Account',
    signUpSubtitle:
      'Join VidoraX and start building your personal offline media library with a secure and seamless experience.',
    signUpA11y: 'Create your VidoraX account and unlock your secure download workspace.',
    nameLabel: 'Full Name',
    namePlaceholder: 'Enter your full name',
    createPasswordPlaceholder: 'Create a password',
    confirmLabel: 'Confirm Password',
    confirmPlaceholder: 'Confirm your password',
    hasAccount: 'Already have an account?',
    termsPrefix: 'I agree to the ',
    termsLink: 'Terms & Conditions',
    termsMiddle: ' and ',
    privacyLink: 'Privacy Policy',
    termsSuffix: '.',
    termsA11y: 'Agree to Terms and Privacy Policy',
    duplicateEmail: 'An account with this email already exists.',
    incorrectCredentials: 'Incorrect email or password.',
    unableToConnect: 'Unable to connect.\nPlease check your internet connection.',
    requestTimeout: 'The request took longer than expected.\nPlease try again.',
    checkDetails: 'Please check your details and try again.',
    genericFailure: 'Something went wrong.\nPlease try again shortly.',
    forgotTitle: 'Forgot Password',
    forgotSubtitle:
      'Password reset is not available yet. You can still enter your email to confirm the flow, then return to sign in.',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    forgotSuccessTitle: 'Not available yet',
    forgotSuccessMessage:
      'Password reset is not available yet. Please sign in with your existing credentials or contact support.',
    forgotA11y:
      'Forgot password. Enter your email to recover access to your VidoraX account.',
    forgotSuccessA11y:
      'Password reset is not available yet. Return to login when you are ready.',
    emailValidA11y: 'Email looks valid',
    nameValidA11y: 'Name looks valid',
    validation: {
      emailRequired: 'Email is required',
      emailInvalid: 'Enter a valid email address',
      passwordRequired: 'Password is required',
      passwordMin: 'Password must be at least {count} characters',
      passwordUpper: 'Include at least one uppercase letter',
      passwordLower: 'Include at least one lowercase letter',
      passwordNumber: 'Include at least one number',
      passwordSpecial: 'Include at least one special character',
      nameRequired: 'Full name is required',
      nameMin: 'Enter at least 2 characters',
      nameMax: 'Name must not exceed 100 characters',
      confirmRequired: 'Confirm your password',
      passwordMismatch: 'Passwords do not match',
      termsRequired: 'Please accept the Terms & Privacy Policy',
      generic: 'Please check this field and try again.',
      ruleLength: 'Minimum {count} characters',
      ruleUpper: 'Uppercase letter',
      ruleLower: 'Lowercase letter',
      ruleNumber: 'Number',
      ruleSpecial: 'Special character',
      strengthWeak: 'Weak',
      strengthMedium: 'Medium',
      strengthStrong: 'Strong',
    },
  },
  home: {
    brand: 'VidoraX',
    greetingWelcome: 'Welcome to VidoraX',
    pasteLink: 'Paste link',
    pasteLinkA11y: 'Paste a link in Browser to open a video page',
    openBrowser: 'Open Browser',
    openBrowserA11y: 'Open the VidoraX browser',
    quickAccess: 'Quick Access',
    quickAccessSubtitle: 'Open your favorite platforms',
    quickAccessA11y: 'Quick access to popular video and social websites',
    openSettingsA11y: 'Open settings',
    activeDownloads: 'Active Downloads',
    noActiveDownloads: 'Nothing downloading right now',
    recentDownloads: 'Recent Downloads',
    noDownloadsYet: 'No downloads yet',
    continueWatching: 'Continue Watching',
    noVideosToContinue: 'Nothing playing right now',
    recentlyWatched: 'Recently Watched',
    watchHistoryEmpty: 'Watch history is empty',
    storage: 'Storage',
    storageUnavailable: 'Storage details unavailable',
    storageUsed: 'Used',
    storageFree: 'Available',
    viewAll: 'View All',
    viewLibraryA11y: 'View all in Player',
    viewDownloadsA11y: 'Open Downloads',
    viewHistoryA11y: 'Open watch history',
    viewStorageA11y: 'Open storage manager',
    resumeA11y: 'Opens the video player',
    refreshA11y: 'Refresh Home',
    downloadingCount: '{count} downloading',
    pausedCount: '{count} paused',
    queuedCount: '{count} queued',
    averageProgressA11y: 'Average download progress {percent} percent',
    storageUsageA11y: 'Player storage {percent} percent of used plus available',
  },
  browser: {
    title: 'Browser',
    addressPlaceholder: 'Search or paste video link',
    addressBar: 'Address bar',
    goBack: 'Go back',
    goForward: 'Go forward',
    goHome: 'Go home',
    tabs: 'Tabs',
    menu: 'Browser menu',
    openMenuA11y: 'Open browser menu',
    newTab: 'New tab',
    newTabA11y: 'Open a new browser tab',
    tabsLimitReached: 'Maximum 10 tabs open',
    tabsLimitReachedA11y: 'Maximum of 10 browser tabs already open',
    tabSwitcherTitle: 'Tabs',
    tabSwitcherCloseA11y: 'Close tab',
    tabSwitcherOpenA11y: 'Open tab switcher',
    tabActiveA11y: 'Active tab',
    closeTab: 'Close tab',
    addBookmark: 'Add bookmark',
    addBookmarkA11y: 'Add bookmark for current page',
    addBookmarkFailed: 'Could not save bookmark',
    alreadyBookmarked: 'Already bookmarked',
    alreadyBookmarkedA11y: 'Current page is already bookmarked',
    bookmarkSaved: 'Bookmark saved',
    linkCopied: 'Link copied',
    copyLinkA11y: 'Copy link to current page',
    sharePageA11y: 'Share current page',
    desktopSiteA11y: 'Request desktop version of current site',
    desktopSiteEnabled: 'Desktop site enabled',
    desktopSiteDisabled: 'Mobile site enabled',
    openExternalA11y: 'Open current page in external browser',
    openExternalFailed: 'Unable to open in external browser',
    openDownloadsA11y: 'Open downloads',
    activeDownloads: 'Active Downloads',
    activeDownloadsA11y: 'Open active downloads',
    recentDownloads: 'Recent Downloads',
    recentDownloadsA11y: 'Open recent downloads',
    continueWatching: 'Continue Watching',
    continueWatchingA11y: 'Open continue watching in Player',
    recentlyWatched: 'Recently Watched',
    recentlyWatchedA11y: 'Open recently watched in Player',
    openSettingsA11y: 'Open settings',
    aiAssistant: 'AI assistant',
    settings: 'Settings',
    sharePage: 'Share page',
    openExternal: 'Open in external browser',
    copyLink: 'Copy link',
    readerMode: 'Reader mode',
    translatePage: 'Translate page',
    desktopSite: 'Desktop site',
    qrCode: 'Scan QR code',
    bookmarks: 'Bookmarks',
    history: 'History',
    downloads: 'Downloads',
    goToWebsite: 'Go to website',
    searchGoogle: 'Search Google for “{query}”',
    addressEmpty: 'Enter a website address or search the web.',
    addressInvalid: 'That doesn’t look like a valid address. Try a website or a search.',
    youtubeNotSupported: 'YouTube downloads are not supported',
    addressBlocked: 'This type of address can’t be opened for security reasons.',
    addressIncomplete: 'That address is incomplete. Try adding a full website name.',
    mediaDetected: 'Downloadable video detected',
    addressHint: 'Enter a website address or search query. Suggestions appear as you type.',
    sslHomeHint: 'Leave this insecure connection and return to the browser home page',
    sslRetryHint: 'Retry loading this page. Only continue if you trust the website',
    retryHint: 'Reload the page and try again',
    goHomeHint: 'Return to the browser home page',
    dismissSuggestions: 'Dismiss suggestions',
    suggestionsA11y: 'Address bar suggestions',
    goAction: 'Go',
    clearAddressA11y: 'Clear address',
    loadingPageA11y: 'Loading page',
    pageProgressA11y: 'Page load progress',
    webContentA11y: 'Web content',
    openBookmarksA11y: 'Open bookmarks',
    openHistoryA11y: 'Open browsing history',
    media: {
      videoAvailable: 'Video available',
      alreadyDownloaded: 'Already downloaded',
      detectingVideo: 'Detecting video',
      downloadingVideo: 'Downloading…',
      downloadedVideo: 'Downloaded',
      protectedVideo: 'Protected video — can’t be downloaded',
      unsupportedVideo: 'This video can’t be downloaded',
      download: 'Download',
      preparingDownload: 'Preparing download…',
      cantDownload: "This video can't be downloaded by VidoraX.",
      videoAvailableA11y: 'Video available',
      videoAvailableHint: 'Downloads this video',
      downloadA11y: 'Download this video',
      chooseQualityHint: 'Choose a quality to download.',
    },
    home: {
      dashboardA11y: 'Browser start page',
      startPageA11y: 'Browser start page',
      brandA11y: 'VidoraX',
      startSubtitle: 'Browse or paste a video link to get started.',
      quickAccess: 'Quick Access',
      bookmarksTab: 'BOOKMARKS',
      recentHistory: 'HISTORY',
      viewAll: 'View all',
      viewAllHistoryA11y: 'View all browsing history',
      viewAllBookmarksA11y: 'View all bookmarks',
      clearHistoryA11y: 'Clear browsing history',
      clearHistoryTitle: 'Clear history?',
      clearHistoryMessage: 'Remove all browsing history from this device.',
      clearHistoryConfirm: 'Clear',
      noRecentHistory: 'Pages you visit will appear here.',
      noBookmarks: 'Saved bookmarks will appear here.',
      openSiteA11y: 'Open {name}',
      openSiteHint: 'Opens the website inside VidoraX browser',
      openBookmarkA11y: 'Open bookmark {title}',
      tabCountA11y: '{count} tab open',
    },
    saveBookmarkA11y: 'Save bookmark',
    removeBookmarkA11y: 'Remove bookmark',
    pullToRefreshHint: 'Pull down to refresh the page',
    pageLoadingHint: 'Page is loading',
    openSuggestionHint: 'Double tap to open',
    downloadableMedia: 'Downloadable media',
    downloadAvailable: 'Download available',
    mediaDetectedShort: 'Media detected',
    hideDetails: 'Hide details',
    showDetails: 'Show details',
    less: 'Less',
    details: 'Details',
    formatLabel: 'Format',
    typeLabel: 'Type',
    codecLabel: 'Codec',
    confidenceLabel: 'Confidence',
    downloadUnavailableCta: 'Unavailable',
    addingDownload: 'Adding…',
    downloadCta: 'Download',
    downloadThisMediaA11y: 'Download this media',
    downloadUnavailableMediaA11y: 'Download unavailable for this media',
    startingDownloadAnalysisA11y: 'Starting download analysis',
    downloadAnalysisHint: 'Opens format analysis, then adds a download',
    swipeDownDismiss: 'Swipe down to dismiss',
    swipeDownDismissMulti: '{count} media · swipe down to dismiss',
    swipeDismissHide: 'Swipe down or press dismiss to hide.',
    discoveryCardA11y: '{status}. {title}. {meta}. {hint}',
    errors: {
      invalid_url: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      load_failed: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      network_failure: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      dns_failure: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      connection_interrupted: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      timeout: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      ssl_error: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      http_error: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      unsupported: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      process_terminated: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      unknown: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
    },
  },
  downloads: {
    title: 'Downloads',
    detailsTitle: 'Download Details',
    searchPlaceholder: 'Search downloads...',
    emptyTitle: 'No downloads yet',
    emptyDescription:
      'Open a video in Browser. VidoraX finds downloadable video automatically.',
    emptyAction: 'Open Browser',
    emptySearchTitle: 'No downloads found',
    emptySearchDescription: 'Try a different title, file name, or URL.',
    emptyFilterTitle: 'Nothing here',
    emptyFilterDescription: 'No downloads match this filter.',
    emptyCompletedTitle: 'No completed downloads',
    emptyCompletedDescription: 'Finished downloads will appear in this list.',
    errorTitle: 'Couldn’t load downloads',
    detailsErrorTitle: 'Couldn’t load download',
    detailsMissingTitle: 'Download unavailable',
    detailsMissingDescription: 'This download may have been removed.',
    detailsMissingAction: 'Back to Downloads',
    detailsInfoTitle: 'Download information',
    detailsSourceTitle: 'Source',
    detailsFavoriteHint: 'Add or remove this download from Favorites',
    detailsFavoriteLabel: 'Favorite',
    detailsFavoriteAddLabel: 'Add to favorites',
    detailsFavoriteRemoveLabel: 'Remove from favorites',
    detailsFavoriteErrorTitle: 'Couldn’t update favorite',
    detailsOpenFile: 'Open',
    detailsShareFile: 'Share',
    detailsFileUnavailable: 'File is not available on this device.',
    fileUnavailableTitle: 'File unavailable',
    deleteTitle: 'Delete from VidoraX?',
    deleteMessage:
      'Delete this download from VidoraX? Copies saved outside VidoraX will not be deleted.',
    deleteConfirm: 'Delete',
    deleteCancel: 'Cancel',
    removeTitle: 'Remove from Downloads?',
    removeMessage:
      'This clears the download from this list. The video stays in Player, and any copy you saved to your device is untouched.',
    removeConfirm: 'Remove',
    deleteFailed: 'Unable to delete this download',
    deleteMissingConfirm: 'Remove from Player',
    notifications: {
      channelName: 'Download updates',
      downloadingTitle: 'Downloading',
      preparingTitle: 'Preparing download',
      waitingWifiTitle: 'Waiting for Wi-Fi',
      pausedTitle: 'Download paused',
      retryingTitle: 'Retrying download',
      completedTitle: 'Download complete',
      failedTitle: 'Download failed',
      tapForDetails: 'Tap to view details',
      reasons: {
        sessionExpired: 'Session expired',
        sourceUnavailable: 'Source unavailable',
        fileValidationFailed: 'File validation failed',
        networkError: 'Network error',
      },
    },
    export: {
      saveToDevice: 'Save to device',
      saving: 'Saving…',
      saved: 'Saved to device',
      alreadySaved: 'Already saved to device',
      unableToSave: 'Unable to save this file',
      notEnoughStorage: 'Not enough storage',
      cancelled: 'Save cancelled',
    },
    filterTitle: 'Filter',
    filterSubtitle: 'Show downloads by status',
    sortTitle: 'Sort',
    sortSubtitle: 'Order by date added',
    loadingAnnouncement: 'Loading downloads',
    endOfList: 'You’re all caught up',
    resetControls: 'Reset',
    primaryPause: 'Pause download',
    primaryResume: 'Resume download',
    primaryCancel: 'Cancel download',
    primaryRetry: 'Retry download',
    primaryOpen: 'Open downloaded file',
    primaryShare: 'Share downloaded file',
    primaryRemove: 'Delete download',
    secondaryCancel: 'Cancel download',
    successToast: 'Added to Downloads',
    completedToast: 'Video downloaded',
    alreadyDownloadingToast: 'Video is already downloading',
    alreadyDownloadedToast: 'Video already downloaded',
    filterAll: 'All',
    filterRunning: 'Running',
    filterQueued: 'Queued',
    filterPaused: 'Paused',
    filterCompleted: 'Completed',
    filterFailed: 'Failed',
    sortNewest: 'Newest',
    sortOldest: 'Oldest',
    statusQueued: 'Queued',
    statusDownloading: 'Running',
    statusPaused: 'Paused',
    statusCompleted: 'Completed',
    statusFailed: 'Failed',
    statusCancelled: 'Cancelled',
    executionForeground: 'Downloading',
    executionBackground: 'Downloading in background',
    waitingWifi: 'Waiting for Wi-Fi',
    waitingNetwork: 'Waiting for network',
    retrying: 'Retrying',
    queued: 'Queued',
    preparing: 'Preparing download',
    starting: 'Starting download…',
    finalizing: 'Finalizing',
    processingMerging: 'Merging audio and video',
    processingRemuxing: 'Preparing the video file',
    processingTranscoding: 'Converting the video',
    processingVerifying: 'Checking the video',
    qualitySheetTitle: 'Add download',
    qualitySheetSubtitle: 'Paste a media link. We’ll check what can be saved.',
    urlLabel: 'Link',
    urlPlaceholder: 'https://example.com/video.mp4',
    urlHelper: 'Direct video, audio, or stream links work best.',
    analyzeAction: 'Analyze link',
    analyzing: 'Checking this link…',
    pasteAction: 'Paste',
    retryAction: 'Try again',
    changeLinkAction: 'Use a different link',
    downloadAction: 'Start download',
    downloadNamed: 'Download {label}',
    downloadingAction: 'Starting download…',
    qualitiesTitle: 'Choose format',
    qualityEmptyTitle: 'Nothing downloadable here',
    qualityErrorTitle: 'Couldn’t analyze this link',
    unsupportedBadge: 'Can’t download',
    missingUrl: 'Paste a link to continue',
    invalidUrl: 'Enter a valid http or https link',
    closeLabel: 'Close',
    selectionHint: 'Select a format to download',
    selectedHint: 'Selected for download',
    untitled: 'Untitled download',
    infoFormat: 'Format',
    infoPlatform: 'Platform',
    infoDuration: 'Duration',
    infoQuality: 'Quality',
    infoResolution: 'Resolution',
    infoBitrate: 'Bitrate',
    infoFileSize: 'File Size',
    infoRetryAttempts: 'Retry Attempts',
    infoLocalFile: 'Local file',
    availableOnDevice: 'Available on device',
    missingOnDevice: 'File missing on device',
    localFileIncomplete: 'Local file incomplete',
    infoFolder: 'Folder',
    infoDownloaded: 'Downloaded',
    infoCreatedDate: 'Created Date',
    infoDownloadedDate: 'Downloaded Date',
    downloadedProgress: '{size} downloaded',
    failedBanner: 'Download failed',
    retryingSoon: 'Retrying',
    retryingSoonBody: 'Waiting for the next automatic retry.',
    retryingSoonA11y: 'Retrying download soon',
    statusA11y: 'Status {label}',
    moveToFolder: 'Move to folder',
    moveToFolderHint: 'Move this media into a logical folder',
    moveToFolderSubtitle: 'Choose where this media should live',
    manageFolders: 'Manage folders',
    manageFoldersSubtitle: 'Create, rename, or delete logical folders',
    newFolder: 'New folder',
    folderName: 'Folder name',
    yourFolders: 'Your folders',
    noFoldersYet: 'No folders yet — everything starts in Unfiled.',
    deleteFolder: 'Delete folder',
    deleteFolderMessage:
      'Items in this folder will be moved to Unfiled. Physical files are untouched.',
    renameDisplayName: 'Update the media display name',
    newName: 'New name',
    openQueue: 'Open download queue',
    openQueueHint: 'Shows active downloads and items waiting in line',
    openFavoritesA11y: 'Open favorites',
    openFavoritesHint: 'Shows downloads you have favorited',
    pasteLinkHint: 'Opens Browser so you can paste or open a video page',
    opensDetails: 'Opens download details',
    favoriteEnabled: 'Favorite enabled',
    favoriteDisabled: 'Favorite disabled',
    actionsA11y: 'Download actions',
    pauseNamedA11y: 'Pause {title}',
    resumeNamedA11y: 'Resume {title}',
    pauseUnsupported: 'This source can’t resume, so pausing would restart it',
    cancelNamedA11y: 'Cancel {title}',
    percentA11y: '{percent} percent',
    queuePositionA11y: 'position {position}',
    searchA11y: 'Search downloads',
    retryLoadA11y: 'Retry loading downloads',
    refreshListA11y: 'Refresh downloads',
    loadingA11y: 'Loading downloads',
    loadingDetailsA11y: 'Loading download details',
    thumbnailA11y: 'Thumbnail for {title}',
    searchFilterHint: 'Filters by title, file name, or URL',
    resetFiltersHint: 'Clears search, filter, and sort',
    analyzeLinkHint: 'Checks the link for downloadable formats',
  },
  deviceVideos: {
    title: 'On this device',
    subtitle: 'Videos already saved on your phone',
    empty: 'No videos found on this device.',
    permission: 'Allow VidoraX to read your videos to play them here.',
    allow: 'Allow access',
    unavailable: 'Not available in this build.',
    limited: 'Showing the videos you gave VidoraX access to',
    open: 'Videos on this device',
  },
  library: {
    title: 'Player',
    searchPlaceholder: 'Search downloaded videos',
    emptyTitle: 'No downloads yet',
    emptyDescription:
      'Completed downloads that are available on this device will appear here.',
    emptyAction: 'Go to Downloads',
    emptySearchTitle: 'No videos found',
    emptySearchDescription: 'Try a different title, file name, quality, or folder name.',
    emptyFilterTitle: 'No videos found',
    emptyFilterDescription: 'Try All, or choose a different filter.',
    emptyFavoritesTitle: 'No favorites yet',
    emptyFavoritesDescription: 'Mark videos as favorites to find them here.',
    emptyFolderTitle: 'This folder is empty',
    emptyFolderDescription: 'Move videos into this folder from download details.',
    errorTitle: 'Couldn’t load your library',
    errorRetry: 'Try again',
    offlineHint: 'Showing downloads saved on this device.',
    filterTitle: 'Filter',
    filterSubtitle: 'Show videos by category',
    sortTitle: 'Sort',
    sortSubtitle: 'Order your library',
    qualityTitle: 'Quality',
    qualitySubtitle: 'Show videos at a specific quality',
    resetControls: 'Reset',
    viewList: 'List view',
    viewGrid: 'Grid view',
    loadingAnnouncement: 'Loading library',
    emptyRecentlyWatchedTitle: 'No Recently Watched videos',
    emptyRecentlyWatchedDescription:
      'Videos you play will appear here, ordered by last watched.',
    continueWatchingTitle: 'Continue Watching',
    continueWatchingEmpty: 'No videos to continue',
    continueWatchingEmptyDescription:
      'Unfinished videos you start watching will show up here.',
    watchedBadge: 'Watched',
    watchHistoryTitle: 'Watch History',
    filterAll: 'All',
    filterFavorites: 'Favorites',
    filterRecentlyDownloaded: 'Recently Downloaded',
    filterRecentlyWatched: 'Recently Watched',
    filterFolder: 'Folder',
    sortNewest: 'Newest',
    sortOldest: 'Oldest',
    sortNameAsc: 'Name A–Z',
    sortNameDesc: 'Name Z–A',
    sortLargest: 'Largest',
    sortSmallest: 'Smallest',
    sortRecentlyPlayed: 'Recently Played',
    searchA11y: 'Search downloaded videos',
    watchProgressA11y: 'Watch progress',
    retryLoadA11y: 'Retry loading library',
    refreshListA11y: 'Refresh library',
    favoriteA11y: 'Favorite',
    searchFilterHint: 'Filters by title, file name, quality, or folder name',
    resetFiltersHint: 'Clears search, filter, and sort',
    actionsTitle: 'Completed file',
    actionsSubtitle: 'Open, share, save, or delete',
    openWith: 'Open with…',
    share: 'Share',
    play: 'Play',
    saveToDevice: 'Save to device',
    deleteFromVidoraX: 'Delete from VidoraX',
    fileUnavailable: 'File unavailable',
    actionFailed: 'Unable to complete that action.',
    longPressHint: 'Shows Open, Share, Save, and Delete actions',
    playHint: 'Opens the video player',
    deleteTitle: 'Delete from VidoraX?',
    deleteMessage:
      'Delete this download from VidoraX? Copies saved outside VidoraX will not be deleted.',
    deleteConfirm: 'Delete',
    deleteCancel: 'Cancel',
    deleteFailed: 'Unable to delete this download',
    removeFromLibrary: 'Remove from Player',
    saving: 'Saving…',
    savedToDevice: 'Saved to device',
    alreadySavedToDevice: 'Already saved to device',
    unableToSave: 'Unable to save this file',
  },
  player: {
    mini: {
      openA11y: 'Now playing: {title}. Open player',
      openHint: 'Opens the full player. Swipe sideways to close.',
      close: 'Close player',
    },
    continueWatching: 'Continue watching?',
    continueWatchingBody: 'Pick up where you left off, or start from the beginning.',
    startOver: 'Start Over',
    resumeFrom: 'Resume from {time}',
    play: 'Play video',
    pause: 'Pause video',
    replay: 'Replay video',
    rewind: 'Rewind 10 seconds',
    forward: 'Forward 10 seconds',
    previousVideo: 'Previous video',
    nextVideo: 'Next video',
    lockScreen: 'Lock screen',
    unlockScreen: 'Unlock screen',
    screenLocked: 'Screen locked · tap to unlock',
    mute: 'Mute video',
    unmute: 'Unmute video',
    preparing: 'Preparing video',
    playbackSpeed: 'Playback speed',
    playbackSpeedSelected: 'Playback speed, {rate} selected',
    speedSelected: 'Selected {rate}',
    orientationTitle: 'Orientation',
    orientationSelected: 'Selected {mode}',
    orientation: {
      auto: 'Auto',
      portrait: 'Portrait',
      landscape: 'Landscape',
    },
    enterFullscreen: 'Enter fullscreen',
    exitFullscreen: 'Exit fullscreen',
    goBack: 'Go back',
    untitled: 'Video',
    seekTimelineA11y: 'Seek timeline',
    videoSurfaceA11y: 'Video surface',
    surfaceHint: 'Tap to show controls. Swipe the left edge for brightness, the right edge for volume. Double tap a side to seek. Pinch to zoom; double tap resets the zoom.',
    hud: {
      brightness: 'Brightness {percent} percent',
      volume: 'Volume {percent} percent',
      zoom: 'Zoom {percent} percent',
    },
    missingFile: 'This video is no longer on this device.',
    unsupported: 'This video cannot be played on this device.',
    errors: {
      MEDIA_NOT_FOUND: {
        title: 'Not found',
        message: 'This video could not be found in your library.',
      },
      FILE_UNAVAILABLE: {
        title: 'Unavailable',
        message: 'File is no longer available.',
      },
      SOURCE_RESOLUTION_FAILED: {
        title: 'Unable to play',
        message: 'Unable to prepare this video for playback.',
      },
      UNSUPPORTED_MEDIA: {
        title: 'Unsupported format',
        message: "This video's format or codec isn't supported on this device.",
      },
      CORRUPT_MEDIA: {
        title: 'Unreadable video',
        message: 'This video file appears to be damaged or unreadable.',
      },
      PERMISSION_DENIED: {
        title: 'Permission needed',
        message: 'VidoraX does not have permission to play this file.',
      },
      PLAYER_INIT_FAILED: {
        title: 'Player error',
        message: 'Unable to start the video player.',
      },
      PLAYBACK_FAILED: {
        title: 'Playback error',
        message: 'Playback failed. Try again.',
      },
      PREPARATION_TIMEOUT: {
        title: 'Still preparing',
        message: 'This video is taking too long to prepare.',
      },
    },
  },
  settings: {
    screenTitle: 'Settings',
    screenSubtitle: 'Preferences for this device',
    loadingA11y: 'Loading settings',
    appearanceSection: 'Appearance',
    appearanceDescription: 'Look and feel of the app',
    defaultBrowser: 'Default browser',
    defaultBrowserHintOn: 'VidoraX opens web links on this device.',
    defaultBrowserHintOff: 'Open web links from other apps in VidoraX.',
    defaultBrowserValueOn: 'On',
    defaultBrowserValueOff: 'Set up',
    defaultBrowserUnavailable: 'Not available on this device',
    generalSection: 'General',
    generalDescription: 'Language and regional preferences',
    downloadsSection: 'Downloads',
    downloadsDescription: 'How downloads behave on this device',
    downloadSettings: 'Download Settings',
    downloadSettingsHint: 'Wi-Fi, resume, concurrency, and download alerts',
    notificationsSection: 'Notifications',
    notificationsDescription: 'Alerts and activity updates',
    aboutSection: 'About',
    aboutDescription: 'App information',
    legalSection: 'Legal',
    legalDescription: 'Privacy, terms, and app information',
    privacySection: 'Privacy',
    privacySectionDescription: 'Protect access to VidoraX on this device',
    appLock: 'App Lock',
    appLockHint: 'Require a PIN when returning to VidoraX',
    changePin: 'Change PIN',
    changePinHint: 'Replace your App Lock PIN',
    changePinA11y: 'Opens Change PIN',
    generateRecoveryCode: 'Generate New Recovery Code',
    generateRecoveryCodeHint: 'Replace your saved recovery code',
    generateRecoveryCodeA11y: 'Opens Generate New Recovery Code',
    helpAccountSection: 'Help & support',
    helpAccountDescription: 'Help Center and problem reporting',
    supportSection: 'Support',
    supportSectionDescription: 'Help, reporting, and feedback',
    howToUseSection: 'How to use VidoraX',
    howToUseDescription: 'Download a video in a few steps',
    howToUseStep1: 'Paste or open a supported video link.',
    howToUseStep2: 'Browse or scroll to the video.',
    howToUseStep3: 'Wait for “Video available”.',
    howToUseStep4: 'Tap it.',
    howToUseStep5: 'Choose a quality, if available.',
    howToUseStep6: 'Download the video.',
    howToUseStep7: 'Find completed videos in Downloads / Gallery.',
    howToUseNoteYouTube: 'YouTube downloads are not supported.',
    howToUseNoteDrm: 'DRM-protected videos cannot be downloaded.',
    helpSupportSection: 'Help & Support',
    helpSupportDescription: 'Contact the VidoraX team',
    contactSupport: 'Contact Support',
    contactSupportA11y: 'Opens your email app to write to VidoraX support',
    reportIssue: 'Report an Issue',
    reportIssueHint: 'Email us what went wrong',
    reportIssueA11y: 'Opens your email app with an issue report',
    noEmailAppTitle: 'No email app found',
    noEmailAppMessage: 'Install or set up an email app, or write to {email} from any device.',
    copyEmailAddress: 'Copy address',
    accountSectionTitle: 'Device',
    accountSectionDescription: 'Preferences stored on this device',
    storageSection: 'Storage',
    storageSectionDescription: 'Manage downloaded media on this device',
    manageStorage: 'Manage Storage',
    manageStorageHint: 'Open Player to review and remove downloads',
    manageStorageA11y: 'Opens Player to manage storage',
    reportProblem: 'Report a Problem',
    reportProblemHint: 'Describe an issue so we can investigate',
    reportProblemA11y: 'Opens the Report a Problem form',
    rateVidoraX: 'Rate VidoraX',
    rateVidoraXHint: 'Rate VidoraX on the Play Store',
    rateVidoraXA11y: 'Opens the Play Store listing to rate VidoraX',
    signOutHint: 'Not used — VidoraX has no account sign-out',
    signOutA11y: 'Not used — VidoraX has no account sign-out',
    comingSoon: 'Coming Soon',
    emptyTitle: 'Settings unavailable',
    emptyDescription:
      'We could not find your preferences. Pull to refresh or tap retry to try again.',
    signOut: 'Sign Out',
    theme: 'Theme',
    themeHint: 'System, Red, or Dark',
    themeA11y: 'Theme preference',
    themeLight: 'System',
    themeLogo: 'Red',
    themeDark: 'Dark',
    themeLightA11y: 'System theme',
    themeLogoA11y: 'Red theme',
    themeDarkA11y: 'Dark theme',
    language: 'Language',
    languageHint: 'Display language for VidoraX',
    languageSheetTitle: 'Choose language',
    languageSheetSubtitle: 'Select a language. The app updates immediately.',
    languageOpenHint: 'Opens language selection',
    languageSelected: '{label} selected',
    languageNameEn: 'English',
    languageNameUr: 'Urdu',
    wifiOnly: 'Wi-Fi Only',
    wifiOnlyHint: 'Download only on Wi-Fi networks',
    autoResume: 'Auto Resume',
    autoResumeHint: 'Resume interrupted downloads automatically',
    downloadDirectory: 'Download Location',
    downloadDirectoryHint: 'App-managed download storage on this device',
    notifications: 'Notifications',
    notificationsHint: 'Receive download and activity alerts',
    aboutApp: 'About VidoraX',
    aboutAppHint: 'Version, updates, and product information',
    privacyPolicy: 'Privacy Policy',
    privacyHint: 'How VidoraX handles your information',
    termsConditions: 'Terms & Conditions',
    termsHint: 'Rules for using VidoraX',
    support: 'Help & Support',
    supportHint: 'Get help or contact us',
    profile: 'Device preferences',
    profileHint: 'Language, theme, and download preferences on this device',
    successTitle: 'Preference saved',
    successMessage: 'Your settings are saved on this device.',
    pendingSyncTitle: 'Saved on this device',
    pendingSyncMessage: 'Your preference is saved on this device.',
    preferenceErrorTitle: 'Could not save preference',
    loadUnauthorized: 'Settings could not be read from this device.',
    saveUnauthorized: 'Settings could not be saved on this device.',
    forbidden: 'That settings change is not available.',
    invalidPreference: 'That preference value is not supported. Please choose another.',
    unsupportedLanguage: 'That language is not supported yet. Please choose another.',
    unsupportedTheme: 'That theme option is not supported. Please choose another.',
    loadFailed: 'We could not load your settings. Please try again.',
    saveFailed: 'We could not save your settings. Please try again.',
    currentValue: 'Current: {value}.',
    aboutAppA11y: 'Opens the About screen',
    privacyA11y: 'Opens the Privacy Policy',
    termsA11y: 'Opens the Terms and Conditions',
    supportA11y: 'Opens the Help and Support screen',
    profileA11y: 'Opens device preferences',
    downloadSettingsTitle: 'Download Settings',
    downloadSettingsSubtitle: 'Control how downloads behave on this device',
    behaviorSection: 'Download behavior',
    behaviorDescription: 'When new downloads start and how they recover',
    performanceSection: 'Performance',
    performanceDescription: 'How many downloads can run at once',
    downloadNotificationsSection: 'Notifications',
    downloadNotificationsDescription: 'Get notified when downloads finish or fail.',
    wifiOnlyLong: 'Download over Wi-Fi only',
    wifiOnlyLongHint: 'New downloads wait until Wi-Fi is available.',
    saveToGallery: 'Save to Gallery',
    saveToGalleryHint: 'Finished videos also appear in your phone’s Gallery app.',
    autoResumeLong: 'Automatically resume interrupted downloads',
    autoResumeLongHint: 'Resume eligible interrupted downloads when safe.',
    maxConcurrent: 'Maximum simultaneous downloads',
    maxConcurrentHint: 'Choose how many downloads can run at once.',
    downloadNotifications: 'Download notifications',
    downloadNotificationsHint: 'Get notified when downloads finish or fail.',
    notificationsPermissionRequired: 'Notifications permission required',
    notificationsPermissionHint:
      'Allow notifications in Android settings to receive download alerts.',
    openSystemSettings: 'Open Android settings',
    downloadSettingsSuccessMessage: 'Your download settings were updated.',
  },
  profile: {
    welcomePrefix: 'Welcome back,',
    accountSection: 'Account Information',
    appSection: 'Application Information',
    actionsSection: 'Quick Actions',
    actionsDescription: 'Manage your account preferences',
    emptyTitle: 'Profile unavailable',
    emptyDescription:
      'We could not find your account details. Pull to refresh or tap retry to try again.',
    comingSoon: 'Coming Soon',
    editSuccessTitle: 'Profile updated',
    editSuccessMessage: 'Your changes are saved and synced across VidoraX.',
    editProfile: 'Edit Profile',
    editProfileSubtitle: 'Update your name and photo',
    editProfileHint: 'Opens the Edit Profile screen',
    changePassword: 'Change Password',
    changePasswordSubtitle: 'Keep your account secure',
    changePasswordHint: 'Password change is not available in this release',
    privacy: 'Privacy',
    privacySubtitle: 'How VidoraX handles your information',
    privacyHint: 'Opens the Privacy screen',
    about: 'About',
    aboutSubtitle: 'App information and legal details',
    aboutHint: 'Opens the About screen',
    appVersion: 'App Version',
    buildVersion: 'Build Version',
    environment: 'Environment',
    environmentDevelopment: 'Development',
    platform: 'Platform',
    appSectionDescription: 'Build and runtime details',
    avatarSheetTitle: 'Profile photo',
    avatarSheetSubtitle: 'Choose how you want to update your photo',
    takePhoto: 'Take Photo',
    chooseFromLibrary: 'Choose from Library',
    removePhoto: 'Remove Photo',
    removeConfirmTitle: 'Remove profile photo?',
    removeConfirmMessage: 'Your photo will be deleted and replaced with your initials.',
    opening: 'Opening…',
    optimizing: 'Optimizing photo…',
    uploading: 'Uploading',
    removing: 'Removing photo…',
    cancelUpload: 'Cancel upload',
    retryUpload: 'Retry upload',
    openSettings: 'Open Settings',
    verified: 'Verified',
    unverified: 'Unverified',
    admin: 'Admin',
    memberSince: 'Member since {date}',
    accountStatus: 'Account Status',
    userId: 'User ID',
    a11yProfile: 'Profile for {name}, {email}. Member since {date}',
    a11yAdd: 'Add profile photo',
    a11yChange: 'Change profile photo',
    a11yHint: 'Opens options to take a photo, choose one, or remove it.',
    loadingA11y: 'Loading profile',
    fullNameA11y: 'Full name',
    retrySaveA11y: 'Retry saving profile',
    discardChangesA11y: 'Discard profile changes',
    nameLengthHint: 'Required. Between 2 and 100 characters.',
  },
  history: {
    title: 'History',
    searchPlaceholder: 'Search history',
    emptyTitle: 'No browsing history',
    emptyDescription: 'Pages you visit in the browser will show up here.',
    emptyAction: 'Open browser',
    emptySearchTitle: 'No matching pages',
    emptySearchDescription: 'Try a different title, site, or URL.',
    errorTitle: 'Couldn’t load history',
    clearTitle: 'Clear browsing history?',
    clearMessage:
      'This permanently removes your saved browsing history from this device.',
    clearConfirm: 'Clear all',
    clearCancel: 'Cancel',
    deleteTitle: 'Remove this page?',
    deleteMessage: 'This page will be removed from your browsing history.',
    deleteConfirm: 'Remove',
    deleteCancel: 'Cancel',
    loadingAnnouncement: 'Loading browsing history',
    endOfList: 'You’re all caught up',
    clearAllA11y: 'Clear all browsing history',
    openHint: 'Double tap to open',
    removeOnlyHint: 'Removes only this page from your history',
    itemA11y: '{title}. {url}. Visited {relative}',
    removeItemA11y: 'Remove {title} from history',
  },
  bookmarks: {
    title: 'Bookmarks',
    searchPlaceholder: 'Search bookmarks',
    emptyTitle: 'No bookmarks yet',
    emptyDescription: 'Tap the bookmark icon while browsing to save pages here.',
    emptyAction: 'Open browser',
    emptySearchTitle: 'No matching bookmarks',
    emptySearchDescription: 'Try a different title, site, or URL.',
    errorTitle: 'Couldn’t load bookmarks',
    clearTitle: 'Clear all bookmarks?',
    clearMessage:
      'This permanently removes every saved bookmark from this device.',
    clearConfirm: 'Clear all',
    clearCancel: 'Cancel',
    deleteTitle: 'Remove bookmark?',
    deleteMessage: 'This page will be removed from your bookmarks.',
    deleteConfirm: 'Remove',
    deleteCancel: 'Cancel',
    loadingAnnouncement: 'Loading bookmarks',
    endOfList: 'You’re all caught up',
    toggleFailed: 'Couldn’t update bookmark. Try again.',
    clearAllA11y: 'Clear all bookmarks',
    bookmarkedA11y: 'Bookmarked',
    openHint: 'Double tap to open',
    removeOnlyHint: 'Removes only this bookmark',
    itemA11y: '{title}. {url}. Bookmarked {date}',
    removeItemA11y: 'Remove {title} from bookmarks',
  },
  favorites: {
    title: 'Favorites',
    searchPlaceholder: 'Search favorites',
    emptyTitle: 'No favorites yet',
    emptyDescription: 'Save downloads you care about from Download Details.',
    emptyAction: 'Open Downloads',
    emptySearchTitle: 'No favorites found',
    emptySearchDescription: 'Try a different title or URL.',
    errorTitle: 'Couldn’t load favorites',
    removeTitle: 'Remove favorite?',
    removeMessage: 'This item will be removed from your favorites.',
    removeConfirm: 'Remove',
    removeCancel: 'Cancel',
    unavailableTitle: 'Download unavailable',
    unavailableDescription:
      'The original download is no longer available. You can remove this favorite.',
    unavailableAction: 'Remove favorite',
    loadingAnnouncement: 'Loading favorites',
    endOfList: 'You’re all caught up',
    toggleFailed: 'Couldn’t update favorite. Try again.',
    openFailed: 'Couldn’t open this favorite.',
    favoritedA11y: 'Favorited',
    removeOnlyHint: 'Removes only this favorite',
    itemA11y: '{title}. Favorited. {meta}',
    itemUnavailableA11y: '{title}. Favorite. Download unavailable.',
    openHint: 'Double tap to open download details',
    unavailableHint: 'Double tap for options. Long press to remove.',
    removeItemA11y: 'Remove {title} from favorites',
    downloadUnavailableLabel: 'Download unavailable',
  },
  watchHistory: {
    title: 'Watch History',
    emptyTitle: 'No watch history yet',
    emptyDescription: 'Videos you play will appear here.',
    missing: 'No longer on this device',
    errorTitle: 'Couldn’t load watch history',
    offlineHint: 'Showing watch progress saved on this device.',
    watchProgressA11y: 'Watch progress',
  },
  about: {
    title: 'About',
    description: 'Learn more about VidoraX, version info, and legal details.',
    a11y: 'About screen',
    versionLabel: 'Version {version}',
    versionBuildLabel: 'Version {version} (Build {build})',
    tagline: 'Browser & Video Downloader',
    productDescription:
      'VidoraX is an Android-focused browser, media, and download manager. Organize and play supported downloadable media you are allowed to save — not every site or video is downloadable, and DRM or encrypted content is not supported.',
    identityA11y: 'VidoraX. Browser and video downloader. Version {version}, build {build}.',
    logoA11y: 'VidoraX logo',
    appInformation: 'App Information',
    appSection: 'App',
    version: 'Version',
    build: 'Build',
    platform: 'Platform',
    checkForUpdates: 'Check for Updates',
    checkForUpdatesA11y: 'Opens the Play Store listing to review available updates',
    updateIdleDescription: 'Review updates on the Play Store when a listing is available.',
    updateChecking: 'Opening the Play Store…',
    updateOpenedStore: 'Play Store opened so you can review updates.',
    updateFailed: 'Couldn’t open the Play Store. Try again later.',
    updateUnavailableDescription:
      'Update checking will be available after the Play Store listing is published.',
    updateUnavailableA11y: 'Update checking is not available yet',
    rateVidoraX: 'Rate VidoraX',
    rateDescription: 'Rate VidoraX on the Play Store',
    rateA11y: 'Opens the VidoraX Play Store listing to leave a rating',
    rateUnavailableDescription:
      'Rating will be available after the Play Store listing is published.',
    rateUnavailableA11y: 'Rating is not available yet',
    openSourceLicenses: 'Open-source licenses',
    helpLegal: 'Help & Legal',
    helpSupport: 'Help & Support',
    helpSupportDescription: 'Browse help topics and common questions',
    helpSupportA11y: 'Opens Help and Support',
    privacyPolicy: 'Privacy Policy',
    privacyDescription: 'How VidoraX handles information on this device',
    privacyA11y: 'Opens Privacy Policy',
    privacy: 'Privacy',
    termsConditions: 'Terms & Conditions',
    termsDescription: 'Terms for using VidoraX',
    termsA11y: 'Opens Terms and Conditions',
    terms: 'Terms',
    support: 'Support',
    copyrightLine: '© {year} {brand}',
    allRightsReserved: 'All rights reserved.',
    copyrightA11y: 'Copyright {year} {brand}. All rights reserved.',
  },
  support: {
    title: 'Help & Support',
    description:
      'Search help topics, browse categories, and find answers about downloads, the Player tab, playback, and settings — all available offline.',
    a11y: 'Help and Support screen',
    searchPlaceholder: 'Search help',
    searchA11y: 'Search help articles',
    searchHint: 'Filters help articles as you type',
    clearSearchA11y: 'Clear search',
    categoriesHeading: 'Categories',
    popularHeading: 'Popular questions',
    resultsHeading: 'Search results',
    categoryFaqsHeading: 'Questions',
    noResultsTitle: 'No help articles found',
    noResultsDescription: 'Try a different keyword, or browse a category below.',
    showAllCategories: 'All categories',
    showAllCategoriesA11y: 'Show all help categories',
    expandA11y: 'Expands the answer',
    collapseA11y: 'Collapses the answer',
    faqExpandedHint: 'Expanded',
    faqCollapsedHint: 'Collapsed',
    privacyHeading: 'Privacy',
    privacyQuestions: 'Privacy questions',
    privacyQuestionsHint: 'Open the in-app Privacy Policy',
    privacyQuestionsA11y: 'Opens Privacy Policy for privacy questions',
    deletionRequest: 'Local data deletion',
    deletionRequestHint: 'See how local data is stored and removed in the Privacy Policy',
    deletionRequestA11y: 'Opens Privacy Policy for local data deletion information',
    emailContact: 'Email support',
    emailContactHint: 'Send a message to {email}',
    emailContactA11y: 'Opens your email app to contact support',
    supportActionsHeading: 'Get help',
    contactSupport: 'Contact Support',
    contactSupportHint: 'Get help from the VidoraX team',
    contactSupportA11y: 'Opens support contact options',
    reportProblem: 'Report a Problem',
    reportProblemHint: 'Describe a technical issue to the VidoraX team',
    reportProblemA11y: 'Opens the report a problem form',
    contactUnavailableTitle: 'Support contact is not available yet.',
    contactUnavailableDescription: 'A support email has not been configured for this build.',
    getHelp: 'Get Help',
    getHelpA11y: 'Get help with this issue',
    getHelpHint: 'Opens help articles related to this issue',
    contextualHeading: 'Related help',
    report: {
      title: 'Report a Problem',
      a11y: 'Report a problem form',
      categoryLabel: 'Issue category',
      categoryPlaceholder: 'Select a category',
      categorySelectedA11y: 'Issue category: {selected}',
      subjectLabel: 'Subject',
      subjectPlaceholder: 'Brief summary of the issue',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Describe what happened and the steps to reproduce it',
      includeDiagnostics: 'Include technical details',
      diagnosticsHint: 'Adds version, OS, and device info to help investigate',
      diagnosticsExpanded: 'Technical details',
      send: 'Send Report',
      sending: 'Sending\u2026',
      successTitle: 'Report prepared',
      successDescription:
        'Your email app has been opened. Please review and send the report from there.',
      failureTitle: 'Could not send report',
      failureDescription: 'Please try again.',
      retry: 'Try again',
      unavailableTitle: 'Support contact not configured',
      unavailableDescription:
        'Support contact is not configured. Your report has not been submitted.',
      privacyNote: 'Technical details are shared according to our Privacy Policy.',
      openPrivacy: 'Privacy Policy',
      categories: {
        download: 'Download issue',
        browser: 'Browser issue',
        playback: 'Playback issue',
        file: 'File / Library issue',
        account: 'App issue',
        other: 'Other',
      },
      validation: {
        categoryRequired: 'Please select an issue category',
        subjectRequired: 'Please enter a subject',
        subjectTooShort: 'Subject must be at least 5 characters',
        subjectTooLong: 'Subject must be 120 characters or fewer',
        descriptionRequired: 'Please describe the issue',
        descriptionTooShort: 'Description must be at least 20 characters',
        descriptionTooLong: 'Description must be 2000 characters or fewer',
      },
    },
    categories: {
      gettingStarted: {
        title: 'Getting Started',
        description: 'Browser, downloads, and playback basics',
      },
      downloads: {
        title: 'Downloads',
        description: 'Failures, pause, Wi-Fi, and unsupported sources',
      },
      libraryFiles: {
        title: 'Player & Files',
        description: 'Rename, delete, share, favorites, and folders',
      },
      playback: {
        title: 'Playback',
        description: 'Playing media, codecs, resume, and fullscreen',
      },
      accountSettings: {
        title: 'Settings',
        description: 'Language, theme, and storage',
      },
    },
    actions: {
      openBrowser: 'Open Browser',
      openDownloads: 'Open Downloads',
      openLibrary: 'Open Player',
      openDownloadSettings: 'Open Download Settings',
      openSettings: 'Open Settings',
      openPrivacy: 'Open Privacy Policy',
      manageStorage: 'Manage Storage',
      openLanguageSettings: 'Open Language Settings',
      openAppearanceSettings: 'Open Appearance Settings',
    },
    faq: {
      howToDownload: {
        question: 'How do I download a video?',
        answer:
          'Open Browser and go to the page with the video, or paste its link into the address bar. When “Video available” appears, tap it, choose a quality if offered, and follow the progress in Downloads. Not every website or video can be downloaded — YouTube, DRM-protected, encrypted and live videos are refused.',
        keywords: 'download, save, video, quality, browser',
      },
      howToUseBrowser: {
        question: 'How do I use the browser?',
        answer:
          'Open Browser from the main tabs. Enter a URL or search in the address bar, browse pages, and use bookmarks or history from the browser menu. Long-press a link to copy it, share it or open it in another browser. The in-app browser is for navigation and detecting supported media — it does not claim every site works the same way.',
        keywords: 'browser, url, address bar, tabs, bookmarks',
      },
      whereDownloadsAppear: {
        question: 'Where do downloads appear?',
        answer:
          'Active and recent transfers appear in Downloads, including queued, paused, failed, and completed items. Finished videos also show in the Player tab, where you can search, filter and play them offline, and by default a copy is saved to your phone’s Gallery (turn this off in Download Settings → Save to Gallery). Use Downloads for transfer status and the Player tab for your saved videos.',
        keywords: 'downloads, library, queue, completed, where',
      },
      howToPlayDownloaded: {
        question: 'How do I play downloaded media?',
        answer:
          'Tap a video in the Player tab, or open a completed item in Downloads and choose Play, to open the VidoraX player. Playback needs the local file to still be on the device and a format your device can decode. If the file was deleted or the codec is unsupported, VidoraX will show an error instead of playing.',
        keywords: 'play, player, library, offline, watch',
      },
      downloadFailed: {
        question: 'Why did my download fail?',
        answer:
          'Downloads can fail when the network drops, the source blocks or changes the file, storage is full, the media source refuses to resume from a partial file, or the media is DRM/encrypted/unsupported. Open the failed item in Downloads to read the error, then retry if the source is still available. Wi-Fi Only can also delay starts until Wi-Fi returns.',
        keywords: 'failed, error, retry, network, storage',
      },
      pauseAndResume: {
        question: 'Can I pause and resume downloads?',
        answer:
          'Yes. Tap Pause on a running download in Downloads and Resume when you want it to continue — this works for video files and for HLS and DASH streams. A stream continues from the last segment it finished; a file continues from the bytes already saved, unless its source refuses to resume a partial file (some social sites’ temporary links), in which case it starts again from zero. A download stopped by a lost connection, by Android closing the app or by a phone restart continues on its own; a download you paused stays paused until you tap Resume.',
        keywords: 'pause, resume, HLS, DASH, stream, auto resume',
      },
      wifiOnlyDownloads: {
        question: 'How does Wi-Fi Only work?',
        answer:
          'Turn on “Download over Wi-Fi only” in Settings → Download Settings to keep downloads waiting until Wi-Fi is available. A running download that loses Wi-Fi waits too. Mobile data will not be used for those downloads until Wi-Fi returns or you turn the setting off.',
        keywords: 'wifi, wi-fi, cellular, data, settings',
      },
      fileUnavailable: {
        question: 'Why is a file unavailable?',
        answer:
          'A completed download needs its local file in app storage. If the file was removed, storage was cleared, or the partial file is missing, VidoraX cannot open, share, or play it. Re-download from a supported source if the media is still available.',
        keywords: 'missing, unavailable, deleted, storage, file',
      },
      unsupportedSource: {
        question: 'Why is a source unsupported?',
        answer:
          'VidoraX only downloads supported, non-DRM sources it can process legally and technically. YouTube, encrypted HLS, DRM-protected media, live streams, and some site protections are blocked with a clear message. Not every website works — an unsupported message means that source cannot be downloaded in VidoraX.',
        keywords: 'unsupported, DRM, encrypted, HLS, live',
      },
      renameMedia: {
        question: 'How do I rename media?',
        answer:
          'In Downloads, open the completed item, tap the menu at the top to open File actions, and choose Rename. This changes the name VidoraX shows. Renaming does not change unsupported formats or restore a missing file.',
        keywords: 'rename, name, display name, edit',
      },
      deleteMedia: {
        question: 'How do I delete media?',
        answer:
          'Long-press a video in the Player tab and choose Delete from VidoraX, or open it in Downloads and choose Delete in File actions. This removes the file from VidoraX on this device; a copy already saved to your Gallery stays there. This cannot be undone from within VidoraX.',
        keywords: 'delete, remove, erase, storage',
      },
      shareMedia: {
        question: 'How do I share a downloaded file?',
        answer:
          'Long-press a video in the Player tab, or open File actions on a completed item in Downloads, and choose Share. VidoraX hands the local file to the system share sheet. Share needs the file to still exist on the device.',
        keywords: 'share, send, export, sheet',
      },
      openExternally: {
        question: 'How do I open a file in another app?',
        answer:
          'Long-press a video in the Player tab and choose Open with…, or choose Open in File actions on a completed download. VidoraX asks the system to open the local file with another app if one is available. If no suitable app is installed, use Share instead.',
        keywords: 'open, external, another app, intent',
      },
      favorites: {
        question: 'How do favorites work?',
        answer:
          'Open a completed item in Downloads and tap the heart at the top to make it a favorite. Favorites appear in the Player tab’s Favorites filter and the Favorites list so you can find important items faster. Favoriting does not re-download or protect a file from deletion.',
        keywords: 'favorite, star, filter, library',
      },
      folders: {
        question: 'How do folders work?',
        answer:
          'Open a completed item in Downloads and tap its Folder row to move it into a folder — you can create, rename and delete folders there too. In the Player tab, the Folder filter shows one folder’s videos. Folders only group media on this device; they do not sync as a cloud drive and do not move the files.',
        keywords: 'folder, organize, move, group',
      },
      videoNotPlaying: {
        question: 'Why isn’t a video playing?',
        answer:
          'Confirm the download completed and the local file still exists, then play it from the Player tab or Downloads. Playback can fail if the file is missing, the format/codec is unsupported on this device, or the player hits a device error. Try Open with or Share with another app only if you have a compatible player installed.',
        keywords: 'play, broken, black screen, error, player',
      },
      unsupportedCodec: {
        question: 'What if the codec is unsupported?',
        answer:
          'VidoraX plays formats your device can decode. Some containers or codecs (or combinations) may download but still fail in the built-in player. That is a device capability limit — VidoraX does not claim every downloaded file will play everywhere. You can try Open/Share with another app that supports that codec.',
        keywords: 'codec, format, unsupported media, decode',
      },
      resumePlayback: {
        question: 'Does playback resume where I left off?',
        answer:
          'Yes for eligible unfinished watches. When you reopen media in the VidoraX player, playback can seek to your saved position automatically if a resume record exists on this device. Very short watches or cleared history may start from the beginning.',
        keywords: 'resume, continue, position, watch history',
      },
      fullscreenOrientation: {
        question: 'How do fullscreen and orientation work?',
        answer:
          'Use the fullscreen control in the player to enter or exit fullscreen. Orientation follows the player’s fullscreen lifecycle on supported devices. Locking rotation in system settings can limit automatic orientation changes.',
        keywords: 'fullscreen, landscape, portrait, rotate',
      },
      loginAccount: {
        question: 'Do I need an account?',
        answer:
          'No. VidoraX does not use a login, password, or cloud account. Downloads, folders, favorites, history, bookmarks, playback progress, and settings stay on this device. You can use the app after install without signing in.',
        keywords: 'login, sign in, account, profile, password',
      },
      languageSettings: {
        question: 'How do I change the language?',
        answer:
          'Open Settings → Language and choose English or اردو (Urdu). The app updates labels, help content, and RTL layout for Urdu without requiring a reinstall. Technical terms like VidoraX, file extensions, and codec names stay as-is where appropriate.',
        keywords: 'language, english, urdu, اردو, locale',
      },
      themeSettings: {
        question: 'How do I change the theme?',
        answer:
          'Open Settings → Appearance → Theme and pick System, Red, or Dark. Red, VidoraX’s own colours, is the default; System is a plain light look and Dark is dark. The theme applies across the whole app, including Help & Support.',
        keywords: 'theme, red, dark, light, appearance, system',
      },
      storageSettings: {
        question: 'How do I manage storage?',
        answer:
          'Downloaded videos use storage inside the VidoraX app. Settings → Storage → Manage Storage shows how much space VidoraX uses; Clear Cache there removes temporary files only. To free space, long-press videos you no longer need in the Player tab and choose Delete from VidoraX. Uninstalling the app removes VidoraX’s own files; copies saved to your Gallery stay on the phone.',
        keywords: 'storage, space, disk, delete, manage',
      },
    },
  },
  legal: {
    effectiveLabel: 'Effective date: {date}',
    updatedLabel: 'Last updated: {date}',
    listBullet: '•',
    footer: {
      contactTitle: 'Contact',
      contactDescription: 'Email {email}',
      contactA11y: 'Opens your email app to contact VidoraX',
      webTitle: 'View on the web',
      webDescription: 'Open the published web version',
      webA11y: 'Opens the published web legal page',
      supportTitle: 'Help & Support',
      supportDescription: 'Help center, privacy questions, and deletion information',
      supportA11y: 'Opens Help and Support',
    },
  },
  privacy: {
    title: 'Privacy Policy',
    a11y: 'Privacy Policy',
    sections: {
      introduction: {
        heading: '1. Introduction',
        p1: 'This Privacy Policy explains how VidoraX processes information when you use the VidoraX mobile application. VidoraX does not offer a user account, login, or password.',
        p2: 'VidoraX is a browser, media, and download manager. Downloads, folders, favorites, history, bookmarks, playback progress, and settings are stored on this device. VidoraX does not sync that data to a VidoraX cloud account in normal use. Third-party websites you visit still receive ordinary browsing and network requests.',
      },
      informationProcessed: {
        heading: '2. Information processed',
        intro:
          'Depending on how you use VidoraX, we may process the following categories of information:',
        itemAccount:
          'VidoraX does not collect a user account, email, display name, or password. There is no VidoraX login identity.',
        itemAuth:
          'VidoraX does not keep access tokens, refresh tokens, or a signed-in session for a VidoraX account.',
        itemDownloadMeta:
          'Download and media metadata — titles, source URLs, platform labels, thumbnail URLs, file names, sizes, quality or resolution details, status, progress, and related download records when you analyze or save media. This metadata is stored on your device.',
        itemLocalMedia:
          'Local downloaded files and cache — media files saved in VidoraX app storage on your device, plus local transfer/progress state used to manage downloads. Physical media files stay on your device.',
        itemBrowser:
          'Browser-related information — page URLs, titles, hostnames, visit times, bookmarks, recent searches, and recent URLs retained in local browser history on this device. An in-app browser session may also restore the last page you were viewing on this device.',
        itemPlayback:
          'Playback, history, and resume state — watch position, duration, progress, completion flags, and related continue-watching records stored locally on this device. Resume does not require a VidoraX account.',
        itemDiagnostics:
          'Diagnostics — VidoraX does not currently integrate a third-party analytics or crash-reporting SDK in the app. Development builds may log limited diagnostic messages on-device for troubleshooting; production use does not rely on a separate analytics product described here.',
        itemSettings:
          'Preferences and settings — language, theme, and download-related preferences stored on this device. They are not synced to a VidoraX cloud account.',
      },
      howUsed: {
        heading: '3. How information is used',
        intro: 'We use processed information to:',
        itemProvide:
          'Provide core product features — browsing, downloading supported media you request, local playback, and library organization on this device.',
        itemSync:
          'Keep downloads, folders, favorites, history, bookmarks, playback progress, and settings available locally after you close and reopen the app.',
        itemSecurity:
          'Operate download, playback, and storage features reliably on this device. VidoraX does not use a login session or password to identify you.',
        itemImprove:
          'Understand and fix product issues using information already needed to run the app. VidoraX does not currently operate a separate advertising or third-party analytics program in the app.',
      },
      backend: {
        heading: '4. Network communication',
        p1: 'VidoraX does not require a VidoraX account, and it does not perform normal cloud sync of downloads, folders, favorites, history, bookmarks, playback, or settings. Those records stay on this device. VidoraX does not require its own API server for normal use.',
        p2: 'When you browse a website, analyze a media link, or download a file, VidoraX sends ordinary network requests to that third-party source. Source URLs and related media metadata may be sent to the sites you choose to open. Playback progress is stored locally and is not uploaded to a VidoraX account.',
        p3: 'Downloaded media files themselves remain on your device unless you choose to share or move them through your own device tools. If you contact support by email, the content of that message is sent only because you chose to send it.',
      },
      thirdParties: {
        heading: '5. Third-party and service-provider processing',
        p1: 'When you browse websites or open in-app search that loads a third-party page, those third parties process information under their own policies. VidoraX does not control third-party websites you visit.',
        p2: 'Network requests needed to load pages, thumbnails, or media you choose still go to those third-party sources. This policy does not claim that browsing is hidden from the sites you visit.',
        p3: 'The app may use on-device system notifications (for example, download-related alerts). VidoraX does not currently embed advertising networks or third-party analytics SDKs in the mobile app as described in this policy.',
      },
      localStorage: {
        heading: '6. Local device storage',
        p1: 'On your device, VidoraX may store browser history and bookmarks databases, playback resume records, download engine state, preferences, and downloaded media files in app document storage.',
        p2: 'Clearing history, removing downloads, or uninstalling the app affects local data as those actions are designed. Uninstalling removes local app data on the device. VidoraX does not keep a separate cloud copy of that local library for a user account.',
      },
      retention: {
        heading: '7. Data retention',
        p1: 'We do not publish a single fixed retention period for all data categories. Local information is generally kept until you clear it, remove related items, or uninstall the app.',
        p2: 'If you email support, that message is retained by the mailbox provider according to that channel’s practices. Exact backup schedules are not promised in this policy.',
      },
      security: {
        heading: '8. Security safeguards',
        p1: 'VidoraX applies reasonable technical and organizational measures appropriate to the nature of a local, on-device app, including app-sandbox storage for downloads and preferences.',
        p2: 'No method of storage eliminates all risk. We do not claim that information cannot be accessed, disclosed, altered, or destroyed in an unauthorized way.',
      },
      userControls: {
        heading: '9. User controls and rights',
        intro:
          'Depending on your device, VidoraX provides in-app controls such as:',
        itemHistory: 'Clearing browser history stored on this device.',
        itemBookmarks: 'Managing or clearing bookmarks stored on this device.',
        itemDownloads: 'Deleting downloads and their local files.',
        itemLanguage:
          'Changing language and other preferences in Settings.',
      },
      accountDeletion: {
        heading: '10. No VidoraX account',
        p1: 'VidoraX does not create a user account, login, or password. There is no cloud profile to delete.',
        p2: 'To remove local VidoraX data from this device, clear history or downloads in the app, or uninstall VidoraX. Uninstalling removes local app data on the device.',
      },
      children: {
        heading: '11. Children’s privacy',
        p1: 'VidoraX is not designed specifically for children and is not marketed as a child-directed product in the app configuration covered by this policy.',
        p2: 'Applicable age restrictions, parental controls, and local laws may still apply to how the app is used.',
      },
      updates: {
        heading: '12. Policy updates',
        p1: 'We may update this Privacy Policy as VidoraX changes. The effective and last-updated dates appear at the top of this document. Continued use of VidoraX after an update means you should review the revised policy. Material changes may also be communicated in-app or on the VidoraX website when practical.',
      },
      contact: {
        heading: '13. Contact',
        p1: 'A dedicated privacy contact email is not configured in this app build. For privacy questions, check {website} for any published contact details related to VidoraX.',
        p2: 'Public web versions of this policy are intended to be available at {privacyUrl} when published.',
      },
    },
  },
  terms: {
    title: 'Terms & Conditions',
    a11y: 'Terms and Conditions',
    sections: {
      acceptance: {
        heading: '1. Acceptance',
        p1: 'These Terms & Conditions govern your use of the VidoraX mobile application. By using VidoraX, you agree to these Terms. VidoraX does not require you to create an account, sign in, or set a password.',
        p2: 'If you do not agree, do not use VidoraX.',
      },
      permittedUse: {
        heading: '2. Permitted lawful use',
        p1: 'You may use VidoraX to browse the web, manage supported downloads, organize library items, and play supported media in accordance with these Terms and applicable law.',
        p2: 'You may only download, save, or play content that you are legally allowed to access and keep. VidoraX does not grant you rights to third-party content.',
      },
      contentOwnership: {
        heading: '3. Content ownership and copyright',
        p1: 'VidoraX, including its name, branding, and app software, is owned by its rights holders. These Terms do not transfer ownership of VidoraX to you.',
        p2: 'Third-party websites, videos, images, and other media remain the property of their respective owners. You are responsible for respecting copyright and other intellectual-property rights.',
      },
      userAuthorization: {
        heading: '4. User authorization responsibility',
        p1: 'You are solely responsible for the URLs you open, the links you paste, and the media you choose to analyze, download, store, or play.',
        p2: 'You represent that you have any permission required to access and save the content you process with VidoraX.',
      },
      supportedSources: {
        heading: '5. Supported and unsupported sources',
        p1: 'Not every website or media stream can be downloaded or played. Availability depends on the source, technical format, network conditions, and product capabilities.',
        p2: 'VidoraX may refuse, fail, or partially support a request when a source is unsupported, unstable, or incompatible. Lack of support is not a license to obtain the same content by other unlawful means.',
      },
      drmLimitations: {
        heading: '6. DRM, encrypted, and protected media',
        p1: 'VidoraX does not support DRM-protected, encrypted, or similarly protected media that the product cannot lawfully and technically process.',
        p2: 'You must not use VidoraX to attempt to bypass DRM, encryption, access controls, or other technical protection measures.',
        p3: 'If VidoraX reports that media is DRM-protected, encrypted, or unsupported, treat that as a hard limitation — not a prompt to circumvent protections.',
      },
      userResponsibilities: {
        heading: '7. User responsibilities',
        intro: 'You agree to:',
        itemCredentials: 'Use VidoraX without expecting a VidoraX login, password, or cloud account identity.',
        itemLawful: 'Use VidoraX only for lawful purposes and only with content you are authorized to handle.',
        itemDevice: 'Maintain your own device storage, backups, and network access needed to use the app.',
        itemAccuracy: 'Review download and playback results carefully; technical analysis can be imperfect.',
      },
      prohibitedMisuse: {
        heading: '8. Prohibited misuse',
        intro: 'You must not:',
        itemCircumvent:
          'Attempt to circumvent DRM, encryption, paywalls, authentication gates, or other security or copyright protection measures.',
        itemAbuse:
          'Abuse VidoraX services, including by overloading, scraping in a harmful way, or automating use in a manner that disrupts the service.',
        itemInterfere:
          'Interfere with app integrity, reverse-engineer protected components in violation of law, or attempt unauthorized access to VidoraX systems.',
        itemUnlawful:
          'Use VidoraX to store, distribute, or access content unlawfully, or to harass, exploit, or harm others.',
      },
      serviceAvailability: {
        heading: '9. Service availability',
        p1: 'VidoraX features may change, be interrupted, or become temporarily unavailable due to maintenance, network issues, device limits, or service decisions.',
        p2: 'We do not guarantee uninterrupted, error-free, or permanent availability of any feature.',
      },
      accountsSecurity: {
        heading: '10. Device security',
        p1: 'You are responsible for physical and lock-screen access to the device where VidoraX is installed. VidoraX does not provide a login or password for a VidoraX account.',
        p2: 'Protecting the device (passcode, biometrics, OS updates) is the primary way to limit who can open your local downloads, history, and settings.',
      },
      localFiles: {
        heading: '11. Local files and storage',
        p1: 'Downloaded media and related local data occupy space on your device. You are responsible for managing storage, deleting files you no longer need, and understanding that uninstalling the app removes local app data.',
        p2: 'VidoraX is not a guaranteed backup service for your media library. Keep your own copies of anything important.',
      },
      deviceLimitations: {
        heading: '12. Device, codec, and network limitations',
        p1: 'Playback and download success depend on your device capabilities, supported codecs, available storage, OS permissions, and network quality.',
        p2: 'Unsupported codecs or formats may fail to play even when a file was saved. Network interruptions can delay or fail transfers.',
      },
      limitationOfService: {
        heading: '13. Limitation of service',
        p1: 'VidoraX is provided on an “as available” basis for personal use as a browser, media, and download manager. To the fullest extent permitted by law, VidoraX and its operators are not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data, media files, profits, or goodwill arising from your use of the app.',
        p2: 'Nothing in these Terms excludes liability that cannot be excluded under applicable law.',
      },
      suspension: {
        heading: '14. Suspension and termination',
        p1: 'We may suspend or stop providing VidoraX features for serious violations of these Terms, unlawful use, security risk, or abuse of the product.',
        p2: 'You may stop using VidoraX at any time and may uninstall the app. Uninstalling removes local app data on the device. There is no VidoraX account to close.',
      },
      updates: {
        heading: '15. Updates to these Terms',
        p1: 'We may update these Terms as the product evolves. The effective and last-updated dates appear at the top of this document. Continued use after an update constitutes acceptance of the revised Terms where permitted by law.',
      },
      contact: {
        heading: '16. Contact',
        p1: 'A dedicated support contact email is not configured in this app build. For questions about these Terms, check {website} for any published contact details related to VidoraX.',
        p2: 'Public web versions of these Terms are intended to be available at {termsUrl} when published.',
      },
    },
  },
  appLock: {
    enterPin: 'Enter PIN',
    enterPinA11y: 'Enter your 4-digit App Lock PIN',
    unlock: 'Unlock',
    incorrectPin: 'Incorrect PIN',
    unlockError: 'Could not verify PIN. Try again.',
    setPinTitle: 'Set App Lock PIN',
    setPinHint: 'Choose a 4-digit PIN to protect VidoraX on this device.',
    setPinA11y: 'Enter a new 4-digit PIN',
    confirmPinHint: 'Enter the same 4-digit PIN again to confirm.',
    confirmPinA11y: 'Confirm your 4-digit PIN',
    pinsDoNotMatch: 'PINs do not match',
    pinInvalid: 'Enter a valid 4-digit PIN',
    recoveryTitle: 'Recovery Code',
    recoveryHint:
      'Save this recovery code somewhere safe. You may need it later if you forget your PIN.',
    recoveryCodeA11y: 'Your App Lock recovery code',
    copyRecoveryCode: 'Copy recovery code',
    savedRecoveryConfirm: "I've saved my recovery code",
    mustConfirmSaved: 'Confirm that you have saved your recovery code',
    dataLossWarningTitle: 'IMPORTANT',
    dataLossWarningBody:
      'Keep your PIN and recovery code safe. If you forget BOTH your PIN and your recovery code, your protected local app data cannot be recovered.',
    dataLossWarningReinstall:
      'You would need to uninstall VidoraX and install it again, which removes the app’s local data.',
    dataLossWarningCompact:
      'Keep your PIN and recovery code safe. If you forget both, your protected local data can’t be recovered — only reinstalling VidoraX (which removes its local data) resets App Lock.',
    dataLossAcknowledge:
      'I understand that losing both my PIN and recovery code may cause loss of my local app data.',
    mustAcknowledgeDataLoss: 'Confirm that you understand the warning above',
    enableAppLock: 'Enable App Lock',
    setupError: 'Could not enable App Lock. Try again.',
    cancelSetupTitle: 'Cancel setup?',
    cancelSetupMessage: 'App Lock will remain off.',
    disableTitle: 'Disable App Lock',
    disableHint: 'Enter your current PIN to disable App Lock.',
    disablePinA11y: 'Enter your current App Lock PIN to disable',
    disableConfirmTitle: 'Disable App Lock?',
    disableConfirmMessage:
      'VidoraX will no longer require a PIN when you return to the app.',
    disableConfirmAction: 'Disable',
    disableError: 'Could not disable App Lock. Try again.',
    integrityTitle: 'App Lock unavailable',
    integrityMessage:
      'App Lock data on this device looks incomplete or damaged. Private content stays locked. Try again, or reinstall if this continues.',
    secureStoreError:
      'Secure storage could not be read. Private content stays locked. Try again.',
    changePinTitle: 'Change PIN',
    enterCurrentPinHint: 'Enter your current 4-digit PIN.',
    enterCurrentPinA11y: 'Enter your current App Lock PIN',
    setNewPinHint: 'Choose a new 4-digit PIN.',
    setNewPinA11y: 'Enter a new 4-digit PIN',
    confirmNewPinHint: 'Enter the new PIN again to confirm.',
    confirmNewPinA11y: 'Confirm your new 4-digit PIN',
    pinChangedTitle: 'PIN updated',
    pinChangedMessage: 'Your App Lock PIN was changed. Your recovery code is unchanged.',
    forgotPin: 'Forgot PIN?',
    forgotPinTitle: 'Forgot PIN',
    enterRecoveryCodeHint:
      'Enter your recovery code to set a new PIN. This does not unlock VidoraX by itself.',
    enterRecoveryCodeA11y: 'Enter your App Lock recovery code',
    recoveryCodePlaceholder: 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XX',
    verifyRecoveryCode: 'Continue',
    incorrectRecoveryCode: 'Incorrect Recovery Code',
    lostBothWarning:
      'If you no longer have your PIN or Recovery Code, VidoraX cannot unlock the app.',
    updateError: 'Unable to update App Lock. Try again.',
    tooManyAttempts: 'Too many attempts.',
    tryAgainShortly: 'Try again shortly.',
    tryAgainInSeconds: 'Try again in {seconds}s.',
    generateRecoveryTitle: 'New Recovery Code',
    generateRecoveryPinHint: 'Enter your current PIN to generate a new recovery code.',
    generateRecoveryHint:
      'Save this new recovery code somewhere safe. Your previous recovery code will stop working after you confirm.',
    previousRecoveryWillStop:
      'Your previous Recovery Code will stop working after you save this one.',
    savedNewRecoveryConfirm: "I've saved my new recovery code",
    saveNewRecovery: 'Save new recovery code',
  },
  shell: shellEn,
  detection: detectionEn,
  videoPlayer: videoPlayerEn,
} as const;
