import { detectionUr } from './catalogs/detection.ur';
import { shellUr } from './catalogs/shell.ur';
import { videoPlayerUr } from './catalogs/videoPlayer.ur';
import type { CatalogStrings } from './types';
import type { en } from './en';

export const ur: CatalogStrings<typeof en> = {
  common: {
    ok: 'ٹھیک ہے',
    cancel: 'منسوخ',
    close: 'بند کریں',
    retry: 'دوبارہ کوشش کریں',
    save: 'محفوظ کریں',
    saved: 'محفوظ ہو گیا',
    delete: 'حذف کریں',
    remove: 'ہٹائیں',
    rename: 'نام تبدیل کریں',
    share: 'شیئر',
    open: 'کھولیں',
    play: 'چلائیں',
    pause: 'توقف',
    resume: 'جاری رکھیں',
    back: 'واپس',
    goBack: 'واپس جائیں',
    next: 'اگلا',
    continue: 'جاری رکھیں',
    skip: 'چھوڑیں',
    done: 'مکمل',
    loading: 'لوڈ ہو رہا ہے',
    search: 'تلاش',
    reset: 'ری سیٹ',
    dismiss: 'بند کریں',
    comingSoon: 'جلد آ رہا ہے',
    on: 'آن',
    off: 'آف',
    default: 'ڈیفالٹ',
    selected: 'منتخب',
    version: 'ورژن {version}',
    brand: 'VidoraX',
    or: 'یا',
    create: 'بنائیں',
    yes: 'ہاں',
    no: 'نہیں',
    clearInput: 'ان پٹ صاف کریں',
    closeModal: 'موڈل بند کریں',
    loadingPlaceholder: 'لوڈ ہو رہا ہے',
    refreshProfile: 'پروفائل ریفریش کریں',
    refreshA11y: 'ریفریش',
    dismissDiscoveryA11y: 'میڈیا دریافت بند کریں',
    dismissDiscoveryHint: 'نئے صفحے تک دریافت شدہ میڈیا چھپاتا ہے',
    logoA11y: 'VidoraX لوگو',
    loadingScreenA11y: 'VidoraX لوڈنگ اسکرین',
  },
  nav: {
    home: 'ہوم',
    homeTab: 'ہوم ٹیب',
    browser: 'براؤزر',
    browserTab: 'براؤزر ٹیب',
    downloads: 'ڈاؤن لوڈز',
    downloadsTab: 'ڈاؤن لوڈز ٹیب',
    library: 'پلیئر',
    libraryTab: 'پلیئر ٹیب',
    settings: 'سیٹنگز',
    settingsTab: 'سیٹنگز ٹیب',
    about: 'تعارف',
    support: 'مدد',
    reportProblem: 'مسئلہ رپورٹ کریں',
    privacy: 'پرائیویسی',
    terms: 'شرائط',
    history: 'ہسٹری',
    watchHistory: 'واچ ہسٹری',
    bookmarks: 'بک مارکس',
    favorites: 'فیوریٹس',
    downloadSettings: 'ڈاؤن لوڈ سیٹنگز',
    appLockSetup: 'ایپ لاک سیٹ کریں',
    appLockDisable: 'ایپ لاک بند کریں',
    appLockChangePin: 'PIN تبدیل کریں',
    appLockRotateRecovery: 'نیا ریکوری کوڈ',
    downloadDetails: 'ڈاؤن لوڈ کی تفصیل',
    storage: 'اسٹوریج',
  },
  storage: {
    title: 'اسٹوریج',
    subtitle: 'اس ڈivice پر VidoraX فائلوں کے مقامات اور گنجائش',
    loading: 'اسٹوریج کا حساب لگایا جا رہا ہے…',
    loadFailed: 'اس وقت اسٹوریج کی تفصیلات نہیں مل سکیں۔',
    refresh: 'ریفریش',
    refreshA11y: 'اسٹوریج کی تفصیلات ریفریش کریں',
    unavailable: 'دستیاب نہیں',
    zeroBytes: '0 B',
    estimatedNote: 'کچھ اقدار ایپ کے فولڈرز سے تخمینہ کی گئی ہیں۔',
    partialScan: 'کچھ فولڈرز مکمل طور پر اسکین نہیں ہو سکے۔',
    deviceOverview: 'ڈivice اسٹوریج',
    storageUsed: 'استعمال شدہ اسٹوریج',
    deviceUsageA11y: 'ڈivice اسٹوریج {percent} فیصد استعمال',
    deviceUnavailable: 'اس ڈivice پر اسٹوریج کی تفصیلات دستیاب نہیں۔',
    total: 'کل',
    used: 'استعمال شدہ',
    free: 'دستیاب',
    appUsage: 'VidoraX اسٹوریج',
    appUsageSection: 'VidoraX کا استعمال',
    locationsSection: 'ڈاؤن لوڈ مقامات',
    locationsSubtitle: 'VidoraX اس ڈivice پر فائلیں کہاں محفوظ کرتا ہے',
    actionsSection: 'اسٹوریج ایکشنز',
    videos: 'ویڈیوز',
    images: 'تصاویر / تھمب نیلز',
    cache: 'کیش',
    temp: 'عارضی فائلیں',
    other: 'دیگر ایپ ڈیٹا',
    userVisible: 'ڈivice پر صارف کو نظر آنے والا',
    appPrivate: 'VidoraX کی نجی ایپ اسٹوریج',
    createdWhenNeeded: 'پہلی ضرورت پر خود بخود بنایا جائے گا',
    openDownloads: 'ڈاؤن لوڈز کھولیں',
    openLibrary: 'لائبریری کھولیں',
    clearCache: 'کیش صاف کریں',
    clearCacheTitle: 'کیش صاف کریں؟',
    clearCacheMessage:
      'یہ صرف عارضی کیش فائلیں ہٹاتا ہے۔ مکمل ڈاؤن لوڈز اور میڈیا لائبریری محفوظ رہتی ہے۔',
    clearCacheConfirm: 'کیش صاف کریں',
    locations: {
      downloadedVideos: 'ڈاؤن لوڈ شدہ ویڈیوز',
      downloadedVideosDescription:
        'VidoraX کی مکمل میڈیا فائلیں ایپ کی دستاویزات اسٹوریج میں محفوظ ہوتی ہیں۔',
      thumbnails: 'تھمب نیلز اور کیش تصاویر',
      thumbnailsDescription:
        'ویب تھمب نیلز اور تصویر پیش نظارہ مقامی کیش میں محفوظ ہوتے ہیں، علیحدہ ڈاؤن لوڈز نہیں۔',
      temporaryFiles: 'عارضی HLS فائلیں',
      temporaryFilesDescription:
        'اسٹریم ڈاؤن لوڈ کے دوران HLS سیگمنٹ ورک اسپیس۔',
      temporaryDownloadParts: 'عارضی ڈاؤن لوڈ حصے',
      temporaryDownloadPartsDescription:
        'پrogresive ڈاؤن لوڈ کے دوران جزوی رینج فائلیں۔',
      appCache: 'ایپ کیش',
      appCacheDescription:
        'عارضی کیش ڈیٹا بشمول تصویر پیش نظارہ۔ مکمل ڈاؤن لوڈز کو متاثر کیے بغیر صاف کیا جا سکتا ہے۔',
      appDocuments: 'ایپ دستاویزات',
      appDocumentsDescription:
        'ترجیحات، پلے بیک اسٹیٹ، اور دیگر VidoraX ڈیٹا اس ڈivice پر۔',
    },
  },
  dates: {
    justNow: 'ابھی',
    minutesAgo: '{count} منٹ پہلے',
    hoursAgo: '{count} گھنٹے پہلے',
    yesterday: 'کل',
    daysAgo: '{count} دن پہلے',
    remainingSeconds: '{count} سیکنڈ باقی',
    remainingMinutes: '{count} منٹ باقی',
    remainingHours: '{count} گھنٹے باقی',
    remainingHoursMinutes: '{hours} گھنٹے {minutes} منٹ باقی',
  },
  plurals: {
    downloadsZero: 'کوئی ڈاؤن لوڈ نہیں',
    downloadsOne: '{count} ڈاؤن لوڈ',
    downloadsOther: '{count} ڈاؤن لوڈز',
    videosZero: 'کوئی ویڈیو نہیں',
    videosOne: '{count} ویڈیو',
    videosOther: '{count} ویڈیوز',
    itemsZero: 'کوئی آئٹم نہیں',
    itemsOne: '{count} آئٹم',
    itemsOther: '{count} آئٹمز',
    simultaneousDownloadsOne: '{count} بیک وقت ڈاؤن لوڈ',
    simultaneousDownloadsOther: '{count} بیک وقت ڈاؤن لوڈز',
  },
  errors: {
    unexpectedTitle: 'کچھ غلط ہو گیا',
    unexpected: 'کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔',
    retry: 'دوبارہ کوشش کریں',
    networkTitle: 'کنکشن کا مسئلہ',
    network:
      'ویب سائٹ یا میڈیا ماخذ تک رسائی نہیں ہو سکی۔ اپنا انٹرنیٹ چیک کریں اور دوبارہ کوشش کریں۔',
    timeout: 'کنکشن ٹائم آؤٹ ہو گیا۔ دوبارہ کوشش کریں۔',
    serverTitle: 'ماخذ دستیاب نہیں',
    server: 'ویب سائٹ یا میڈیا ماخذ میں عارضی مسئلہ ہے۔ تھوڑی دیر بعد کوشش کریں۔',
    unauthorizedTitle: 'رسائی مسترد',
    unauthorized: 'میڈیا ماخذ نے یہ درخواست مسترد کر دی۔',
    forbiddenTitle: 'اجازت نہیں',
    forbidden: 'آپ کو یہ کام کرنے کی اجازت نہیں۔',
    notFoundTitle: 'نہیں ملا',
    notFound: 'یہ آئٹم نہیں ملا۔',
    validationTitle: 'غلط درخواست',
    validation: 'اپنی معلومات چیک کریں اور دوبارہ کوشش کریں۔',
    offline: 'آپ آف لائن لگتے ہیں۔ کچھ کام دستیاب نہیں ہو سکتے۔',
    storage: 'ڈیوائس اسٹوریج اب استعمال نہیں ہو سکی۔',
    fileNotFound: 'یہ فائل اب اس ڈیوائس پر دستیاب نہیں۔',
    unsupportedMedia: 'اس ویڈیو کا فارمیٹ اس ڈیوائس پر نہیں چل سکتا۔',
    downloadFailed: 'یہ ڈاؤن لوڈ مکمل نہیں ہو سکا۔',
    authRequired: 'میڈیا ماخذ کو اس کی اپنی ویب سائٹ یا ایپ میں تصدیق درکار ہے۔',
    renameFailed: 'نام تبدیل نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    deleteFailed: 'حذف نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    shareFailed: 'فائل شیئر نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    openFailed: 'فائل نہیں کھل سکی۔',
    unknown: 'غیر متوقع مسئلہ پیش آیا۔ دوبارہ کوشش کریں۔',
    codes: {
      NETWORK_ERROR: 'ڈاؤن لوڈ کے دوران نیٹ ورک منقطع ہو گیا۔',
      NETWORK_TIMEOUT: 'کنکشن ٹائم آؤٹ ہو گیا۔',
      RATE_LIMITED: 'میڈیا ماخذ عارضی طور پر مصروف ہے۔ تھوڑی دیر بعد کوشش کریں۔',
      HTTP_ERROR: 'ڈاؤن لوڈ سورس تک رسائی نہیں ہو سکی۔',
      FILE_SYSTEM_ERROR: 'فائل محفوظ نہیں ہو سکی۔',
      FILE_WRITE_FAILED: 'فائل محفوظ نہیں ہو سکی۔',
      FILE_APPEND_FAILED: 'فائل محفوظ کرنا جاری نہیں رہ سکا۔',
      FILE_FINALIZE_FAILED: 'ڈاؤن لوڈ شدہ فائل مکمل نہیں ہو سکی۔',
      INSUFFICIENT_STORAGE: 'ڈاؤن لوڈ مکمل کرنے کے لیے اسٹوریج کافی نہیں۔',
      INVALID_DESTINATION: 'فائل اسٹوریج میں محفوظ نہیں ہو سکی۔',
      PERMISSION_DENIED: 'ڈاؤن لوڈ محفوظ کرنے کے لیے اسٹوریج کی اجازت درکار ہے۔',
      PARTIAL_FILE_CORRUPT: 'جزوی فائل خراب ہے، جاری نہیں رکھا جا سکتا۔',
      FINAL_FILE_INVALID: 'ڈاؤن لوڈ شدہ فائل کی تصدیق ناکام رہی۔',
      CANCELLED: 'ڈاؤن لوڈ منسوخ ہو گیا۔',
      INVALID_RESOURCE: 'اس میڈیا کو ڈاؤن لوڈ نہیں کیا جا سکتا۔',
      TRANSFER_INTERRUPTED: 'ڈاؤن لوڈ رک گیا۔',
      PAUSE_FAILED: 'ڈاؤن لوڈ روکا نہیں جا سکا۔ تھوڑی دیر بعد کوشش کریں۔',
      RESUME_FAILED: 'ڈاؤن لوڈ دوبارہ شروع نہیں ہو سکا۔',
      RESUME_UNSUPPORTED:
        'یہ میڈیا ماخذ ادھورے ڈاؤن لوڈ کو دوبارہ شروع کرنے کی سہولت نہیں دیتا۔',
      RESUME_STATE_MISSING: 'ڈاؤن لوڈ دوبارہ شروع نہیں ہو سکا۔',
      RESUME_STATE_CONFLICT: 'ڈاؤن لوڈ دوبارہ شروع نہیں ہو سکا۔',
      QUEUE_ADMISSION_FAILED: 'ڈاؤن لوڈ دوبارہ شروع نہیں ہو سکا۔',
      PARTIAL_FILE_MISSING: 'جزوی فائل اب دستیاب نہیں۔',
      RANGE_REJECTED:
        'میڈیا ماخذ نے وہاں سے جاری رکھنے سے انکار کیا جہاں ڈاؤن لوڈ رکا تھا۔',
      INVALID_RANGE_RESPONSE: 'میڈیا ماخذ نے غلط جواب دیا۔',
      SOURCE_CHANGED: 'سورس فائل بدل گئی ہے، محفوظ طریقے سے جاری نہیں رکھا جا سکتا۔',
      RETRY_EXHAUSTED: 'کئی کوششوں کے بعد بھی ڈاؤن لوڈ ناکام رہا۔',
      MERGE_FAILED: 'ڈاؤن لوڈ شدہ فائل جوڑی نہیں جا سکی۔',
      PART_SIZE_MISMATCH: 'ڈاؤن لوڈ کے ایک حصے کی تصدیق ناکام رہی۔',
      FINAL_SIZE_MISMATCH: 'فائل کا سائز سورس سے میل نہیں کھاتا۔',
      CANCEL_FAILED: 'ڈاؤن لوڈ منسوخ نہیں ہو سکا۔',
      WORKER_NOT_FOUND: 'ڈاؤن لوڈ روکا نہیں جا سکا۔ تھوڑی دیر بعد کوشش کریں۔',
      AUTH_ERROR: 'ڈاؤن لوڈ جاری رکھنے کے لیے میڈیا ماخذ کی تصدیق درکار ہے۔',
      AUTH_REQUIRED: 'میڈیا ماخذ کو اس کی اپنی ویب سائٹ یا ایپ میں تصدیق درکار ہے۔',
      SESSION_CONTEXT_LOST:
        'اس تصدیق شدہ ڈاؤن لوڈ کے لیے فعال ویب سائٹ سیشن درکار ہے۔ ویب سائٹ کھولیں اور دوبارہ کوشش کریں۔',
      SESSION_CHANGED: 'آپ کا ویب سائٹ اکاؤنٹ بدل گیا۔ ویب سائٹ کھولیں اور دوبارہ کوشش کریں۔',
      SESSION_EXPIRED: 'آپ کا ویب سائٹ سیشن ختم ہو گیا۔ ویب سائٹ کھولیں اور دوبارہ کوشش کریں۔',
      AUTH_CONTEXT_UNAVAILABLE: 'دستیاب سیشن کے ساتھ یہ محفوظ میڈیا ڈاؤن لوڈ نہیں ہو سکتا۔',
      HLS_UNSUPPORTED: 'اس سٹریم کا فارمیٹ اس ڈیوائس پر ڈاؤن لوڈ نہیں ہو سکتا۔',
      HLS_ENCRYPTED: 'یہ سٹریم انکرپٹڈ ہے، ڈاؤن لوڈ نہیں ہو سکتا۔',
      UNSUPPORTED_DRM: 'محفوظ میڈیا ڈاؤن لوڈ نہیں ہو سکتا۔',
      UNSUPPORTED_HLS_ENCRYPTION: 'یہ انکرپٹڈ سٹریم ڈاؤن لوڈ نہیں ہو سکتا۔',
      LIVE_HLS_UNSUPPORTED: 'لائیو سٹریم ڈاؤن لوڈ نہیں ہو سکتے۔',
      UNSUPPORTED_HLS_BYTERANGE: 'یہ سٹریم ڈاؤن لوڈ نہیں ہو سکتا۔',
      INVALID_HLS_PLAYLIST: 'اس سٹریم کی فہرست پڑھی نہیں جا سکی۔',
      UNKNOWN_ERROR: 'کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔',
      FILE_NOT_FOUND: 'یہ فائل اب اس ڈیوائس پر دستیاب نہیں۔',
      UNSUPPORTED_MEDIA: 'اس ویڈیو کا فارمیٹ اس ڈیوائس پر نہیں چل سکتا۔',
      DOWNLOAD_FAILED: 'یہ ڈاؤن لوڈ مکمل نہیں ہو سکا۔',
      RENAME_FAILED: 'نام تبدیل نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
      STORAGE_ERROR: 'ڈیوائس اسٹوریج اب استعمال نہیں ہو سکی۔',
      NOT_FOUND: 'یہ آئٹم نہیں ملا۔',
      VALIDATION_ERROR: 'اپنی معلومات چیک کریں اور دوبارہ کوشش کریں۔',
      SERVER_ERROR: 'ویب سائٹ یا میڈیا ماخذ میں عارضی مسئلہ ہے۔ تھوڑی دیر بعد کوشش کریں۔',
      UNAUTHORIZED: 'میڈیا ماخذ نے یہ درخواست مسترد کر دی۔',
      FORBIDDEN: 'آپ کو یہ کام کرنے کی اجازت نہیں۔',
      TIMEOUT: 'کنکشن ٹائم آؤٹ ہو گیا۔ دوبارہ کوشش کریں۔',
    },
  },
  emptyStates: {
    retry: 'دوبارہ کوشش کریں',
    genericTitle: 'ابھی کچھ نہیں',
    genericDescription: 'جب کچھ دکھانے کو ہو گا، وہ یہاں نظر آئے گا۔',
  },
  dialogs: {
    confirm: 'تصدیق',
    cancel: 'منسوخ',
    close: 'بند کریں',
  },
  files: {
    actionsTitle: 'فائل کے اختیارات',
    actionsSubtitle: 'نام تبدیل کریں، حذف کریں، کھولیں یا شیئر کریں',
    rename: 'نام تبدیل کریں',
    renameFile: 'فائل کا نام تبدیل کریں',
    renameFolder: 'فولڈر کا نام تبدیل کریں',
    delete: 'حذف کریں',
    deleteFile: 'فائل حذف کریں',
    open: 'کھولیں',
    share: 'شیئر',
    play: 'چلائیں',
    emptyName: 'نیا نام خالی نہیں ہو سکتا۔',
    emptyFolderName: 'فولڈر کا نام خالی نہیں ہو سکتا۔',
    unavailable: 'ڈاؤن لوڈ شدہ فائل نہیں مل سکی۔',
    unreadable: 'VidoraX یہ ڈاؤن لوڈ شدہ فائل نہیں کھول سکا۔',
    noCompatibleApp: 'کوئی مطابقت رکھنے والی ویڈیو ایپ نصب نہیں۔',
    shareFailed: 'یہ ویڈیو شیئر نہیں ہو سکی۔',
    openFailed: 'VidoraX یہ ڈاؤن لوڈ شدہ فائل نہیں کھول سکا۔',
    uriFailed: 'شیئر کے لیے فائل تیار نہیں ہو سکی۔',
    notCompleted: 'یہ ڈاؤن لوڈ ابھی مکمل نہیں ہوا۔',
  },
  splash: {
    brandName: 'VidoraX',
    taglineFast: 'تیز',
    taglineReliable: 'قابلِ اعتماد',
    taglineSecure: 'محفوظ',
    loadingA11y: 'لوڈ ہو رہا ہے',
    loadingScreenA11y: 'VidoraX لوڈنگ اسکرین',
  },
  onboarding: {
    skip: 'چھوڑیں',
    skipA11y: 'آن بورڈنگ چھوڑیں',
    continue: 'جاری رکھیں',
    getStarted: 'شروع کریں',
    gatewayTitleLead: 'ڈاؤن لوڈ',
    gatewayTitleAccent: 'معاون میڈیا',
    gatewaySubtitle:
      'اپنی پسندیدہ ویب سائٹس براؤز کریں یا لنک پیسٹ کریں۔\nVidoraX خود بخود ڈاؤن لوڈ کے قابل ویڈیوز پہچانتا ہے۔',
    trustTitleLead: 'تیز۔',
    trustTitleAccent: 'قابلِ اعتماد۔',
    trustTitleTrail: 'کنٹرول ہمیشہ آپ کے پاس۔',
    trustSubtitle:
      'ڈاؤن لوڈز کو آسانی سے روکیں، جاری رکھیں، قطار میں لگائیں اور منظم کریں — VidoraX پسِ منظر میں سب سنبھالتا رہتا ہے۔',
    trustA11y:
      'تیز۔ قابلِ اعتماد۔ کنٹرول ہمیشہ آپ کے پاس۔ VidoraX ہر ڈاؤن لوڈ شروع سے آخر تک سنبھالتا ہے اور آپ کو کنٹرول میں رکھتا ہے۔',
    trustDetected: 'ویڈیو مل گئی',
    trustCardTitle: 'مووی ٹریلر',
    trustCompleted: 'مکمل',
    trustLibrary: 'آف لائن لائبریری',
    trustPause: 'توقف',
    trustResume: 'جاری رکھیں',
    trustQueue: 'قطار',
    trustNotifications: 'اطلاعات',
    trustRetry: 'دوبارہ کوشش',
    trustBackground: 'پسِ منظر',
    libraryTitleLead: 'سب کچھ',
    libraryTitleAccent: 'مرتب۔',
    libraryTitleTrail: 'فوراً دستیاب۔',
    librarySubtitle:
      'ہر ڈاؤن لوڈ کو ایک خوبصورت آف لائن لائبریری سے تلاش کریں، چلائیں اور منظم کریں۔',
    libraryA11y:
      'سب کچھ مرتب۔ فوراً دستیاب۔ آپ کی آف لائن میڈیا لائبریری منظم، قابلِ تلاش اور دیکھنے کے لیے تیار رہتی ہے۔',
    librarySearchPlaceholder: 'ڈاؤن لوڈز تلاش کریں...',
    libraryPlaying: 'آف لائن چل رہا ہے',
    libraryFavorites: 'فیوریٹس',
    libraryHistory: 'ہسٹری',
    librarySearch: 'سمارٹ تلاش',
    libraryPlayer: 'آف لائن پلیئر',
    libraryOrganized: 'مرتب لائبریری',
    librarySettings: 'سیٹنگز',
    libraryMovie: 'مووی ٹریلر',
    libraryTravel: 'ٹریول ولاگ',
    libraryCourse: 'React کورس',
    libraryVacation: 'ویکیشن ریل',
    libraryMetaCompleted: 'مکمل',
    libraryMetaSaved: 'محفوظ',
    libraryMetaOffline: 'آف لائن',
    gatewayA11y:
      'معاون میڈیا ڈاؤن لوڈ کریں۔ VidoraX آپ کے ڈاؤن لوڈ ورک فلو کو ایک تجربے میں جوڑتا ہے۔',
    downloadWorkflowA11y:
      'ڈاؤن لوڈ ورک فلو: لنک پیسٹ کریں، ویڈیو ملی، ڈاؤن لوڈ ہو رہی ہے، آف لائن محفوظ',
    progressA11y: 'ڈاؤن لوڈ پیش رفت',
    libraryHeroA11y:
      'آف لائن میڈیا لائبریری ایک قابلِ تلاش ذاتی ہب میں ترتیب پا رہی ہے',
  },
  auth: {
    signInTitle: 'خوش آمدید',
    signInSubtitle:
      'اپنے محفوظ ڈاؤن لوڈ ورک اسپیس میں واپس آئیں اور ذاتی آف لائن میڈیا لائبریری استعمال کریں۔',
    signInA11y:
      'خوش آمدید۔ اپنے محفوظ VidoraX ڈاؤن لوڈ ورک اسپیس میں سائن ان کریں۔',
    signIn: 'سائن ان',
    signInInstead: 'بجائے سائن ان کریں',
    emailLabel: 'ای میل',
    emailPlaceholder: 'اپنا ای میل درج کریں',
    passwordLabel: 'پاس ورڈ',
    passwordPlaceholder: 'اپنا پاس ورڈ درج کریں',
    rememberMe: 'مجھے یاد رکھیں',
    forgotPassword: 'پاس ورڈ بھول گئے',
    noAccount: 'اکاؤنٹ نہیں ہے؟',
    createAccount: 'اکاؤنٹ بنائیں',
    signUpTitle: 'اپنا اکاؤنٹ بنائیں',
    signUpSubtitle:
      'VidoraX میں شامل ہوں اور محفوظ تجربے کے ساتھ اپنی ذاتی آف لائن میڈیا لائبریری بنانا شروع کریں۔',
    signUpA11y: 'اپنا VidoraX اکاؤنٹ بنائیں اور محفوظ ڈاؤن لوڈ ورک اسپیس کھولیں۔',
    nameLabel: 'پورا نام',
    namePlaceholder: 'اپنا پورا نام درج کریں',
    createPasswordPlaceholder: 'پاس ورڈ بنائیں',
    confirmLabel: 'پاس ورڈ کی تصدیق',
    confirmPlaceholder: 'پاس ورڈ دوبارہ درج کریں',
    hasAccount: 'پہلے سے اکاؤنٹ ہے؟',
    termsPrefix: 'میں ',
    termsLink: 'شرائط و ضوابط',
    termsMiddle: ' اور ',
    privacyLink: 'پرائیویسی پالیسی',
    termsSuffix: ' سے اتفاق کرتا/کرتی ہوں۔',
    termsA11y: 'شرائط اور پرائیویسی پالیسی سے اتفاق',
    duplicateEmail: 'اس ای میل سے اکاؤنٹ پہلے سے موجود ہے۔',
    incorrectCredentials: 'ای میل یا پاس ورڈ غلط ہے۔',
    unableToConnect: 'کنکشن نہیں ہو سکا۔\nاپنا انٹرنیٹ چیک کریں۔',
    requestTimeout: 'درخواست متوقع سے زیادہ دیر لگی۔\nدوبارہ کوشش کریں۔',
    checkDetails: 'تفصیلات چیک کریں اور دوبارہ کوشش کریں۔',
    genericFailure: 'کچھ غلط ہو گیا۔\nتھوڑی دیر بعد دوبارہ کوشش کریں۔',
    forgotTitle: 'پاس ورڈ بھول گئے',
    forgotSubtitle:
      'پاس ورڈ ری سیٹ ابھی دستیاب نہیں۔ آپ بہرحال ای میل درج کر کے یہ مرحلہ دیکھ سکتے ہیں، پھر سائن ان پر واپس آ سکتے ہیں۔',
    sendResetLink: 'ری سیٹ لنک بھیجیں',
    backToLogin: 'سائن ان پر واپس',
    forgotSuccessTitle: 'ابھی دستیاب نہیں',
    forgotSuccessMessage:
      'پاس ورڈ ری سیٹ ابھی دستیاب نہیں۔ موجودہ تفصیلات سے سائن ان کریں یا سپورٹ سے رابطہ کریں۔',
    forgotA11y:
      'پاس ورڈ بھول گئے۔ اپنے VidoraX اکاؤنٹ تک رسائی کے لیے ای میل درج کریں۔',
    forgotSuccessA11y:
      'پاس ورڈ ری سیٹ ابھی دستیاب نہیں۔ جب تیار ہوں تو لاگ ان پر واپس جائیں۔',
    emailValidA11y: 'ای میل درست لگتی ہے',
    nameValidA11y: 'نام درست لگتا ہے',
    validation: {
      emailRequired: 'ای میل درکار ہے',
      emailInvalid: 'درست ای میل ایڈریس درج کریں',
      passwordRequired: 'پاس ورڈ درکار ہے',
      passwordMin: 'پاس ورڈ کم از کم {count} حروف کا ہونا چاہیے',
      passwordUpper: 'کم از کم ایک بڑا حرف شامل کریں',
      passwordLower: 'کم از کم ایک چھوٹا حرف شامل کریں',
      passwordNumber: 'کم از کم ایک عدد شامل کریں',
      passwordSpecial: 'کم از کم ایک خاص حرف شامل کریں',
      nameRequired: 'پورا نام درکار ہے',
      nameMin: 'کم از کم 2 حروف درج کریں',
      nameMax: 'نام 100 حروف سے زیادہ نہیں ہو سکتا',
      confirmRequired: 'پاس ورڈ کی تصدیق کریں',
      passwordMismatch: 'پاس ورڈ ایک جیسے نہیں',
      termsRequired: 'براہ کرم شرائط اور پرائیویسی پالیسی قبول کریں',
      generic: 'اس فیلڈ کو چیک کریں اور دوبارہ کوشش کریں۔',
      ruleLength: 'کم از کم {count} حروف',
      ruleUpper: 'بڑا حرف',
      ruleLower: 'چھوٹا حرف',
      ruleNumber: 'عدد',
      ruleSpecial: 'خاص حرف',
      strengthWeak: 'کمزور',
      strengthMedium: 'درمیانہ',
      strengthStrong: 'مضبوط',
    },
  },
  home: {
    brand: 'VidoraX',
    greetingWelcome: 'VidoraX میں خوش آمدید',
    pasteLink: 'لنک پیسٹ کریں',
    pasteLinkA11y: 'ویڈیو صفحہ کھولنے کے لیے براؤزر میں لنک پیسٹ کریں',
    openBrowser: 'براؤزر کھولیں',
    openBrowserA11y: 'VidoraX براؤزر کھولیں',
    quickAccess: 'فوری رسائی',
    quickAccessSubtitle: 'اپنی پسندیدہ پلیٹ فارمز کھولیں',
    quickAccessA11y: 'مشہور ویڈیو اور سوشل ویب سائٹس تک فوری رسائی',
    openSettingsA11y: 'سیٹنگز کھولیں',
    activeDownloads: 'فعال ڈاؤن لوڈز',
    noActiveDownloads: 'اس وقت کچھ ڈاؤن لوڈ نہیں ہو رہا',
    recentDownloads: 'حالیہ ڈاؤن لوڈز',
    noDownloadsYet: 'ابھی کوئی ڈاؤن لوڈ نہیں',
    continueWatching: 'دیکھنا جاری رکھیں',
    noVideosToContinue: 'اس وقت کچھ نہیں چل رہا',
    recentlyWatched: 'حال ہی میں دیکھی گئی',
    watchHistoryEmpty: 'واچ ہسٹری خالی ہے',
    storage: 'اسٹوریج',
    storageUnavailable: 'اسٹوریج کی تفصیل دستیاب نہیں',
    storageUsed: 'استعمال شدہ',
    storageFree: 'دستیاب',
    viewAll: 'سب دیکھیں',
    viewLibraryA11y: 'لائبریری میں سب دیکھیں',
    viewDownloadsA11y: 'ڈاؤن لوڈز کھولیں',
    viewHistoryA11y: 'واچ ہسٹری کھولیں',
    viewStorageA11y: 'اسٹوریج مینیجر کھولیں',
    resumeA11y: 'ویڈیو پلیئر کھولتا ہے',
    refreshA11y: 'ہوم تازہ کریں',
    downloadingCount: '{count} ڈاؤن لوڈ ہو رہے ہیں',
    pausedCount: '{count} روکے ہوئے',
    queuedCount: '{count} قطار میں',
    averageProgressA11y: 'اوسط ڈاؤن لوڈ پیش رفت {percent} فیصد',
    storageUsageA11y: 'لائبریری اسٹوریج استعمال شدہ اور دستیاب کا {percent} فیصد',
  },
  browser: {
    title: 'براؤزر',
    addressPlaceholder: 'تلاش کریں یا ویڈیو لنک پیسٹ کریں',
    addressBar: 'ایڈریس بار',
    goBack: 'پیچھے جائیں',
    goForward: 'آگے جائیں',
    goHome: 'ہوم',
    tabs: 'ٹیبز',
    menu: 'براؤزر مینو',
    openMenuA11y: 'براؤزر مینو کھولیں',
    newTab: 'نیا ٹیب',
    newTabA11y: 'نیا براؤزر ٹیب کھولیں',
    tabsLimitReached: 'زیادہ سے زیادہ ۱۰ ٹیبز کھلے ہیں',
    tabsLimitReachedA11y: 'براؤزر ٹیبز کی حد ۱۰ تک پہنچ چکی ہے',
    tabSwitcherTitle: 'ٹیبز',
    tabSwitcherCloseA11y: 'ٹیب بند کریں',
    tabSwitcherOpenA11y: 'ٹیب سوئچر کھولیں',
    tabActiveA11y: 'فعال ٹیب',
    closeTab: 'ٹیب بند کریں',
    addBookmark: 'بک مارک شامل کریں',
    addBookmarkA11y: 'موجودہ صفحے کا بک مارک شامل کریں',
    addBookmarkFailed: 'بک مارک محفوظ نہیں ہو سکا',
    alreadyBookmarked: 'پہلے سے بک مارک ہے',
    alreadyBookmarkedA11y: 'موجودہ صفحہ پہلے سے بک مارک ہے',
    bookmarkSaved: 'بک مارک محفوظ ہو گیا',
    linkCopied: 'لنک کاپی ہو گیا',
    copyLinkA11y: 'موجودہ صفحے کا لنک کاپی کریں',
    sharePageA11y: 'موجودہ صفحہ شیئر کریں',
    desktopSiteA11y: 'موجودہ سائٹ کا ڈیسک ٹاپ ورژن',
    desktopSiteEnabled: 'ڈیسک ٹاپ سائٹ فعال',
    desktopSiteDisabled: 'موبائل سائٹ فعال',
    openExternalA11y: 'موجودہ صفحہ بیرونی براؤزر میں کھولیں',
    openExternalFailed: 'بیرونی براؤزر میں نہیں کھل سکا',
    openDownloadsA11y: 'ڈاؤن لوڈز کھولیں',
    activeDownloads: 'فعال ڈاؤن لوڈز',
    activeDownloadsA11y: 'فعال ڈاؤن لوڈز کھولیں',
    recentDownloads: 'حالیہ ڈاؤن لوڈز',
    recentDownloadsA11y: 'حالیہ ڈاؤن لوڈز کھولیں',
    continueWatching: 'دیکھنا جاری رکھیں',
    continueWatchingA11y: 'لائبریری میں دیکھنا جاری رکھیں کھولیں',
    recentlyWatched: 'حال ہی میں دیکھی گئی',
    recentlyWatchedA11y: 'لائبریری میں حال ہی میں دیکھی گئی کھولیں',
    openSettingsA11y: 'سیٹنگز کھولیں',
    aiAssistant: 'AI معاون',
    settings: 'سیٹنگز',
    sharePage: 'صفحہ شیئر کریں',
    openExternal: 'بیرونی براؤزر میں کھولیں',
    copyLink: 'لنک کاپی کریں',
    readerMode: 'ریڈر موڈ',
    translatePage: 'صفحہ ترجمہ کریں',
    desktopSite: 'ڈیسک ٹاپ سائٹ',
    qrCode: 'QR کوڈ اسکین کریں',
    bookmarks: 'بک مارکس',
    history: 'ہسٹری',
    downloads: 'ڈاؤن لوڈز',
    goToWebsite: 'ویب سائٹ کھولیں',
    searchGoogle: 'Google پر “{query}” تلاش کریں',
    addressEmpty: 'ویب سائٹ کا پتہ درج کریں یا ویب پر تلاش کریں۔',
    addressInvalid: 'یہ درست پتہ نہیں لگتا۔ ویب سائٹ یا تلاش آزمائیں۔',
    youtubeNotSupported: 'یوٹیوب ڈاؤن لوڈز معاون نہیں ہیں',
    addressBlocked: 'حفاظتی وجوہات کی بنا پر اس قسم کا پتہ نہیں کھولا جا سکتا۔',
    addressIncomplete: 'پتہ نامکمل ہے۔ پوری ویب سائٹ کا نام آزمائیں۔',
    mediaDetected: 'ڈاؤن لوڈ کے قابل ویڈیو ملی',
    addressHint: 'ویب سائٹ کا پتہ یا تلاش درج کریں۔ ٹائپ کرتے ہی تجاویز آتی ہیں۔',
    sslHomeHint: 'اس غیر محفوظ کنکشن کو چھوڑیں اور براؤزر ہوم پر واپس جائیں',
    sslRetryHint: 'یہ صفحہ دوبارہ لوڈ کریں۔ صرف اس صورت میں جاری رکھیں جب آپ سائٹ پر بھروسہ کرتے ہوں',
    retryHint: 'صفحہ دوبارہ لوڈ کریں',
    goHomeHint: 'براؤزر ہوم پر واپس جائیں',
    dismissSuggestions: 'تجاویز بند کریں',
    suggestionsA11y: 'ایڈریس بار کی تجاویز',
    goAction: 'جائیں',
    clearAddressA11y: 'پتہ صاف کریں',
    loadingPageA11y: 'صفحہ لوڈ ہو رہا ہے',
    pageProgressA11y: 'صفحہ لوڈ ہونے کی پیش رفت',
    webContentA11y: 'ویب مواد',
    openBookmarksA11y: 'بک مارکس کھولیں',
    openHistoryA11y: 'براؤزنگ ہسٹری کھولیں',
    media: {
      videoAvailable: 'ویڈیو دستیاب',
      alreadyDownloaded: 'پہلے سے ڈاؤن لوڈ شدہ',
      detectingVideo: 'ویڈیو تلاش ہو رہی ہے',
      downloadingVideo: 'ڈاؤن لوڈ ہو رہی ہے…',
      downloadedVideo: 'ڈاؤن لوڈ مکمل',
      protectedVideo: 'محفوظ ویڈیو — ڈاؤن لوڈ نہیں ہو سکتی',
      unsupportedVideo: 'یہ ویڈیو ڈاؤن لوڈ نہیں ہو سکتی',
      download: 'ڈاؤن لوڈ',
      preparingDownload: 'ڈاؤن لوڈ تیار ہو رہا ہے…',
      cantDownload: 'یہ ویڈیو VidoraX سے ڈاؤن لوڈ نہیں ہو سکتی۔',
      videoAvailableA11y: 'ویڈیو دستیاب',
      videoAvailableHint: 'یہ ویڈیو ڈاؤن لوڈ کرتا ہے',
      downloadA11y: 'یہ ویڈیو ڈاؤن لوڈ کریں',
      chooseQualityHint: 'ڈاؤن لوڈ کے لیے کوالٹی منتخب کریں۔',
    },
    home: {
      dashboardA11y: 'براؤزر شروع صفحہ',
      startPageA11y: 'براؤزر شروع صفحہ',
      brandA11y: 'VidoraX',
      startSubtitle: 'براؤز کریں یا شروع کرنے کے لیے ویڈیو لنک پیسٹ کریں۔',
      quickAccess: 'فوری رسائی',
      bookmarksTab: 'بک مارکس',
      recentHistory: 'ہسٹری',
      viewAll: 'سب دیکھیں',
      viewAllHistoryA11y: 'تمام براؤزنگ ہسٹری دیکھیں',
      viewAllBookmarksA11y: 'تمام بک مارکس دیکھیں',
      clearHistoryA11y: 'براؤزنگ ہسٹری صاف کریں',
      clearHistoryTitle: 'ہسٹری صاف کریں؟',
      clearHistoryMessage: 'اس ڈیوائس سے تمام براؤزنگ ہسٹری ہٹا دی جائے گی۔',
      clearHistoryConfirm: 'صاف کریں',
      noRecentHistory: 'آپ جو صفحات دیکھیں گے وہ یہاں ظاہر ہوں گے۔',
      noBookmarks: 'محفوظ بک مارکس یہاں ظاہر ہوں گے۔',
      openSiteA11y: '{name} کھولیں',
      openSiteHint: 'ویب سائٹ VidoraX براؤزر میں کھولتا ہے',
      openBookmarkA11y: 'بک مارک {title} کھولیں',
      tabCountA11y: '{count} ٹیب کھلا',
    },
    saveBookmarkA11y: 'بک مارک محفوظ کریں',
    removeBookmarkA11y: 'بک مارک ہٹائیں',
    pullToRefreshHint: 'صفحہ ریفریش کرنے کے لیے نیچے کھینچیں',
    pageLoadingHint: 'صفحہ لوڈ ہو رہا ہے',
    openSuggestionHint: 'کھولنے کے لیے دو بار ٹیپ کریں',
    downloadableMedia: 'ڈاؤن لوڈ کے قابل میڈیا',
    downloadAvailable: 'ڈاؤن لوڈ دستیاب',
    mediaDetectedShort: 'میڈیا ملا',
    hideDetails: 'تفصیلات چھپائیں',
    showDetails: 'تفصیلات دکھائیں',
    less: 'کم',
    details: 'تفصیلات',
    formatLabel: 'فارمیٹ',
    typeLabel: 'قسم',
    codecLabel: 'کوڈیک',
    confidenceLabel: 'اعتماد',
    downloadUnavailableCta: 'دستیاب نہیں',
    addingDownload: 'شامل ہو رہا ہے…',
    downloadCta: 'ڈاؤن لوڈ',
    downloadThisMediaA11y: 'یہ میڈیا ڈاؤن لوڈ کریں',
    downloadUnavailableMediaA11y: 'اس میڈیا کے لیے ڈاؤن لوڈ دستیاب نہیں',
    startingDownloadAnalysisA11y: 'ڈاؤن لوڈ تجزیہ شروع ہو رہا ہے',
    downloadAnalysisHint: 'فارمیٹ تجزیہ کھولتا ہے، پھر ڈاؤن لوڈ شامل کرتا ہے',
    swipeDownDismiss: 'بند کرنے کے لیے نیچے سوائپ کریں',
    swipeDownDismissMulti: '{count} میڈیا · بند کرنے کے لیے نیچے سوائپ کریں',
    swipeDismissHide: 'چھپانے کے لیے نیچے سوائپ کریں یا بند دبائیں۔',
    discoveryCardA11y: '{status}۔ {title}۔ {meta}۔ {hint}',
    errors: {
      invalid_url: {
        title: 'غلط پتہ',
        message: 'یہ درست ویب سائٹ نہیں لگتی۔ پتہ چیک کریں اور دوبارہ کوشش کریں۔',
      },
      load_failed: {
        title: 'صفحہ لوڈ نہیں ہو سکا',
        message: 'صفحہ کھولتے ہوئے مسئلہ ہوا۔ کنکشن چیک کریں اور دوبارہ کوشش کریں۔',
      },
      network_failure: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      dns_failure: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      connection_interrupted: {
        title: 'Unable to open this page',
        message: 'The website could not be loaded.',
      },
      timeout: {
        title: 'بہت زیادہ وقت لگ رہا ہے',
        message: 'صفحہ نے وقت پر جواب نہیں دیا۔ دوبارہ کوشش کریں یا ہوم پر جائیں۔',
      },
      ssl_error: {
        title: 'کنکشن محفوظ نہیں',
        message:
          'اس سائٹ کا سیکیورٹی سرٹیفکیٹ تصدیق نہیں ہو سکا۔ ہوم پر جانا محفوظ انتخاب ہے۔',
      },
      http_error: {
        title: 'صفحہ دستیاب نہیں',
        message: 'ویب سائٹ نے خرابی واپس کی۔ دوبارہ کوشش کریں یا دوسرا پتہ استعمال کریں۔',
      },
      unsupported: {
        title: 'غیر معاون صفحہ',
        message: 'VidoraX اس قسم کا صفحہ نہیں کھول سکتا۔ عام ویب سائٹ پتہ آزمائیں۔',
      },
      process_terminated: {
        title: 'صفحہ بحال ہوا',
        message: 'صفحہ نے جواب دینا بند کر دیا تھا اور دوبارہ لوڈ ہوا۔',
      },
      unknown: {
        title: 'کچھ غلط ہو گیا',
        message: 'غیر متوقع خرابی ہوئی۔ تھوڑی دیر بعد کوشش کریں۔',
      },
    },
  },
  downloads: {
    title: 'ڈاؤن لوڈز',
    detailsTitle: 'ڈاؤن لوڈ کی تفصیل',
    searchPlaceholder: 'ڈاؤن لوڈز تلاش کریں...',
    emptyTitle: 'ابھی کوئی ڈاؤن لوڈ نہیں',
    emptyDescription:
      'براؤزر میں ویڈیو کھولیں۔ VidoraX خودکار طور پر ڈاؤن لوڈ کے قابل ویڈیو تلاش کرتا ہے۔',
    emptyAction: 'براؤزر کھولیں',
    emptySearchTitle: 'کوئی ڈاؤن لوڈ نہیں ملا',
    emptySearchDescription: 'کوئی اور عنوان، فائل نام، یا URL آزمائیں۔',
    emptyFilterTitle: 'یہاں کچھ نہیں',
    emptyFilterDescription: 'اس فلٹر سے کوئی ڈاؤن لوڈ نہیں ملتا۔',
    emptyCompletedTitle: 'کوئی مکمل ڈاؤن لوڈ نہیں',
    emptyCompletedDescription: 'مکمل ڈاؤن لوڈز اس فہرست میں نظر آئیں گے۔',
    errorTitle: 'ڈاؤن لوڈز لوڈ نہیں ہو سکے',
    detailsErrorTitle: 'ڈاؤن لوڈ لوڈ نہیں ہو سکا',
    detailsMissingTitle: 'ڈاؤن لوڈ دستیاب نہیں',
    detailsMissingDescription: 'یہ ڈاؤن لوڈ ہٹا دیا گیا ہو سکتا ہے۔',
    detailsMissingAction: 'ڈاؤن لوڈز پر واپس',
    detailsInfoTitle: 'ڈاؤن لوڈ کی معلومات',
    detailsSourceTitle: 'سورس',
    detailsFavoriteHint: 'اس ڈاؤن لوڈ کو فیوریٹس میں شامل یا ہٹائیں',
    detailsFavoriteLabel: 'فیوریٹ',
    detailsFavoriteAddLabel: 'فیوریٹس میں شامل کریں',
    detailsFavoriteRemoveLabel: 'فیوریٹس سے ہٹائیں',
    detailsFavoriteErrorTitle: 'فیوریٹ اپ ڈیٹ نہیں ہو سکا',
    detailsOpenFile: 'کھولیں',
    detailsShareFile: 'شیئر',
    detailsFileUnavailable: 'فائل اس ڈیوائس پر دستیاب نہیں۔',
    fileUnavailableTitle: 'فائل دستیاب نہیں',
    deleteTitle: 'VidoraX سے حذف کریں؟',
    deleteMessage:
      'اس ڈاؤن لوڈ کو VidoraX سے حذف کریں؟ VidoraX کے باہر محفوظ کاپیاں حذف نہیں ہوں گی۔',
    deleteConfirm: 'حذف کریں',
    deleteCancel: 'منسوخ',
    removeTitle: 'ڈاؤن لوڈز سے ہٹائیں؟',
    removeMessage:
      'یہ صرف اس فہرست سے ہٹے گا۔ ویڈیو آپ کی لائبریری میں رہے گی، اور ڈیوائس پر محفوظ کی گئی کوئی کاپی بھی محفوظ رہے گی۔',
    removeConfirm: 'ہٹائیں',
    deleteFailed: 'یہ ڈاؤن لوڈ حذف نہیں ہو سکا',
    deleteMissingConfirm: 'لائبریری سے ہٹائیں',
    notifications: {
      channelName: 'ڈاؤن لوڈ اپ ڈیٹس',
      downloadingTitle: 'ڈاؤن لوڈ ہو رہا ہے',
      preparingTitle: 'ڈاؤن لوڈ تیار ہو رہا ہے',
      waitingWifiTitle: 'Wi-Fi کا انتظار',
      pausedTitle: 'ڈاؤن لوڈ موقوف',
      retryingTitle: 'دوبارہ کوشش',
      completedTitle: 'ڈاؤن لوڈ مکمل',
      failedTitle: 'ڈاؤن لوڈ ناکام',
      tapForDetails: 'تفصیل دیکھنے کے لیے تھپتھپائیں',
      reasons: {
        sessionExpired: 'سیشن ختم ہو گیا',
        sourceUnavailable: 'ذریعہ دستیاب نہیں',
        fileValidationFailed: 'فائل کی تصدیق ناکام',
        networkError: 'نیٹ ورک خرابی',
      },
    },
    export: {
      saveToDevice: 'ڈیوائس پر محفوظ کریں',
      saving: 'محفوظ ہو رہا ہے…',
      saved: 'ڈیوائس پر محفوظ ہو گیا',
      alreadySaved: 'پہلے سے ڈیوائس پر محفوظ ہے',
      unableToSave: 'یہ فائل محفوظ نہیں ہو سکی',
      notEnoughStorage: 'کافی اسٹوریج نہیں',
      cancelled: 'محفوظ کرنا منسوخ',
    },
    filterTitle: 'فلٹر',
    filterSubtitle: 'اسٹیٹس کے مطابق دکھائیں',
    sortTitle: 'ترتیب',
    sortSubtitle: 'شامل کیے گئے وقت کے مطابق',
    loadingAnnouncement: 'ڈاؤن لوڈز لوڈ ہو رہے ہیں',
    endOfList: 'آپ سب دیکھ چکے ہیں',
    resetControls: 'ری سیٹ',
    primaryPause: 'ڈاؤن لوڈ روکیں',
    primaryResume: 'ڈاؤن لوڈ جاری رکھیں',
    primaryCancel: 'ڈاؤن لوڈ منسوخ کریں',
    primaryRetry: 'ڈاؤن لوڈ دوبارہ کوشش',
    primaryOpen: 'ڈاؤن لوڈ شدہ فائل کھولیں',
    primaryShare: 'ڈاؤن لوڈ شدہ فائل شیئر کریں',
    primaryRemove: 'ڈاؤن لوڈ حذف کریں',
    secondaryCancel: 'ڈاؤن لوڈ منسوخ کریں',
    successToast: 'ڈاؤن لوڈز میں شامل',
    completedToast: 'ویڈیو ڈاؤن لوڈ ہو گئی',
    alreadyDownloadingToast: 'ویڈیو پہلے سے ڈاؤن لوڈ ہو رہی ہے',
    alreadyDownloadedToast: 'ویڈیو پہلے ہی ڈاؤن لوڈ ہو چکی ہے',
    filterAll: 'تمام',
    filterRunning: 'چل رہا',
    filterQueued: 'قطار میں',
    filterPaused: 'روکا ہوا',
    filterCompleted: 'مکمل',
    filterFailed: 'ناکام',
    sortNewest: 'نیا ترین',
    sortOldest: 'پرانا ترین',
    statusQueued: 'قطار میں',
    statusDownloading: 'چل رہا',
    statusPaused: 'روکا ہوا',
    statusCompleted: 'مکمل',
    statusFailed: 'ناکام',
    statusCancelled: 'منسوخ',
    executionForeground: 'ڈاؤن لوڈ ہو رہا ہے',
    executionBackground: 'پسِ منظر میں ڈاؤن لوڈ',
    waitingWifi: 'Wi-Fi کا انتظار',
    waitingNetwork: 'نیٹ ورک کا انتظار',
    retrying: 'دوبارہ کوشش',
    queued: 'قطار میں',
    preparing: 'ڈاؤن لوڈ تیار ہو رہا ہے',
    starting: 'ڈاؤن لوڈ شروع ہو رہا ہے…',
    finalizing: 'مکمل ہو رہا ہے',
    processingMerging: 'آڈیو اور ویڈیو کو یکجا کیا جا رہا ہے',
    processingRemuxing: 'ویڈیو فائل تیار کی جا رہی ہے',
    processingTranscoding: 'ویڈیو تبدیل کی جا رہی ہے',
    processingVerifying: 'ویڈیو کی جانچ ہو رہی ہے',
    qualitySheetTitle: 'ڈاؤن لوڈ شامل کریں',
    qualitySheetSubtitle: 'میڈیا لنک پیسٹ کریں۔ ہم دیکھیں گے کیا محفوظ ہو سکتا ہے۔',
    urlLabel: 'لنک',
    urlPlaceholder: 'https://example.com/video.mp4',
    urlHelper: 'براہ راست ویڈیو، آڈیو، یا سٹریم لنکس بہتر کام کرتے ہیں۔',
    analyzeAction: 'لنک چیک کریں',
    analyzing: 'لنک چیک ہو رہا ہے…',
    pasteAction: 'پیسٹ',
    retryAction: 'دوبارہ کوشش',
    changeLinkAction: 'دوسرا لنک استعمال کریں',
    downloadAction: 'ڈاؤن لوڈ شروع کریں',
    downloadNamed: '{label} ڈاؤن لوڈ',
    downloadingAction: 'ڈاؤن لوڈ شروع ہو رہا ہے…',
    qualitiesTitle: 'فارمیٹ منتخب کریں',
    qualityEmptyTitle: 'یہاں کچھ ڈاؤن لوڈ نہیں ہو سکتا',
    qualityErrorTitle: 'یہ لنک چیک نہیں ہو سکا',
    unsupportedBadge: 'ڈاؤن لوڈ نہیں ہو سکتا',
    missingUrl: 'جاری رکھنے کے لیے لنک پیسٹ کریں',
    invalidUrl: 'درست http یا https لنک درج کریں',
    closeLabel: 'بند کریں',
    selectionHint: 'ڈاؤن لوڈ کے لیے فارمیٹ منتخب کریں',
    selectedHint: 'ڈاؤن لوڈ کے لیے منتخب',
    untitled: 'بلا عنوان ڈاؤن لوڈ',
    infoFormat: 'فارمیٹ',
    infoPlatform: 'پلیٹ فارم',
    infoDuration: 'دورانیہ',
    infoQuality: 'کوالٹی',
    infoResolution: 'ریزولیوشن',
    infoBitrate: 'بٹ ریٹ',
    infoFileSize: 'فائل سائز',
    infoRetryAttempts: 'دوبارہ کوششیں',
    infoLocalFile: 'مقامی فائل',
    availableOnDevice: 'ڈیوائس پر دستیاب',
    missingOnDevice: 'فائل ڈیوائس پر نہیں',
    localFileIncomplete: 'مقامی فائل نامکمل',
    infoFolder: 'فولڈر',
    infoDownloaded: 'ڈاؤن لوڈ شدہ',
    infoCreatedDate: 'بنانے کی تاریخ',
    infoDownloadedDate: 'ڈاؤن لوڈ کی تاریخ',
    downloadedProgress: '{size} ڈاؤن لوڈ ہو چکا',
    failedBanner: 'ڈاؤن لوڈ ناکام',
    retryingSoon: 'دوبارہ کوشش',
    retryingSoonBody: 'اگلی خودکار کوشش کا انتظار ہے۔',
    retryingSoonA11y: 'جلد ڈاؤن لوڈ دوبارہ آزمایا جائے گا',
    statusA11y: 'حیثیت {label}',
    moveToFolder: 'فولڈر میں منتقل کریں',
    moveToFolderHint: 'اس میڈیا کو منطقی فولڈر میں منتقل کریں',
    moveToFolderSubtitle: 'منتخب کریں یہ میڈیا کہاں رہے',
    manageFolders: 'فولڈرز منظم کریں',
    manageFoldersSubtitle: 'منطقی فولڈرز بنائیں، نام تبدیل کریں، یا حذف کریں',
    newFolder: 'نیا فولڈر',
    folderName: 'فولڈر کا نام',
    yourFolders: 'آپ کے فولڈرز',
    noFoldersYet: 'ابھی کوئی فولڈر نہیں — سب کچھ Unfiled سے شروع ہوتا ہے۔',
    deleteFolder: 'فولڈر حذف کریں',
    deleteFolderMessage:
      'اس فولڈر کی آئٹمز Unfiled میں چلی جائیں گی۔ فزیکل فائلیں نہیں بدلیں گی۔',
    renameDisplayName: 'میڈیا کا دکھائی دینے والا نام اپ ڈیٹ کریں',
    newName: 'نیا نام',
    openQueue: 'ڈاؤن لوڈ قطار کھولیں',
    openQueueHint: 'فعال ڈاؤن لوڈز اور انتظار میں آئٹمز دکھاتا ہے',
    openFavoritesA11y: 'پسندیدہ کھولیں',
    openFavoritesHint: 'پسندیدہ ڈاؤن لوڈز دکھاتا ہے',
    pasteLinkHint: 'براؤزر کھولتا ہے تاکہ آپ ویڈیو صفحہ پیسٹ یا کھول سکیں',
    opensDetails: 'ڈاؤن لوڈ کی تفصیلات کھولتا ہے',
    favoriteEnabled: 'پسندیدہ آن',
    favoriteDisabled: 'پسندیدہ آف',
    actionsA11y: 'ڈاؤن لوڈ ایکشنز',
    pauseNamedA11y: '{title} روکیں',
    resumeNamedA11y: '{title} جاری رکھیں',
    pauseUnsupported:
      'یہ ماخذ ریزیوم نہیں کرتا، اس لیے روکنے پر ڈاؤن لوڈ نئے سرے سے شروع ہوگا',
    cancelNamedA11y: '{title} منسوخ کریں',
    percentA11y: '{percent} فیصد',
    queuePositionA11y: 'مقام {position}',
    searchA11y: 'ڈاؤن لوڈز تلاش کریں',
    retryLoadA11y: 'ڈاؤن لوڈز دوبارہ لوڈ کریں',
    refreshListA11y: 'ڈاؤن لوڈز ریفریش کریں',
    loadingA11y: 'ڈاؤن لوڈز لوڈ ہو رہے ہیں',
    loadingDetailsA11y: 'ڈاؤن لوڈ تفصیل لوڈ ہو رہی ہے',
    thumbnailA11y: '{title} کی تھمب نیل',
    searchFilterHint: 'عنوان، فائل نام، یا URL سے فلٹر',
    resetFiltersHint: 'تلاش، فلٹر، اور ترتیب صاف کرتا ہے',
    analyzeLinkHint: 'ڈاؤن لوڈ کے قابل فارمیٹس کے لیے لنک چیک کرتا ہے',
  },
  deviceVideos: {
    title: 'اس ڈیوائس پر',
    subtitle: 'آپ کے فون پر پہلے سے محفوظ ویڈیوز',
    empty: 'اس ڈیوائس پر کوئی ویڈیو نہیں ملی۔',
    permission: 'یہاں چلانے کے لیے VidoraX کو اپنی ویڈیوز پڑھنے کی اجازت دیں۔',
    allow: 'اجازت دیں',
    unavailable: 'اس بلڈ میں دستیاب نہیں۔',
    limited: 'صرف وہ ویڈیوز جن تک آپ نے VidoraX کو رسائی دی',
    open: 'اس ڈیوائس کی ویڈیوز',
  },
  library: {
    title: 'پلیئر',
    searchPlaceholder: 'ڈاؤن لوڈ شدہ ویڈیوز تلاش کریں',
    emptyTitle: 'ابھی کوئی ڈاؤن لوڈ نہیں',
    emptyDescription:
      'اس ڈیوائس پر دستیاب مکمل ڈاؤن لوڈز یہاں نظر آئیں گے۔',
    emptyAction: 'ڈاؤن لوڈز پر جائیں',
    emptySearchTitle: 'کوئی ویڈیو نہیں ملی',
    emptySearchDescription: 'کوئی اور عنوان، فائل نام، کوالٹی، یا فولڈر آزمائیں۔',
    emptyFilterTitle: 'کوئی ویڈیو نہیں ملی',
    emptyFilterDescription: 'تمام منتخب کریں، یا دوسرا فلٹر آزمائیں۔',
    emptyFavoritesTitle: 'ابھی کوئی فیوریٹ نہیں',
    emptyFavoritesDescription: 'ویڈیوز کو فیوریٹ نشان زد کریں تاکہ وہ یہاں ملیں۔',
    emptyFolderTitle: 'یہ فولڈر خالی ہے',
    emptyFolderDescription: 'ڈاؤن لوڈ کی تفصیل سے ویڈیوز اس فولڈر میں منتقل کریں۔',
    errorTitle: 'لائبریری لوڈ نہیں ہو سکی',
    errorRetry: 'دوبارہ کوشش کریں',
    offlineHint: 'اس ڈیوائس پر محفوظ ڈاؤن لوڈز دکھائے جا رہے ہیں۔',
    filterTitle: 'فلٹر',
    filterSubtitle: 'کیٹگری کے مطابق دکھائیں',
    sortTitle: 'ترتیب',
    sortSubtitle: 'لائبریری کی ترتیب',
    qualityTitle: 'کوالٹی',
    qualitySubtitle: 'خاص کوالٹی کی ویڈیوز دکھائیں',
    resetControls: 'ری سیٹ',
    viewList: 'لسٹ ویو',
    viewGrid: 'گرڈ ویو',
    loadingAnnouncement: 'لائبریری لوڈ ہو رہی ہے',
    emptyRecentlyWatchedTitle: 'حال ہی میں دیکھی گئی ویڈیوز نہیں',
    emptyRecentlyWatchedDescription:
      'جو ویڈیوز آپ چلائیں گے وہ یہاں آخری بار دیکھے گئے وقت کے مطابق آئیں گی۔',
    continueWatchingTitle: 'دیکھنا جاری رکھیں',
    continueWatchingEmpty: 'جاری رکھنے کے لیے ویڈیو نہیں',
    continueWatchingEmptyDescription:
      'نامکمل ویڈیوز جو آپ دیکھنا شروع کریں گے وہ یہاں نظر آئیں گی۔',
    watchedBadge: 'دیکھی گئی',
    watchHistoryTitle: 'واچ ہسٹری',
    filterAll: 'تمام',
    filterFavorites: 'فیوریٹس',
    filterRecentlyDownloaded: 'حالیہ ڈاؤن لوڈز',
    filterRecentlyWatched: 'حال ہی میں دیکھی گئی',
    filterFolder: 'فولڈر',
    sortNewest: 'نیا ترین',
    sortOldest: 'پرانا ترین',
    sortNameAsc: 'نام ا سےے',
    sortNameDesc: 'نام ے سے ا',
    sortLargest: 'بڑی فائلیں',
    sortSmallest: 'چھوٹی فائلیں',
    sortRecentlyPlayed: 'حال ہی میں چلائی گئی',
    searchA11y: 'ڈاؤن لوڈ شدہ ویڈیوز تلاش کریں',
    watchProgressA11y: 'واچ پیش رفت',
    retryLoadA11y: 'لائبریری دوبارہ لوڈ کریں',
    refreshListA11y: 'لائبریری ریفریش کریں',
    favoriteA11y: 'پسندیدہ',
    searchFilterHint: 'عنوان، فائل نام، کوالٹی، یا فولڈر نام سے فلٹر',
    resetFiltersHint: 'تلاش، فلٹر، اور ترتیب صاف کرتا ہے',
    actionsTitle: 'مکمل فائل',
    actionsSubtitle: 'کھولیں، شیئر، محفوظ، یا حذف',
    openWith: 'اس سے کھولیں…',
    share: 'شیئر',
    play: 'چلائیں',
    saveToDevice: 'ڈیوائس پر محفوظ کریں',
    deleteFromVidoraX: 'VidoraX سے حذف کریں',
    fileUnavailable: 'فائل دستیاب نہیں',
    actionFailed: 'یہ عمل مکمل نہیں ہو سکا۔',
    longPressHint: 'کھولیں، شیئر، محفوظ، اور حذف کے اختیارات دکھاتا ہے',
    playHint: 'ویڈیو پلیئر کھولتا ہے',
    deleteTitle: 'VidoraX سے حذف کریں؟',
    deleteMessage:
      'اس ڈاؤن لوڈ کو VidoraX سے حذف کریں؟ VidoraX کے باہر محفوظ کاپیاں حذف نہیں ہوں گی۔',
    deleteConfirm: 'حذف کریں',
    deleteCancel: 'منسوخ',
    deleteFailed: 'یہ ڈاؤن لوڈ حذف نہیں ہو سکا',
    removeFromLibrary: 'لائبریری سے ہٹائیں',
    saving: 'محفوظ ہو رہا ہے…',
    savedToDevice: 'ڈیوائس پر محفوظ ہو گیا',
    alreadySavedToDevice: 'پہلے سے ڈیوائس پر محفوظ ہے',
    unableToSave: 'یہ فائل محفوظ نہیں ہو سکی',
  },
  player: {
    mini: {
      openA11y: 'اب چل رہا ہے: {title}۔ پلیئر کھولیں',
      openHint: 'پورا پلیئر کھولتا ہے۔ بند کرنے کے لیے دائیں یا بائیں سوائپ کریں۔',
      close: 'پلیئر بند کریں',
    },
    continueWatching: 'دیکھنا جاری رکھیں؟',
    continueWatchingBody: 'جہاں چھوڑا تھا وہیں سے شروع کریں، یا شروع سے چلائیں۔',
    startOver: 'شروع سے',
    resumeFrom: '{time} سے جاری رکھیں',
    play: 'ویڈیو چلائیں',
    pause: 'ویڈیو روکیں',
    replay: 'دوبارہ چلائیں',
    rewind: '10 سیکنڈ پیچھے',
    forward: '10 سیکنڈ آگے',
    previousVideo: 'پچھلی ویڈیو',
    nextVideo: 'اگلی ویڈیو',
    lockScreen: 'اسکرین لاک کریں',
    unlockScreen: 'اسکرین ان لاک کریں',
    screenLocked: 'اسکرین لاک ہے · کھولنے کے لیے ٹیپ کریں',
    mute: 'آواز بند',
    unmute: 'آواز چالو',
    preparing: 'ویڈیو تیار ہو رہی ہے',
    playbackSpeed: 'چلانے کی رفتار',
    playbackSpeedSelected: 'چلانے کی رفتار، {rate} منتخب',
    speedSelected: 'منتخب {rate}',
    orientationTitle: 'سمت',
    orientationSelected: 'منتخب {mode}',
    orientation: {
      auto: 'خودکار',
      portrait: 'عمودی',
      landscape: 'افقی',
    },
    enterFullscreen: 'فل اسکرین',
    exitFullscreen: 'فل اسکرین بند کریں',
    goBack: 'واپس جائیں',
    untitled: 'ویڈیو',
    seekTimelineA11y: 'سییک ٹائم لائن',
    videoSurfaceA11y: 'ویڈیو سرفیس',
    surfaceHint: 'کنٹرولز کے لیے ٹیپ کریں۔ روشنی کے لیے بائیں کنارہ، آواز کے لیے دائیں کنارہ سوائپ کریں۔ سییک کے لیے کسی طرف دو بار ٹیپ کریں۔ زوم کے لیے دو انگلیوں سے پھیلائیں؛ دو بار ٹیپ سے زوم ختم ہو جاتا ہے۔',
    hud: {
      brightness: 'روشنی {percent} فیصد',
      volume: 'آواز {percent} فیصد',
      zoom: 'زوم {percent} فیصد',
    },
    missingFile: 'یہ ویڈیو اب اس ڈیوائس پر نہیں ہے۔',
    unsupported: 'یہ ویڈیو اس ڈیوائس پر نہیں چل سکتی۔',
    errors: {
      MEDIA_NOT_FOUND: {
        title: 'نہیں ملی',
        message: 'یہ ویڈیو آپ کی لائبریری میں نہیں ملی۔',
      },
      FILE_UNAVAILABLE: {
        title: 'دستیاب نہیں',
        message: 'فائل اب دستیاب نہیں۔',
      },
      SOURCE_RESOLUTION_FAILED: {
        title: 'چلایا نہیں جا سکا',
        message: 'ویڈیو چلانے کی تیاری نہیں ہو سکی۔',
      },
      UNSUPPORTED_MEDIA: {
        title: 'غیر معاون فارمیٹ',
        message: 'اس ویڈیو کا فارمیٹ اس ڈیوائس پر نہیں چل سکتا۔',
      },
      CORRUPT_MEDIA: {
        title: 'ناقابلِ پڑھائی ویڈیو',
        message: 'یہ ویڈیو فائل خراب یا ناقابلِ پڑھائی لگتی ہے۔',
      },
      PERMISSION_DENIED: {
        title: 'اجازت درکار',
        message: 'VidoraX کو یہ فائل چلانے کی اجازت نہیں۔',
      },
      PLAYER_INIT_FAILED: {
        title: 'پلیئر خرابی',
        message: 'ویڈیو پلیئر شروع نہیں ہو سکا۔',
      },
      PLAYBACK_FAILED: {
        title: 'پلے بیک خرابی',
        message: 'ویڈیو نہیں چل سکی۔ دوبارہ کوشش کریں۔',
      },
      PREPARATION_TIMEOUT: {
        title: 'ابھی تیار ہو رہی ہے',
        message: 'اس ویڈیو کی تیاری میں زیادہ وقت لگ رہا ہے۔',
      },
    },
  },
  settings: {
    screenTitle: 'سیٹنگز',
    screenSubtitle: 'اس ڈیوائس کی ترجیحات',
    loadingA11y: 'سیٹنگز لوڈ ہو رہی ہیں',
    appearanceSection: 'ظاہری شکل',
    appearanceDescription: 'ایپ کی شکل اور احساس',
    defaultBrowser: 'ڈیفالٹ براؤزر',
    defaultBrowserHintOn: 'اس ڈیوائس پر ویب لنکس VidoraX میں کھلتے ہیں۔',
    defaultBrowserHintOff: 'دوسری ایپس کے ویب لنکس VidoraX میں کھولیں۔',
    defaultBrowserValueOn: 'آن',
    defaultBrowserValueOff: 'سیٹ کریں',
    defaultBrowserUnavailable: 'اس ڈیوائس پر دستیاب نہیں',
    generalSection: 'جنرل',
    generalDescription: 'زبان اور علاقائی ترجیحات',
    downloadsSection: 'ڈاؤن لوڈز',
    downloadsDescription: 'اس ڈیوائس پر ڈاؤن لوڈز کیسے چلیں',
    downloadSettings: 'ڈاؤن لوڈ سیٹنگز',
    downloadSettingsHint: 'Wi-Fi، دوبارہ شروع، تعداد، اور اطلاعات',
    notificationsSection: 'اطلاعات',
    notificationsDescription: 'الرٹس اور سرگرمی کی اپ ڈیٹس',
    aboutSection: 'تعارف',
    aboutDescription: 'ایپ کی معلومات',
    legalSection: 'قانونی',
    legalDescription: 'پرائیویسی، شرائط، اور ایپ کی معلومات',
    privacySection: 'پرائیویسی',
    privacySectionDescription: 'اس ڈیوائس پر VidoraX تک رسائی محفوظ کریں',
    appLock: 'ایپ لاک',
    appLockHint: 'VidoraX پر واپس آنے پر PIN درکار ہو',
    changePin: 'PIN تبدیل کریں',
    changePinHint: 'اپنا ایپ لاک PIN تبدیل کریں',
    changePinA11y: 'PIN تبدیل کرنے کا اسکرین کھولتا ہے',
    generateRecoveryCode: 'نیا ریکوری کوڈ بنائیں',
    generateRecoveryCodeHint: 'محفوظ ریکوری کوڈ تبدیل کریں',
    generateRecoveryCodeA11y: 'نیا ریکوری کوڈ بنانے کا اسکرین کھولتا ہے',
    helpAccountSection: 'مدد اور سپورٹ',
    helpAccountDescription: 'ہیلپ سینٹر اور مسئلہ رپورٹنگ',
    supportSection: 'سپورٹ',
    supportSectionDescription: 'مدد، رپورٹنگ، اور تاثرات',
    howToUseSection: 'VidoraX کیسے استعمال کریں',
    howToUseDescription: 'چند مراحل میں ویڈیو ڈاؤن لوڈ کریں',
    howToUseStep1: 'کوئی معاون ویڈیو لنک پیسٹ کریں یا کھولیں۔',
    howToUseStep2: 'ویڈیو تک براؤز یا اسکرول کریں۔',
    howToUseStep3: '“ویڈیو دستیاب” کا انتظار کریں۔',
    howToUseStep4: 'اس پر ٹیپ کریں۔',
    howToUseStep5: 'اگر دستیاب ہو تو کوالٹی منتخب کریں۔',
    howToUseStep6: 'ویڈیو ڈاؤن لوڈ کریں۔',
    howToUseStep7: 'مکمل ویڈیوز ڈاؤن لوڈز / گیلری میں دیکھیں۔',
    howToUseNoteYouTube: 'YouTube ڈاؤن لوڈز معاون نہیں ہیں۔',
    howToUseNoteDrm: 'DRM سے محفوظ ویڈیوز ڈاؤن لوڈ نہیں ہو سکتیں۔',
    helpSupportSection: 'مدد اور سپورٹ',
    helpSupportDescription: 'VidoraX ٹیم سے رابطہ کریں',
    contactSupport: 'سپورٹ سے رابطہ کریں',
    contactSupportA11y: 'VidoraX سپورٹ کو لکھنے کے لیے ای میل ایپ کھولتا ہے',
    reportIssue: 'مسئلہ رپورٹ کریں',
    reportIssueHint: 'ہمیں ای میل کریں کہ کیا غلط ہوا',
    reportIssueA11y: 'مسئلے کی رپورٹ کے ساتھ ای میل ایپ کھولتا ہے',
    noEmailAppTitle: 'کوئی ای میل ایپ نہیں ملی',
    noEmailAppMessage: 'ای میل ایپ انسٹال یا سیٹ اپ کریں، یا کسی بھی ڈیوائس سے {email} پر لکھیں۔',
    copyEmailAddress: 'پتہ کاپی کریں',
    accountSectionTitle: 'ڈیوائس',
    accountSectionDescription: 'اس ڈیوائس پر محفوظ ترجیحات',
    storageSection: 'اسٹوریج',
    storageSectionDescription: 'اس ڈیوائس پر ڈاؤن لوڈ شدہ میڈیا منظم کریں',
    manageStorage: 'اسٹوریج منظم کریں',
    manageStorageHint: 'ڈاؤن لوڈز دیکھنے اور ہٹانے کے لیے لائبریری کھولیں',
    manageStorageA11y: 'اسٹوریج منظم کرنے کے لیے لائبریری کھولتا ہے',
    reportProblem: 'مسئلہ رپورٹ کریں',
    reportProblemHint: 'تحقیق کے لیے مسئلہ بیان کریں',
    reportProblemA11y: 'مسئلہ رپورٹ کرنے کا فارم کھولتا ہے',
    rateVidoraX: 'VidoraX\u200E کو ریٹ کریں',
    rateVidoraXHint: 'Play Store پر VidoraX\u200E کو ریٹ کریں',
    rateVidoraXA11y: 'ریٹ کرنے کے لیے Play Store فہرست کھولتا ہے',
    signOutHint: 'استعمال نہیں — VidoraX میں اکاؤنٹ سائن آؤٹ نہیں',
    signOutA11y: 'استعمال نہیں — VidoraX میں اکاؤنٹ سائن آؤٹ نہیں',
    comingSoon: 'جلد آ رہا ہے',
    emptyTitle: 'سیٹنگز دستیاب نہیں',
    emptyDescription:
      'ترجیحات نہیں ملیں۔ نیچے کھینچ کر تازہ کریں یا دوبارہ کوشش کریں۔',
    signOut: 'سائن آؤٹ',
    theme: 'تھیم',
    themeHint: 'سسٹم، ریڈ، یا ڈارک',
    themeA11y: 'تھیم کی ترجیح',
    themeLight: 'سسٹم',
    themeLogo: 'ریڈ',
    themeDark: 'ڈارک',
    themeLightA11y: 'سسٹم تھیم',
    themeLogoA11y: 'ریڈ تھیم',
    themeDarkA11y: 'ڈارک تھیم',
    language: 'زبان',
    languageHint: 'VidoraX کی ڈسپلے زبان',
    languageSheetTitle: 'زبان منتخب کریں',
    languageSheetSubtitle: 'زبان منتخب کریں۔ ایپ فوراً اپ ڈیٹ ہو جائے گی۔',
    languageOpenHint: 'زبان کے انتخاب کا شیٹ کھولتا ہے',
    languageSelected: '{label} منتخب',
    languageNameEn: 'انگریزی',
    languageNameUr: 'اردو',
    wifiOnly: 'صرف Wi-Fi',
    wifiOnlyHint: 'صرف Wi-Fi پر ڈاؤن لوڈ کریں',
    autoResume: 'خودکار جاری',
    autoResumeHint: 'رکے ہوئے ڈاؤن لوڈز خود بخود جاری رکھیں',
    downloadDirectory: 'ڈاؤن لوڈ مقام',
    downloadDirectoryHint: 'اس ڈیوائس پر ایپ کے زیر ڈاؤن لوڈ اسٹوریج',
    notifications: 'اطلاعات',
    notificationsHint: 'ڈاؤن لوڈ اور سرگرمی کی اطلاعات حاصل کریں',
    aboutApp: 'VidoraX کے بارے میں',
    aboutAppHint: 'ورژن، اپڈیٹس، اور پروڈکٹ کی معلومات',
    privacyPolicy: 'پرائیویسی پالیسی',
    privacyHint: 'VidoraX آپ کی معلومات کیسے سنبھالتا ہے',
    termsConditions: 'شرائط و ضوابط',
    termsHint: 'VidoraX استعمال کے اصول',
    support: 'مدد اور سپورٹ',
    supportHint: 'مدد حاصل کریں یا ہم سے رابطہ کریں',
    profile: 'ڈیوائس ترجیحات',
    profileHint: 'اس ڈیوائس پر زبان، تھیم، اور ڈاؤن لوڈ ترجیحات',
    successTitle: 'ترجیح محفوظ ہو گئی',
    successMessage: 'آپ کی سیٹنگز اس ڈیوائس پر محفوظ ہو گئیں۔',
    pendingSyncTitle: 'اس ڈیوائس پر محفوظ',
    pendingSyncMessage: 'آپ کی ترجیح اس ڈیوائس پر محفوظ ہے۔',
    preferenceErrorTitle: 'ترجیح محفوظ نہیں ہو سکی',
    loadUnauthorized: 'اس ڈیوائس سے سیٹنگز نہیں پڑھی جا سکیں۔',
    saveUnauthorized: 'اس ڈیوائس پر سیٹنگز محفوظ نہیں ہو سکیں۔',
    forbidden: 'یہ سیٹنگز تبدیلی دستیاب نہیں۔',
    invalidPreference: 'یہ ترجیح معاونت شدہ نہیں۔ دوسرا آپشن منتخب کریں۔',
    unsupportedLanguage: 'یہ زبان ابھی معاونت شدہ نہیں۔ دوسری منتخب کریں۔',
    unsupportedTheme: 'یہ تھیم معاونت شدہ نہیں۔ دوسرا آپشن منتخب کریں۔',
    loadFailed: 'سیٹنگز لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔',
    saveFailed: 'سیٹنگز محفوظ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔',
    currentValue: 'موجودہ: {value}۔',
    aboutAppA11y: 'تعارف اسکرین کھولتا ہے',
    privacyA11y: 'پرائیویسی پالیسی کھولتا ہے',
    termsA11y: 'شرائط و ضوابط کھولتا ہے',
    supportA11y: 'مدد اور سپورٹ اسکرین کھولتا ہے',
    profileA11y: 'ڈیوائس ترجیحات کھولتا ہے',
    downloadSettingsTitle: 'ڈاؤن لوڈ سیٹنگز',
    downloadSettingsSubtitle: 'اس ڈیوائس پر ڈاؤن لوڈز کا رویہ کنٹرول کریں',
    behaviorSection: 'ڈاؤن لوڈ کا رویہ',
    behaviorDescription: 'نئے ڈاؤن لوڈز کب شروع ہوں اور کیسے بحال ہوں',
    performanceSection: 'کارکردگی',
    performanceDescription: 'ایک وقت میں کتنے ڈاؤن لوڈز چل سکتے ہیں',
    downloadNotificationsSection: 'اطلاعات',
    downloadNotificationsDescription: 'ڈاؤن لوڈ مکمل یا ناکام ہونے پر اطلاع پائیں۔',
    wifiOnlyLong: 'صرف Wi-Fi پر ڈاؤن لوڈ',
    wifiOnlyLongHint: 'نئے ڈاؤن لوڈز Wi-Fi دستیاب ہونے تک انتظار کریں گے۔',
    saveToGallery: 'گیلری میں محفوظ کریں',
    saveToGalleryHint: 'مکمل ویڈیوز آپ کے فون کی گیلری ایپ میں بھی نظر آئیں گی۔',
    autoResumeLong: 'رکے ہوئے ڈاؤن لوڈز خود بخود جاری رکھیں',
    autoResumeLongHint: 'موزوں رکے ہوئے ڈاؤن لوڈز محفوظ ہونے پر جاری ہوں گے۔',
    maxConcurrent: 'زیادہ سے زیادہ بیک وقت ڈاؤن لوڈز',
    maxConcurrentHint: 'منتخب کریں ایک وقت میں کتنے ڈاؤن لوڈز چلیں۔',
    downloadNotifications: 'ڈاؤن لوڈ اطلاعات',
    downloadNotificationsHint: 'ڈاؤن لوڈ مکمل یا ناکام ہونے پر اطلاع پائیں۔',
    notificationsPermissionRequired: 'اطلاعات کی اجازت درکار ہے',
    notificationsPermissionHint:
      'ڈاؤن لوڈ اطلاعات کے لیے Android سیٹنگز میں اجازت دیں۔',
    openSystemSettings: 'Android سیٹنگز کھولیں',
    downloadSettingsSuccessMessage: 'آپ کی ڈاؤن لوڈ سیٹنگز اپ ڈیٹ ہو گئیں۔',
  },
  profile: {
    welcomePrefix: 'خوش آمدید،',
    accountSection: 'اکاؤنٹ کی معلومات',
    appSection: 'ایپلیکیشن کی معلومات',
    actionsSection: 'فوری اقدامات',
    actionsDescription: 'اکاؤنٹ کی ترجیحات منظم کریں',
    emptyTitle: 'پروفائل دستیاب نہیں',
    emptyDescription:
      'اکاؤنٹ کی تفصیلات نہیں ملیں۔ نیچے کھینچ کر تازہ کریں یا دوبارہ کوشش کریں۔',
    comingSoon: 'جلد آ رہا ہے',
    editSuccessTitle: 'پروفائل اپ ڈیٹ ہو گیا',
    editSuccessMessage: 'تبدیلیاں محفوظ ہیں اور VidoraX پر سنک ہو گئی ہیں۔',
    editProfile: 'پروفائل میں ترمیم',
    editProfileSubtitle: 'نام اور تصویر اپ ڈیٹ کریں',
    editProfileHint: 'پروفائل میں ترمیم کی اسکرین کھولتا ہے',
    changePassword: 'پاس ورڈ تبدیل کریں',
    changePasswordSubtitle: 'اپنا اکاؤنٹ محفوظ رکھیں',
    changePasswordHint: 'اس ریلیز میں پاس ورڈ تبدیل کرنا دستیاب نہیں',
    privacy: 'پرائیویسی',
    privacySubtitle: 'VidoraX آپ کی معلومات کیسے سنبھالتا ہے',
    privacyHint: 'پرائیویسی اسکرین کھولتا ہے',
    about: 'تعارف',
    aboutSubtitle: 'ایپ کی معلومات اور قانونی تفصیلات',
    aboutHint: 'تعارف اسکرین کھولتا ہے',
    appVersion: 'ایپ ورژن',
    buildVersion: 'بلڈ ورژن',
    environment: 'ماحول',
    environmentDevelopment: 'ڈویلپمنٹ',
    platform: 'پلیٹ فارم',
    appSectionDescription: 'بلڈ اور رن ٹائم کی تفصیلات',
    avatarSheetTitle: 'پروفائل تصویر',
    avatarSheetSubtitle: 'تصویر اپ ڈیٹ کرنے کا طریقہ منتخب کریں',
    takePhoto: 'تصویر لیں',
    chooseFromLibrary: 'لائبریری سے منتخب کریں',
    removePhoto: 'تصویر ہٹائیں',
    removeConfirmTitle: 'پروفائل تصویر ہٹائیں؟',
    removeConfirmMessage: 'تصویر حذف ہو جائے گی اور آپ کے ابتدائی حروف دکھائی دیں گے۔',
    opening: 'کھل رہا ہے…',
    optimizing: 'تصویر بہتر ہو رہی ہے…',
    uploading: 'اپ لوڈ ہو رہی ہے',
    removing: 'تصویر ہٹائی جا رہی ہے…',
    cancelUpload: 'اپ لوڈ منسوخ',
    retryUpload: 'اپ لوڈ دوبارہ',
    openSettings: 'سیٹنگز کھولیں',
    verified: 'تصدیق شدہ',
    unverified: 'غیر تصدیق شدہ',
    admin: 'ایڈمن',
    memberSince: 'رکنیت {date} سے',
    accountStatus: 'اکاؤنٹ کی حیثیت',
    userId: 'یوزر آئی ڈی',
    a11yProfile: '{name}، {email} کا پروفائل۔ رکنیت {date} سے',
    a11yAdd: 'پروفائل تصویر شامل کریں',
    a11yChange: 'پروفائل تصویر تبدیل کریں',
    a11yHint: 'تصویر لینے، منتخب کرنے، یا ہٹانے کے اختیارات کھولتا ہے۔',
    loadingA11y: 'پروفائل لوڈ ہو رہی ہے',
    fullNameA11y: 'پورا نام',
    retrySaveA11y: 'پروفائل محفوظ کرنا دوبارہ کوشش کریں',
    discardChangesA11y: 'پروفائل تبدیلیاں منسوخ کریں',
    nameLengthHint: 'درکار ہے۔ 2 سے 100 حروف کے درمیان۔',
  },
  history: {
    title: 'ہسٹری',
    searchPlaceholder: 'ہسٹری تلاش کریں',
    emptyTitle: 'براؤزنگ ہسٹری نہیں',
    emptyDescription: 'براؤزر میں کھلے صفحات یہاں نظر آئیں گے۔',
    emptyAction: 'براؤزر کھولیں',
    emptySearchTitle: 'کوئی مماثل صفحہ نہیں',
    emptySearchDescription: 'کوئی اور عنوان، سائٹ، یا URL آزمائیں۔',
    errorTitle: 'ہسٹری لوڈ نہیں ہو سکی',
    clearTitle: 'براؤزنگ ہسٹری صاف کریں؟',
    clearMessage:
      'اس ڈیوائس سے محفوظ شدہ براؤزنگ ہسٹری مستقل طور پر ہٹ جائے گی۔ آپ کی حالیہ تلاشیں رہیں گی۔',
    clearConfirm: 'سب صاف کریں',
    clearCancel: 'منسوخ',
    clearSearches: 'حالیہ تلاشیں صاف کریں',
    clearSearchesHint: 'ایڈریس بار میں لکھی گئی تلاشیں۔ براؤزنگ ہسٹری رہے گی۔',
    clearSearchesTitle: 'حالیہ تلاشیں صاف کریں؟',
    clearSearchesMessage:
      'اس سے ایڈریس بار میں لکھی گئی تلاشیں اس ڈیوائس سے ہٹ جائیں گی اور پھر تجویز نہیں ہوں گی۔ آپ کی براؤزنگ ہسٹری رہے گی۔',
    clearSearchesConfirm: 'تلاشیں صاف کریں',
    deleteTitle: 'یہ صفحہ ہٹائیں؟',
    deleteMessage: 'یہ صفحہ براؤزنگ ہسٹری سے ہٹ جائے گا۔',
    deleteConfirm: 'ہٹائیں',
    deleteCancel: 'منسوخ',
    loadingAnnouncement: 'براؤزنگ ہسٹری لوڈ ہو رہی ہے',
    endOfList: 'آپ سب دیکھ چکے ہیں',
    clearAllA11y: 'ساری براؤزنگ ہسٹری صاف کریں',
    openHint: 'کھولنے کے لیے دو بار ٹیپ کریں',
    removeOnlyHint: 'صرف یہ صفحہ ہسٹری سے ہٹاتا ہے',
    itemA11y: '{title}۔ {url}۔ دیکھا گیا {relative}',
    removeItemA11y: '{title} ہسٹری سے ہٹائیں',
  },
  bookmarks: {
    title: 'بک مارکس',
    searchPlaceholder: 'بک مارکس تلاش کریں',
    emptyTitle: 'ابھی کوئی بک مارک نہیں',
    emptyDescription: 'براؤز کرتے ہوئے بک مارک آئیکن دبا کر صفحات محفوظ کریں۔',
    emptyAction: 'براؤزر کھولیں',
    emptySearchTitle: 'کوئی مماثل بک مارک نہیں',
    emptySearchDescription: 'کوئی اور عنوان، سائٹ، یا URL آزمائیں۔',
    errorTitle: 'بک مارکس لوڈ نہیں ہو سکے',
    clearTitle: 'تمام بک مارکس صاف کریں؟',
    clearMessage:
      'اس ڈیوائس سے ہر محفوظ بک مارک مستقل طور پر ہٹ جائے گا۔',
    clearConfirm: 'سب صاف کریں',
    clearCancel: 'منسوخ',
    deleteTitle: 'بک مارک ہٹائیں؟',
    deleteMessage: 'یہ صفحہ بک مارکس سے ہٹ جائے گا۔',
    deleteConfirm: 'ہٹائیں',
    deleteCancel: 'منسوخ',
    loadingAnnouncement: 'بک مارکس لوڈ ہو رہے ہیں',
    endOfList: 'آپ سب دیکھ چکے ہیں',
    toggleFailed: 'بک مارک اپ ڈیٹ نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    clearAllA11y: 'سارے بک مارکس صاف کریں',
    bookmarkedA11y: 'بک مارک شدہ',
    openHint: 'کھولنے کے لیے دو بار ٹیپ کریں',
    removeOnlyHint: 'صرف یہ بک مارک ہٹاتا ہے',
    itemA11y: '{title}۔ {url}۔ بک مارک {date}',
    removeItemA11y: '{title} بک مارکس سے ہٹائیں',
  },
  favorites: {
    title: 'فیوریٹس',
    searchPlaceholder: 'فیوریٹس تلاش کریں',
    emptyTitle: 'ابھی کوئی فیوریٹ نہیں',
    emptyDescription: 'ڈاؤن لوڈ کی تفصیل سے پسندیدہ ڈاؤن لوڈز محفوظ کریں۔',
    emptyAction: 'ڈاؤن لوڈز کھولیں',
    emptySearchTitle: 'کوئی فیوریٹ نہیں ملا',
    emptySearchDescription: 'کوئی اور عنوان یا URL آزمائیں۔',
    errorTitle: 'فیوریٹس لوڈ نہیں ہو سکے',
    removeTitle: 'فیوریٹ ہٹائیں؟',
    removeMessage: 'یہ آئٹم فیوریٹس سے ہٹ جائے گا۔',
    removeConfirm: 'ہٹائیں',
    removeCancel: 'منسوخ',
    unavailableTitle: 'ڈاؤن لوڈ دستیاب نہیں',
    unavailableDescription:
      'اصل ڈاؤن لوڈ اب دستیاب نہیں۔ آپ یہ فیوریٹ ہٹا سکتے ہیں۔',
    unavailableAction: 'فیوریٹ ہٹائیں',
    loadingAnnouncement: 'فیوریٹس لوڈ ہو رہے ہیں',
    endOfList: 'آپ سب دیکھ چکے ہیں',
    toggleFailed: 'فیوریٹ اپ ڈیٹ نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    openFailed: 'یہ فیوریٹ نہیں کھل سکا۔',
    favoritedA11y: 'فیوریٹ',
    removeOnlyHint: 'صرف یہ فیوریٹ ہٹاتا ہے',
    itemA11y: '{title}۔ فیوریٹ۔ {meta}',
    itemUnavailableA11y: '{title}۔ فیوریٹ۔ ڈاؤن لوڈ دستیاب نہیں۔',
    openHint: 'ڈاؤن لوڈ کی تفصیل کھولنے کے لیے دو بار ٹیپ کریں',
    unavailableHint: 'اختیارات کے لیے دو بار ٹیپ کریں۔ ہٹانے کے لیے دیر تک دبائیں۔',
    removeItemA11y: '{title} فیوریٹس سے ہٹائیں',
    downloadUnavailableLabel: 'ڈاؤن لوڈ دستیاب نہیں',
  },
  watchHistory: {
    title: 'واچ ہسٹری',
    emptyTitle: 'ابھی واچ ہسٹری نہیں',
    emptyDescription: 'جو ویڈیوز آپ چلائیں گے وہ یہاں نظر آئیں گی۔',
    missing: 'اب اس ڈیوائس پر نہیں',
    errorTitle: 'واچ ہسٹری لوڈ نہیں ہو سکی',
    offlineHint: 'اس ڈیوائس پر محفوظ واچ پیش رفت دکھائی جا رہی ہے۔',
    watchProgressA11y: 'واچ پیش رفت',
  },
  about: {
    title: 'تعارف',
    description: 'VidoraX، ورژن، اور قانونی تفصیلات کے بارے میں جانیں۔',
    a11y: 'تعارف اسکرین',
    versionLabel: 'ورژن {version}',
    versionBuildLabel: 'ورژن {version} (بلڈ {build})',
    tagline: 'براؤزر اور ویڈیو ڈاؤن لوڈر',
    productDescription:
      'VidoraX ایک اینڈرائیڈ پر مرکوز براؤزر، میڈیا، اور ڈاؤن لوڈ مینیجر ہے۔ سپورٹ شدہ ڈاؤن لوڈ ایبل میڈیا منظم کریں اور چلائیں جسے محفوظ کرنے کی آپ کو اجازت ہے — ہر سائٹ یا ویڈیو ڈاؤن لوڈ نہیں ہوتی، اور DRM یا انکرپٹڈ مواد سپورٹ نہیں ہے۔',
    identityA11y: 'VidoraX۔ براؤزر اور ویڈیو ڈاؤن لوڈر۔ ورژن {version}، بلڈ {build}۔',
    logoA11y: 'VidoraX لوگو',
    appInformation: 'ایپ کی معلومات',
    appSection: 'ایپ',
    version: 'ورژن',
    build: 'بلڈ',
    platform: 'پلیٹ فارم',
    checkForUpdates: 'اپڈیٹس چیک کریں',
    checkForUpdatesA11y: 'دستیاب اپڈیٹس دیکھنے کے لیے پلے اسٹور لسٹنگ کھولتا ہے',
    updateIdleDescription: 'جب لسٹنگ دستیاب ہو تو پلے اسٹور پر اپڈیٹس دیکھیں۔',
    updateChecking: 'پلے اسٹور کھولا جا رہا ہے…',
    updateOpenedStore: 'پلے اسٹور کھل گیا تاکہ آپ اپڈیٹس دیکھ سکیں۔',
    updateFailed: 'پلے اسٹور نہیں کھل سکا۔ بعد میں دوبارہ کوشش کریں۔',
    updateUnavailableDescription:
      'پلے اسٹور لسٹنگ شائع ہونے کے بعد اپڈیٹ چیک دستیاب ہوگا۔',
    updateUnavailableA11y: 'اپڈیٹ چیک ابھی دستیاب نہیں',
    rateVidoraX: 'VidoraX\u200E کو ریٹ کریں',
    rateDescription: 'پلے اسٹور پر VidoraX کو ریٹ کریں',
    rateA11y: 'ریٹنگ دینے کے لیے VidoraX پلے اسٹور لسٹنگ کھولتا ہے',
    rateUnavailableDescription:
      'پلے اسٹور لسٹنگ شائع ہونے کے بعد ریٹنگ دستیاب ہوگی۔',
    rateUnavailableA11y: 'ریٹنگ ابھی دستیاب نہیں',
    openSourceLicenses: 'اوپن سورس لائسنسز',
    helpLegal: 'مدد اور قانونی',
    helpSupport: 'مدد اور سپورٹ',
    helpSupportDescription: 'مدد کے موضوعات اور عام سوالات دیکھیں',
    helpSupportA11y: 'مدد اور سپورٹ کھولتا ہے',
    privacyPolicy: 'پرائیویسی پالیسی',
    privacyDescription: 'VidoraX اس ڈیوائس پر معلومات کیسے سنبھالتا ہے',
    privacyA11y: 'پرائیویسی پالیسی کھولتا ہے',
    privacy: 'پرائیویسی',
    termsConditions: 'شرائط و ضوابط',
    termsDescription: 'VidoraX استعمال کی شرائط',
    termsA11y: 'شرائط و ضوابط کھولتا ہے',
    terms: 'شرائط',
    support: 'مدد',
    copyrightLine: '© {year} {brand}',
    allRightsReserved: 'جملہ حقوق محفوظ ہیں۔',
    copyrightA11y: 'کاپی رائٹ {year} {brand}۔ جملہ حقوق محفوظ ہیں۔',
  },
  support: {
    title: 'مدد اور سپورٹ',
    description:
      'مدد کے موضوعات تلاش کریں، زمرے دیکھیں، اور ڈاؤن لوڈز، پلیئر ٹیب، پلے بیک، اور سیٹنگز کے جوابات حاصل کریں — سب آف لائن دستیاب۔',
    a11y: 'مدد اور سپورٹ اسکرین',
    searchPlaceholder: 'مدد تلاش کریں',
    searchA11y: 'مدد کے مضامین تلاش کریں',
    searchHint: 'لکھتے ہی مدد کے مضامین فلٹر ہوتے ہیں',
    clearSearchA11y: 'تلاش صاف کریں',
    categoriesHeading: 'زمرے',
    popularHeading: 'عام سوالات',
    resultsHeading: 'تلاش کے نتائج',
    categoryFaqsHeading: 'سوالات',
    noResultsTitle: 'کوئی مدد مضمون نہیں ملا',
    noResultsDescription: 'کوئی اور لفظ آزمائیں، یا نیچے سے کوئی زمرہ دیکھیں۔',
    showAllCategories: 'تمام زمرے',
    showAllCategoriesA11y: 'تمام مدد کے زمرے دکھائیں',
    expandA11y: 'جواب کھولتا ہے',
    collapseA11y: 'جواب بند کرتا ہے',
    faqExpandedHint: 'کھلا ہوا',
    faqCollapsedHint: 'بند',
    privacyHeading: 'پرائیویسی',
    privacyQuestions: 'پرائیویسی سوالات',
    privacyQuestionsHint: 'اِن‑ایپ پرائیویسی پالیسی کھولیں',
    privacyQuestionsA11y: 'پرائیویسی سوالات کے لیے پرائیویسی پالیسی کھولتا ہے',
    deletionRequest: 'مقامی ڈیٹا حذف',
    deletionRequestHint: 'پرائیویسی پالیسی میں مقامی ڈیٹا کے ذخیرہ اور حذف کا طریقہ دیکھیں',
    deletionRequestA11y: 'مقامی ڈیٹا حذف کی معلومات کے لیے پرائیویسی پالیسی کھولتا ہے',
    emailContact: 'ای میل سپورٹ',
    emailContactHint: '{email} پر پیغام بھیجیں',
    emailContactA11y: 'سپورٹ سے رابطے کے لیے ای میل ایپ کھولتا ہے',
    supportActionsHeading: 'مدد حاصل کریں',
    contactSupport: 'سپورٹ سے رابطہ کریں',
    contactSupportHint: 'VidoraX ٹیم سے مدد حاصل کریں',
    contactSupportA11y: 'سپورٹ رابطے کے اختیارات کھولتا ہے',
    reportProblem: 'مسئلہ رپورٹ کریں',
    reportProblemHint: 'VidoraX ٹیم کو تکنیکی مسئلہ بتائیں',
    reportProblemA11y: 'مسئلہ رپورٹ فارم کھولتا ہے',
    contactUnavailableTitle: 'سپورٹ رابطہ ابھی دستیاب نہیں ہے۔',
    contactUnavailableDescription: 'اس بلڈ کے لیے سپورٹ ای میل ترتیب نہیں دی گئی۔',
    getHelp: 'مدد حاصل کریں',
    getHelpA11y: 'اس مسئلے میں مدد حاصل کریں',
    getHelpHint: 'اس مسئلے سے متعلق مددگار مضامین کھولتا ہے',
    contextualHeading: 'متعلقہ مدد',
    report: {
      title: 'مسئلہ رپورٹ کریں',
      a11y: 'مسئلہ رپورٹ فارم',
      categoryLabel: 'مسئلے کی قسم',
      categoryPlaceholder: 'قسم منتخب کریں',
      categorySelectedA11y: 'مسئلے کی قسم: {selected}',
      subjectLabel: 'موضوع',
      subjectPlaceholder: 'مسئلے کا مختصر خلاصہ',
      descriptionLabel: 'تفصیل',
      descriptionPlaceholder: 'کیا ہوا اور اسے دوبارہ کیسے پیدا کریں یہ بیان کریں',
      includeDiagnostics: 'تکنیکی تفصیلات شامل کریں',
      diagnosticsHint: 'تحقیق میں مدد کے لیے ورژن، OS، اور ڈیوائس کی معلومات شامل کرتا ہے',
      diagnosticsExpanded: 'تکنیکی تفصیلات',
      send: 'رپورٹ بھیجیں',
      sending: 'بھیجا جا رہا ہے\u2026',
      successTitle: 'رپورٹ تیار ہے',
      successDescription:
        'آپ کی ای میل ایپ کھل گئی ہے۔ براہ کرم وہاں سے رپورٹ کا جائزہ لیں اور بھیجیں۔',
      failureTitle: 'رپورٹ نہیں بھیجی جا سکی',
      failureDescription: 'دوبارہ کوشش کریں۔',
      retry: 'دوبارہ کوشش کریں',
      unavailableTitle: 'سپورٹ رابطہ ترتیب نہیں دیا گیا',
      unavailableDescription:
        'سپورٹ رابطہ ترتیب نہیں دیا گیا۔ آپ کی رپورٹ جمع نہیں ہوئی۔',
      privacyNote: 'تکنیکی تفصیلات ہماری پرائیویسی پالیسی کے مطابق شیئر کی جاتی ہیں۔',
      openPrivacy: 'پرائیویسی پالیسی',
      categories: {
        download: 'ڈاؤن لوڈ کا مسئلہ',
        browser: 'براؤزر کا مسئلہ',
        playback: 'پلے بیک کا مسئلہ',
        file: 'فائل / لائبریری کا مسئلہ',
        account: 'ایپ کا مسئلہ',
        other: 'دیگر',
      },
      validation: {
        categoryRequired: 'براہ کرم مسئلے کی قسم منتخب کریں',
        subjectRequired: 'براہ کرم موضوع درج کریں',
        subjectTooShort: 'موضوع کم از کم ۵ حروف کا ہونا چاہیے',
        subjectTooLong: 'موضوع ۱۲۰ حروف یا کم ہونا چاہیے',
        descriptionRequired: 'براہ کرم مسئلے کی تفصیل بیان کریں',
        descriptionTooShort: 'تفصیل کم از کم ۲۰ حروف کی ہونی چاہیے',
        descriptionTooLong: 'تفصیل ۲۰۰۰ حروف یا کم ہونی چاہیے',
      },
    },
    categories: {
      gettingStarted: {
        title: 'شروعات',
        description: 'براؤزر، ڈاؤن لوڈز، اور پلے بیک کی بنیادی باتیں',
      },
      downloads: {
        title: 'ڈاؤن لوڈز',
        description: 'ناکامیاں، توقف، Wi-Fi، اور غیر معاون ذرائع',
      },
      libraryFiles: {
        title: 'پلیئر اور فائلیں',
        description: 'نام تبدیل، حذف، شیئر، فیوریٹس، اور فولڈرز',
      },
      playback: {
        title: 'پلے بیک',
        description: 'میڈیا چلانا، کوڈیکس، ریزیوم، اور فل سکرین',
      },
      accountSettings: {
        title: 'سیٹنگز',
        description: 'زبان، تھیم، اور اسٹوریج',
      },
    },
    actions: {
      openBrowser: 'براؤزر کھولیں',
      openDownloads: 'ڈاؤن لوڈز کھولیں',
      openLibrary: 'پلیئر کھولیں',
      openDownloadSettings: 'ڈاؤن لوڈ سیٹنگز کھولیں',
      openSettings: 'سیٹنگز کھولیں',
      openPrivacy: 'پرائیویسی پالیسی کھولیں',
      manageStorage: 'اسٹوریج منظم کریں',
      openLanguageSettings: 'زبان کی سیٹنگز کھولیں',
      openAppearanceSettings: 'ظاہری شکل کی سیٹنگز کھولیں',
    },
    faq: {
      howToDownload: {
        question: 'ویڈیو کیسے ڈاؤن لوڈ کروں؟',
        answer:
          'براؤزر کھولیں اور ویڈیو والے صفحے پر جائیں، یا اس کا لنک ایڈریس بار میں پیسٹ کریں۔ جب “ویڈیو دستیاب” نظر آئے تو اس پر ٹیپ کریں، اگر معیار کے اختیارات ہوں تو ایک منتخب کریں، اور پیش رفت ڈاؤن لوڈز میں دیکھیں۔ ہر ویب سائٹ یا ویڈیو ڈاؤن لوڈ نہیں ہوتی — YouTube، DRM‑محفوظ، انکرپٹڈ اور لائیو ویڈیوز مسترد کی جاتی ہیں۔',
        keywords: 'ڈاؤن لوڈ، محفوظ، ویڈیو، معیار، براؤزر',
      },
      howToUseBrowser: {
        question: 'براؤزر کیسے استعمال کروں؟',
        answer:
          'مرکزی ٹیبز سے براؤزر کھولیں۔ ایڈریس بار میں URL لکھیں یا تلاش کریں، صفحات دیکھیں، اور براؤزر مینو سے بُک مارکس یا ہسٹری کھولیں۔ کسی لنک پر دیر تک دبائیں تو اسے کاپی، شیئر یا کسی دوسرے براؤزر میں کھول سکتے ہیں۔ اِن‑ایپ براؤزر نیویگیشن اور معاون میڈیا پہچان کے لیے ہے — یہ دعویٰ نہیں کہ ہر سائٹ ایک جیسا کام کرتی ہے۔',
        keywords: 'براؤزر، url، ایڈریس بار، ٹیبز، بُک مارکس',
      },
      whereDownloadsAppear: {
        question: 'ڈاؤن لوڈز کہاں نظر آتے ہیں؟',
        answer:
          'جاری اور حالیہ منتقلیاں ڈاؤن لوڈز میں نظر آتی ہیں — قطار میں، روکی ہوئی، ناکام، اور مکمل۔ مکمل ویڈیوز پلیئر ٹیب میں بھی آتی ہیں جہاں آپ انہیں تلاش، فلٹر اور آف لائن چلا سکتے ہیں، اور عام طور پر ان کی ایک کاپی فون کی گیلری میں بھی محفوظ ہو جاتی ہے (اسے ڈاؤن لوڈ سیٹنگز → گیلری میں محفوظ کریں سے بند کریں)۔ منتقلی کی حالت کے لیے ڈاؤن لوڈز اور محفوظ ویڈیوز کے لیے پلیئر ٹیب استعمال کریں۔',
        keywords: 'ڈاؤن لوڈز، لائبریری، قطار، مکمل، کہاں',
      },
      howToPlayDownloaded: {
        question: 'ڈاؤن لوڈ شدہ میڈیا کیسے چلاؤں؟',
        answer:
          'VidoraX پلیئر کھولنے کے لیے پلیئر ٹیب میں کسی ویڈیو پر ٹیپ کریں، یا ڈاؤن لوڈز میں مکمل آئٹم کھول کر چلائیں منتخب کریں۔ پلے بیک کے لیے فائل ڈیوائس پر موجود ہونی چاہیے اور فارمیٹ آپ کی ڈیوائس ڈیکوڈ کر سکے۔ اگر فائل حذف ہو یا کوڈیک غیر معاون ہو تو VidoraX خرابی دکھائے گا، ویڈیو نہیں چلائے گا۔',
        keywords: 'چلائیں، پلیئر، لائبریری، آف لائن، دیکھیں',
      },
      downloadFailed: {
        question: 'میرا ڈاؤن لوڈ کیوں ناکام ہوا؟',
        answer:
          'ڈاؤن لوڈ نیٹ ورک ٹوٹنے، ذریعہ فائل تبدیل/بلاک کرنے، اسٹوریج بھر جانے، میڈیا ماخذ ریزیوم نہ دینے، یا میڈیا DRM/انکرپٹڈ/غیر معاون ہونے پر ناکام ہو سکتا ہے۔ ناکام آئٹم ڈاؤن لوڈز میں کھول کر خرابی پڑھیں، پھر اگر ذریعہ دستیاب ہو تو دوبارہ کوشش کریں۔ صرف Wi-Fi سیٹنگ بھی Wi-Fi آنے تک آغاز روک سکتی ہے۔',
        keywords: 'ناکام، خرابی، دوبارہ، نیٹ ورک، اسٹوریج',
      },
      pauseAndResume: {
        question: 'کیا ڈاؤن لوڈز روک کر پھر جاری کر سکتا ہوں؟',
        answer:
          'جی ہاں۔ ڈاؤن لوڈز میں چلتے ڈاؤن لوڈ پر توقف دبائیں اور جب چاہیں جاری رکھیں دبائیں — یہ ویڈیو فائلوں اور HLS اور DASH سٹریمز دونوں کے لیے کام کرتا ہے۔ سٹریم آخری مکمل حصے کے بعد سے جاری ہوتی ہے؛ فائل پہلے سے محفوظ بائٹس کے بعد سے جاری ہوتی ہے، سوائے اس کے کہ اس کا ماخذ ادھوری فائل جاری کرنے سے انکار کرے (کچھ سوشل سائٹس کے عارضی لنکس)، تب وہ صفر سے دوبارہ شروع ہوتی ہے۔ جو ڈاؤن لوڈ کنکشن ٹوٹنے، Android کے ایپ بند کرنے یا فون ری اسٹارٹ ہونے سے رکے وہ خود جاری ہو جاتا ہے؛ جسے آپ نے روکا ہو وہ تب تک رکا رہتا ہے جب تک آپ جاری رکھیں نہ دبائیں۔',
        keywords: 'توقف، جاری، HLS، DASH، سٹریم، خودکار جاری',
      },
      wifiOnlyDownloads: {
        question: 'صرف Wi-Fi کیسے کام کرتا ہے؟',
        answer:
          'سیٹنگز → ڈاؤن لوڈ سیٹنگز میں “صرف Wi-Fi پر ڈاؤن لوڈ” آن کریں تاکہ ڈاؤن لوڈز Wi-Fi دستیاب ہونے تک انتظار کریں۔ جو ڈاؤن لوڈ چلتے ہوئے Wi-Fi کھو دے وہ بھی انتظار کرتا ہے۔ جب تک Wi-Fi واپس نہ آئے یا آپ سیٹنگ بند نہ کریں، ان ڈاؤن لوڈز کے لیے موبائل ڈیٹا استعمال نہیں ہو گا۔',
        keywords: 'wifi، wi-fi، سیلولر، ڈیٹا، سیٹنگز',
      },
      fileUnavailable: {
        question: 'فائل دستیاب کیوں نہیں؟',
        answer:
          'مکمل ڈاؤن لوڈ کے لیے مقامی فائل ایپ اسٹوریج میں ہونی چاہیے۔ اگر فائل ہٹا دی گئی، اسٹوریج صاف ہوا، یا جزوی فائل غائب ہے تو VidoraX اسے کھول، شیئر، یا چلا نہیں سکتا۔ اگر میڈیا اب بھی دستیاب ہو تو معاون ذریعے سے دوبارہ ڈاؤن لوڈ کریں۔',
        keywords: 'غائب، دستیاب نہیں، حذف، اسٹوریج، فائل',
      },
      unsupportedSource: {
        question: 'ذریعہ غیر معاون کیوں ہے؟',
        answer:
          'VidoraX صرف وہ معاون، غیر DRM ذرائع ڈاؤن لوڈ کرتا ہے جنہیں قانونی اور تکنیکی طور پر پروسیس کر سکے۔ YouTube، انکرپٹڈ HLS، DRM‑محفوظ میڈیا، لائیو سٹریمز، اور کچھ سائٹ تحفظات واضح پیغام کے ساتھ روکے جاتے ہیں۔ ہر ویب سائٹ کام نہیں کرتی — غیر معاون پیغام کا مطلب ہے کہ وہ ذریعہ VidoraX میں ڈاؤن لوڈ نہیں ہو سکتا۔',
        keywords: 'غیر معاون، DRM، انکرپٹڈ، HLS، لائیو',
      },
      renameMedia: {
        question: 'میڈیا کا نام کیسے تبدیل کروں؟',
        answer:
          'ڈاؤن لوڈز میں مکمل آئٹم کھولیں، اوپر مینو پر ٹیپ کر کے فائل کے اختیارات کھولیں، اور نام تبدیل کریں منتخب کریں۔ اس سے VidoraX میں دکھائی دینے والا نام بدلتا ہے۔ نام تبدیل کرنے سے غیر معاون فارمیٹ درست نہیں ہوتا اور غائب فائل واپس نہیں آتی۔',
        keywords: 'نام، تبدیل، ڈسپلے نام، ترمیم',
      },
      deleteMedia: {
        question: 'میڈیا کیسے حذف کروں؟',
        answer:
          'پلیئر ٹیب میں کسی ویڈیو پر دیر تک دبائیں اور VidoraX سے حذف کریں منتخب کریں، یا اسے ڈاؤن لوڈز میں کھول کر فائل کے اختیارات میں حذف کریں منتخب کریں۔ اس سے فائل اس ڈیوائس پر VidoraX سے ہٹ جاتی ہے؛ گیلری میں پہلے سے محفوظ کاپی وہیں رہتی ہے۔ VidoraX کے اندر یہ واپس نہیں کیا جا سکتا۔',
        keywords: 'حذف، ہٹائیں، مٹائیں، اسٹوریج',
      },
      shareMedia: {
        question: 'ڈاؤن لوڈ شدہ فائل کیسے شیئر کروں؟',
        answer:
          'پلیئر ٹیب میں کسی ویڈیو پر دیر تک دبائیں، یا ڈاؤن لوڈز میں مکمل آئٹم کے فائل کے اختیارات کھولیں، اور شیئر منتخب کریں۔ VidoraX مقامی فائل سسٹم شیئر شیٹ کو دیتا ہے۔ شیئر کے لیے فائل ڈیوائس پر موجود ہونی چاہیے۔',
        keywords: 'شیئر، بھیجیں، ایکسپورٹ، شیٹ',
      },
      openExternally: {
        question: 'فائل دوسری ایپ میں کیسے کھولوں؟',
        answer:
          'پلیئر ٹیب میں کسی ویڈیو پر دیر تک دبا کر اس سے کھولیں… منتخب کریں، یا مکمل ڈاؤن لوڈ کے فائل کے اختیارات میں کھولیں منتخب کریں۔ VidoraX سسٹم سے کہتا ہے کہ مقامی فائل کوئی دوسری ایپ کھولے اگر دستیاب ہو۔ اگر مناسب ایپ نہ ہو تو اس کی بجائے شیئر استعمال کریں۔',
        keywords: 'کھولیں، بیرونی، دوسری ایپ',
      },
      favorites: {
        question: 'فیوریٹس کیسے کام کرتے ہیں؟',
        answer:
          'ڈاؤن لوڈز میں مکمل آئٹم کھولیں اور اوپر دل کے نشان پر ٹیپ کر کے اسے فیوریٹ بنائیں۔ فیوریٹس پلیئر ٹیب کے فیوریٹس فلٹر اور فیوریٹس فہرست میں نظر آتے ہیں تاکہ اہم آئٹمز جلدی ملیں۔ فیوریٹ کرنا دوبارہ ڈاؤن لوڈ نہیں کرتا اور حذف سے نہیں بچاتا۔',
        keywords: 'فیوریٹ، ستارہ، فلٹر، لائبریری',
      },
      folders: {
        question: 'فولڈرز کیسے کام کرتے ہیں؟',
        answer:
          'ڈاؤن لوڈز میں مکمل آئٹم کھولیں اور اس کی فولڈر والی قطار پر ٹیپ کر کے اسے کسی فولڈر میں منتقل کریں — وہیں فولڈر بنا، نام بدل اور حذف بھی کر سکتے ہیں۔ پلیئر ٹیب میں فولڈر فلٹر ایک فولڈر کی ویڈیوز دکھاتا ہے۔ فولڈرز صرف اس ڈیوائس پر میڈیا کو گروپ کرتے ہیں؛ یہ کلاؤڈ ڈرائیو کی طرح سنک نہیں ہوتے اور فائلیں منتقل نہیں کرتے۔',
        keywords: 'فولڈر، منظم، منتقل، گروپ',
      },
      videoNotPlaying: {
        question: 'ویڈیو کیوں نہیں چل رہی؟',
        answer:
          'یقینی بنائیں ڈاؤن لوڈ مکمل ہے اور مقامی فائل موجود ہے، پھر اسے پلیئر ٹیب یا ڈاؤن لوڈز سے چلائیں۔ اگر فائل غائب ہو، فارمیٹ/کوڈیک اس ڈیوائس پر غیر معاون ہو، یا پلیئر ڈیوائس خرابی دے تو پلے بیک ناکام ہو سکتا ہے۔ اس سے کھولیں یا شیئر سے کوئی دوسری ایپ صرف تب آزمائیں جب آپ کے پاس موافق پلیئر ایپ ہو۔',
        keywords: 'چلنا، خراب، کالے پردے، خرابی، پلیئر',
      },
      unsupportedCodec: {
        question: 'اگر کوڈیک غیر معاون ہو تو کیا؟',
        answer:
          'VidoraX وہ فارمیٹس چلاتا ہے جو آپ کی ڈیوائس ڈیکوڈ کر سکے۔ کچھ کنٹینرز یا کوڈیکس (یا ان کا امتزاج) ڈاؤن لوڈ ہو سکتے ہیں مگر بلٹ اِن پلیئر میں ناکام رہیں۔ یہ ڈیوائس کی حد ہے — VidoraX یہ دعویٰ نہیں کرتا کہ ہر ڈاؤن لوڈ شدہ فائل ہر جگہ چلے گی۔ آپ Open/Share سے ایسی ایپ آزما سکتے ہیں جو اس کوڈیک کو سپورٹ کرے۔',
        keywords: 'کوڈیک، فارمیٹ، غیر معاون میڈیا، ڈیکوڈ',
      },
      resumePlayback: {
        question: 'کیا پلے بیک وہیں سے جاری ہوتا ہے جہاں چھوڑا تھا؟',
        answer:
          'اہل ناتمام واچز کے لیے ہاں۔ جب آپ VidoraX پلیئر میں میڈیا دوبارہ کھولتے ہیں تو اگر اس ڈیوائس پر ریزیوم ریکارڈ موجود ہو تو پلے بیک خود محفوظ پوزیشن پر جا سکتا ہے۔ بہت مختصر واچز یا صاف شدہ ہسٹری شروع سے چل سکتی ہے۔',
        keywords: 'ریزیوم، جاری، پوزیشن، واچ ہسٹری',
      },
      fullscreenOrientation: {
        question: 'فل سکرین اور اورینٹیشن کیسے کام کرتے ہیں؟',
        answer:
          'پلیئر میں فل سکرین کنٹرول سے فل سکرین میں داخل یا باہر ہوں۔ معاون ڈیوائسز پر اورینٹیشن پلیئر کے فل سکرین لائف سائیکل کے مطابق ہوتا ہے۔ سسٹم سیٹنگز میں روٹیشن لاک خودکار اورینٹیشن کو محدود کر سکتا ہے۔',
        keywords: 'فل سکرین، لینڈسکیپ، پورٹریٹ، گھمائیں',
      },
      loginAccount: {
        question: 'کیا اکاؤنٹ ضروری ہے؟',
        answer:
          'نہیں۔ VidoraX لاگ اِن، پاس ورڈ، یا کلاؤڈ اکاؤنٹ استعمال نہیں کرتا۔ ڈاؤن لوڈز، فولڈرز، فیوریٹس، ہسٹری، بُک مارکس، پلے بیک پیش رفت، اور سیٹنگز اس ڈیوائس پر رہتی ہیں۔ انسٹال کے بعد آپ سائن اِن کیے بغیر ایپ استعمال کر سکتے ہیں۔',
        keywords: 'لاگ اِن، سائن اِن، اکاؤنٹ، پروفائل، پاس ورڈ',
      },
      languageSettings: {
        question: 'زبان کیسے تبدیل کروں؟',
        answer:
          'سیٹنگز → زبان کھولیں اور English یا اردو منتخب کریں۔ ایپ لیبلز، مدد کا مواد، اور اردو کے لیے RTL لے آؤٹ اپ ڈیٹ کرتی ہے بغیر دوبارہ انسٹال کیے۔ VidoraX، فائل ایکسٹینشنز، اور کوڈیک نام جہاں مناسب ہوں ویسے ہی رہتے ہیں۔',
        keywords: 'زبان، english، urdu، اردو، لوکیل',
      },
      themeSettings: {
        question: 'تھیم کیسے تبدیل کروں؟',
        answer:
          'سیٹنگز → ظاہری شکل → تھیم کھولیں اور سسٹم، ریڈ یا ڈارک منتخب کریں۔ ریڈ، یعنی VidoraX کے اپنے رنگ، پہلے سے منتخب ہوتا ہے؛ سسٹم سادہ روشن انداز ہے اور ڈارک گہرا۔ تھیم مدد اور سپورٹ سمیت پوری ایپ پر لاگو ہوتا ہے۔',
        keywords: 'تھیم، ریڈ، ڈارک، لائٹ، ظاہری شکل، سسٹم',
      },
      storageSettings: {
        question: 'اسٹوریج کیسے منظم کروں؟',
        answer:
          'ڈاؤن لوڈ شدہ ویڈیوز VidoraX ایپ کے اندر اسٹوریج استعمال کرتی ہیں۔ سیٹنگز → اسٹوریج → اسٹوریج منظم کریں دکھاتا ہے کہ VidoraX کتنی جگہ استعمال کر رہا ہے؛ وہاں کیش صاف کریں صرف عارضی فائلیں ہٹاتا ہے۔ جگہ خالی کرنے کے لیے پلیئر ٹیب میں غیر ضروری ویڈیوز پر دیر تک دبائیں اور VidoraX سے حذف کریں منتخب کریں۔ ایپ ان انسٹال کرنے سے VidoraX کی اپنی فائلیں ہٹ جاتی ہیں؛ گیلری میں محفوظ کاپیاں فون پر رہتی ہیں۔',
        keywords: 'اسٹوریج، جگہ، ڈسک، حذف، منظم',
      },
    },
  },
  legal: {
    effectiveLabel: 'تاریخِ نفاذ: {date}',
    updatedLabel: 'آخری تازہ کاری: {date}',
    listBullet: '•',
    footer: {
      contactTitle: 'رابطہ',
      contactDescription: '{email} پر ای میل',
      contactA11y: 'VidoraX سے رابطے کے لیے ای میل ایپ کھولتا ہے',
      webTitle: 'ویب پر دیکھیں',
      webDescription: 'شائع شدہ ویب ورژن کھولیں',
      webA11y: 'شائع شدہ ویب قانونی صفحہ کھولتا ہے',
      supportTitle: 'مدد اور سپورٹ',
      supportDescription: 'ہیلپ سینٹر، پرائیویسی سوالات، اور حذف کی معلومات',
      supportA11y: 'مدد اور سپورٹ کھولتا ہے',
    },
  },
  privacy: {
    title: 'پرائیویسی پالیسی',
    a11y: 'پرائیویسی پالیسی',
    sections: {
      introduction: {
        heading: '۱۔ تعارف',
        p1: 'یہ پرائیویسی پالیسی بتاتی ہے کہ جب آپ VidoraX موبائل ایپ استعمال کرتے ہیں تو معلومات کیسے پراسیس ہوتی ہیں۔ VidoraX صارف اکاؤنٹ، لاگ اِن، یا پاس ورڈ پیش نہیں کرتا۔',
        p2: 'VidoraX ایک براؤزر، میڈیا، اور ڈاؤن لوڈ مینیجر ہے۔ ڈاؤن لوڈز، فولڈرز، فیوریٹس، ہسٹری، بُک مارکس، پلے بیک پیش رفت، اور سیٹنگز اس ڈیوائس پر محفوظ ہوتی ہیں۔ عام استعمال میں VidoraX اس ڈیٹا کو VidoraX کلاؤڈ اکاؤنٹ سے سنک نہیں کرتا۔ جن تیسری پارٹی سائٹس پر آپ جاتے ہیں وہ عام براؤزنگ اور نیٹ ورک درخواستیں وصول کرتی رہتی ہیں۔',
      },
      informationProcessed: {
        heading: '۲۔ پراسیس ہونے والی معلومات',
        intro:
          'آپ VidoraX کو کیسے استعمال کرتے ہیں اس کے مطابق ہم مندرجہ ذیل اقسام کی معلومات پراسیس کر سکتے ہیں:',
        itemAccount:
          'VidoraX صارف اکاؤنٹ، ای میل، ڈسپلے نام، یا پاس ورڈ جمع نہیں کرتا۔ کوئی VidoraX لاگ اِن شناخت نہیں ہے۔',
        itemAuth:
          'VidoraX کسی VidoraX اکاؤنٹ کے لیے رسائی ٹوکن، ریفریش ٹوکن، یا سائن اِن سیشن نہیں رکھتا۔',
        itemDownloadMeta:
          'ڈاؤن لوڈ اور میڈیا میٹا ڈیٹا — عنوان، ماخذ یو آر ایل، پلیٹ فارم لیبل، تھمب نیل یو آر ایل، فائل نام، سائز، کوالٹی یا ریزولوشن، اسٹیٹس، پیش رفت، اور متعلقہ ڈاؤن لوڈ ریکارڈز جب آپ میڈیا کا تجزیہ یا محفوظ کرتے ہیں۔ یہ میٹا ڈیٹا آپ کی ڈیوائس پر محفوظ ہوتا ہے۔',
        itemLocalMedia:
          'مقامی ڈاؤن لوڈ فائلیں اور کیش — آپ کی ڈیوائس پر VidoraX ایپ اسٹوریج میں محفوظ میڈیا فائلیں، نیز ڈاؤن لوڈز چلانے کے لیے مقامی ٹرانسفر/پیش رفت کی حالت۔ جسمانی میڈیا فائلیں آپ کی ڈیوائس پر رہتی ہیں۔',
        itemBrowser:
          'براؤزر سے متعلق معلومات — صفحہ یو آر ایل، عنوان، ہوسٹ نیم، وزٹ کا وقت، بُک مارکس، حالیہ تلاشیں، اور حالیہ یو آر ایلز جو اس ڈیوائس کی مقامی براؤزر ہسٹری میں رہتی ہیں۔ اِن‑ایپ براؤزر سیشن اس ڈیوائس پر آخری کھلا صفحہ بھی بحال کر سکتا ہے۔',
        itemPlayback:
          'پلے بیک، ہسٹری، اور ریزیوم حالت — واچ پوزیشن، دورانیہ، پیش رفت، تکمیل کے جھنڈے، اور کنٹینیو واچنگ ریکارڈز جو اس ڈیوائس پر مقامی طور پر محفوظ ہوتے ہیں۔ ریزیوم کے لیے VidoraX اکاؤنٹ درکار نہیں۔',
        itemDiagnostics:
          'ڈائگناسٹکس — اس وقت ایپ میں تیسری پارٹی کا اینالیٹکس یا کریش‑رپورٹنگ ایس ڈی کے مربوط نہیں۔ ترقیاتی بلڈز میں ٹربل شوٹنگ کے لیے ڈیوائس پر محدود ڈائگناسٹک پیغامات ہو سکتے ہیں؛ پروڈکشن استعمال یہاں بیان کردہ الگ اینالیٹکس پروڈکٹ پر منحصر نہیں۔',
        itemSettings:
          'ترجیحات اور سیٹنگز — زبان، تھیم، اور ڈاؤن لوڈ سے متعلق ترجیحات جو اس ڈیوائس پر محفوظ ہوتی ہیں۔ وہ VidoraX کلاؤڈ اکاؤنٹ سے سنک نہیں ہوتیں۔',
      },
      howUsed: {
        heading: '۳۔ معلومات کا استعمال',
        intro: 'ہم پراسیس شدہ معلومات اس لیے استعمال کرتے ہیں:',
        itemProvide:
          'بنیادی پروڈکٹ فیچرز فراہم کرنا — براؤزنگ، آپ کی درخواست پر سپورٹ شدہ میڈیا ڈاؤن لوڈ، مقامی پلے بیک، اور اس ڈیوائس پر لائبریری تنظیم۔',
        itemSync:
          'ڈاؤن لوڈز، فولڈرز، فیوریٹس، ہسٹری، بُک مارکس، پلے بیک پیش رفت، اور سیٹنگز کو ایپ بند کر کے دوبارہ کھولنے کے بعد بھی مقامی طور پر دستیاب رکھنا۔',
        itemSecurity:
          'اس ڈیوائس پر ڈاؤن لوڈ، پلے بیک، اور اسٹوریج فیچرز کو قابلِ اعتماد طریقے سے چلانا۔ VidoraX آپ کی شناخت کے لیے لاگ اِن سیشن یا پاس ورڈ استعمال نہیں کرتا۔',
        itemImprove:
          'سروس چلانے کے لیے درکار معلومات کے ذریعے مسائل سمجھنا اور ٹھیک کرنا۔ اس وقت ایپ میں الگ اشتہاری یا تیسری پارٹی اینالیٹکس پروگرام نہیں چل رہا۔',
      },
      backend: {
        heading: '۴۔ نیٹ ورک مواصلت',
        p1: 'VidoraX کو VidoraX اکاؤنٹ کی ضرورت نہیں، اور یہ عام طور پر ڈاؤن لوڈز، فولڈرز، فیوریٹس، ہسٹری، بُک مارکس، پلے بیک، یا سیٹنگز کا کلاؤڈ سنک نہیں کرتا۔ وہ ریکارڈز اس ڈیوائس پر رہتے ہیں۔ عام استعمال کے لیے VidoraX کو اپنے API سرور کی ضرورت نہیں۔',
        p2: 'جب آپ کوئی ویب سائٹ براؤز کرتے ہیں، میڈیا لنک کا تجزیہ کرتے ہیں، یا فائل ڈاؤن لوڈ کرتے ہیں تو VidoraX اس تیسری پارٹی ماخذ کو عام نیٹ ورک درخواستیں بھیجتا ہے۔ پلے بیک پیش رفت مقامی طور پر محفوظ ہوتی ہے اور VidoraX اکاؤنٹ پر اپلوڈ نہیں ہوتی۔',
        p3: 'ڈاؤن لوڈ شدہ میڈیا فائلیں خود آپ کی ڈیوائس پر رہتی ہیں جب تک آپ انہیں اپنے ڈیوائس ٹولز سے شیئر یا منتقل نہ کریں۔ اگر آپ ای میل سے سپورٹ سے رابطہ کریں تو اس پیغام کا مواد صرف اس لیے بھیجا جاتا ہے کہ آپ نے بھیجنے کا انتخاب کیا۔',
      },
      thirdParties: {
        heading: '۵۔ تیسری پارٹی اور سروس فراہم کنندگان',
        p1: 'جب آپ ویب سائٹس براؤز کرتے ہیں یا اِن‑ایپ تلاش جو تیسری پارٹی صفحہ کھولتی ہے استعمال کرتے ہیں، تو وہ فریق اپنی اپنی پالیسیوں کے تحت معلومات پراسیس کرتے ہیں۔ جن سائٹس پر آپ جاتے ہیں ان پر VidoraX کا کنٹرول نہیں۔',
        p2: 'صفحات، تھمب نیلز، یا وہ میڈیا جو آپ خود کھولتے ہیں انہیں لوڈ کرنے کی نیٹ ورک درخواستیں ان تیسری پارٹی ماخذوں تک جاتی رہتی ہیں۔ یہ پالیسی یہ دعویٰ نہیں کرتی کہ براؤزنگ ان سائٹس سے چھپی ہوئی ہے۔',
        p3: 'ایپ ڈیوائس کی سسٹم نوٹیفیکیشنز استعمال کر سکتی ہے (مثلاً ڈاؤن لوڈ سے متعلق الرٹس)۔ اس پالیسی کے مطابق موبائل ایپ میں اس وقت اشتہاری نیٹ ورکس یا تیسری پارٹی اینالیٹکس ایس ڈی کے شامل نہیں۔',
      },
      localStorage: {
        heading: '۶۔ مقامی ڈیوائس اسٹوریج',
        p1: 'آپ کی ڈیوائس پر VidoraX براؤزر ہسٹری و بُک مارکس ڈیٹا بیسز، پلے بیک ریزیوم ریکارڈز، ڈاؤن لوڈ انجن کی حالت، ترجیحات، اور ایپ دستاویز اسٹوریج میں ڈاؤن لوڈ شدہ میڈیا فائلیں رکھ سکتا ہے۔',
        p2: 'ہسٹری صاف کرنا، ڈاؤن لوڈز ہٹانا، یا ایپ ان انسٹال کرنا مقامی ڈیٹا پر ان کارروائیوں کے مطابق اثر ڈالتا ہے۔ ان انسٹال ڈیوائس سے مقامی ایپ ڈیٹا ہٹا دیتا ہے۔ VidoraX صارف اکاؤنٹ کے لیے اس مقامی لائبریری کا الگ کلاؤڈ کاپی نہیں رکھتا۔',
      },
      retention: {
        heading: '۷۔ ڈیٹا برقرار رکھنا',
        p1: 'ہم تمام اقسامِ ڈیٹا کے لیے ایک مقررہ برقرار رکھنے کی مدت شائع نہیں کرتے۔ مقامی معلومات عموماً اس وقت تک رہتی ہیں جب تک آپ اسے صاف نہ کریں، متعلقہ آئٹمز نہ ہٹائیں، یا ایپ ان انسٹال نہ کریں۔',
        p2: 'اگر آپ سپورٹ کو ای میل کریں تو وہ پیغام میل باکس فراہم کنندہ کے طریقوں کے مطابق رکھا جا سکتا ہے۔ درست بیک اپ شیڈولز اس پالیسی میں وعدہ نہیں کیے جاتے۔',
      },
      security: {
        heading: '۸۔ سیکیورٹی احتیاطیں',
        p1: 'VidoraX مقامی، آن‑ڈیوائس ایپ کی نوعیت کے مطابق معقول تکنیکی اور انتظامی اقدامات اپناتا ہے، جن میں ڈاؤن لوڈز اور ترجیحات کا ایپ‑سینڈ باکس اسٹوریج شامل ہے۔',
        p2: 'ٹرانسمیشن یا اسٹوریج کا کوئی طریقہ تمام خطرے ختم نہیں کرتا۔ ہم یہ دعویٰ نہیں کرتے کہ معلومات غیر مجاز رسائی، افشا، تبدیلی، یا تباہی سے محفوظ رہیں گی۔',
      },
      userControls: {
        heading: '۹۔ صارف کنٹرولز اور حقوق',
        intro:
          'آپ کی ڈیوائس کے مطابق VidoraX ایسے اِن‑ایپ کنٹرولز فراہم کر سکتا ہے:',
        itemHistory: 'اس ڈیوائس پر محفوظ براؤزر ہسٹری صاف کرنا۔',
        itemBookmarks: 'اس ڈیوائس پر محفوظ بُک مارکس منظم یا صاف کرنا۔',
        itemDownloads: 'ڈاؤن لوڈز اور ان کی مقامی فائلیں حذف کرنا۔',
        itemLanguage: 'سیٹنگز میں زبان اور دیگر ترجیحات بدلنا۔',
      },
      accountDeletion: {
        heading: '۱۰۔ کوئی VidoraX اکاؤنٹ نہیں',
        p1: 'VidoraX صارف اکاؤنٹ، لاگ اِن، یا پاس ورڈ نہیں بناتا۔ حذف کرنے کے لیے کوئی کلاؤڈ پروفائل نہیں۔',
        p2: 'اس ڈیوائس سے مقامی VidoraX ڈیٹا ہٹانے کے لیے ایپ میں ہسٹری یا ڈاؤن لوڈز صاف کریں، یا VidoraX ان انسٹال کریں۔ ان انسٹال ڈیوائس سے مقامی ایپ ڈیٹا ہٹا دیتا ہے۔',
      },
      children: {
        heading: '۱۱۔ بچوں کی پرائیویسی',
        p1: 'VidoraX خاص طور پر بچوں کے لیے نہیں بنایا گیا اور اس پالیسی کے تحت ایپ کنفیگریشن میں اسے بچوں کی طرف متوجہ پروڈکٹ کے طور پر پیش نہیں کیا گیا۔',
        p2: 'لاگو عمر کی پابندیاں، والدین کے کنٹرولز، اور مقامی قوانین پھر بھی ایپ کے استعمال پر اثر انداز ہو سکتے ہیں۔',
      },
      updates: {
        heading: '۱۲۔ پالیسی کی تازہ کاریاں',
        p1: 'VidoraX میں تبدیلی کے ساتھ ہم یہ پرائیویسی پالیسی اپڈیٹ کر سکتے ہیں۔ تاریخِ نفاذ اور آخری تازہ کاری اس دستاویز کے اوپر درج ہیں۔ اپڈیٹ کے بعد VidoraX کا مسلسل استعمال مطلب ہے کہ آپ نظرِ ثانی شدہ پالیسی دیکھیں۔ اہم تبدیلیاں عملی طور پر اِن‑ایپ یا VidoraX ویب سائٹ پر بھی بتائی جا سکتی ہیں۔',
      },
      contact: {
        heading: '۱۳۔ رابطہ',
        p1: 'اس ایپ بلڈ میں وقف پرائیویسی ای میل کنفیگر نہیں۔ پرائیویسی سوالات کے لیے VidoraX سے متعلق کوئی شائع شدہ رابطہ تفصیل {website} پر دیکھیں۔',
        p2: 'اس پالیسی کے عوامی ویب ورژن شائع ہونے پر {privacyUrl} پر دستیاب رکھنے کا ارادہ ہے۔',
      },
    },
  },
  terms: {
    title: 'شرائط و ضوابط',
    a11y: 'شرائط و ضوابط',
    sections: {
      acceptance: {
        heading: '۱۔ قبولیت',
        p1: 'یہ شرائط و ضوابط VidoraX موبائل ایپ کے استعمال پر لاگو ہیں۔ VidoraX استعمال کر کے آپ ان شرائط سے اتفاق کرتے ہیں۔ VidoraX کے لیے اکاؤنٹ بنانا، سائن اِن، یا پاس ورڈ درکار نہیں۔',
        p2: 'اگر آپ متفق نہیں تو VidoraX استعمال نہ کریں۔',
      },
      permittedUse: {
        heading: '۲۔ جائز استعمال',
        p1: 'آپ ان شرائط اور لاگو قانون کے مطابق ویب براؤز کرنے، سپورٹ شدہ ڈاؤن لوڈز منظم کرنے، لائبریری آئٹمز ترتیب دینے، اور سپورٹ شدہ میڈیا چلانے کے لیے VidoraX استعمال کر سکتے ہیں۔',
        p2: 'آپ صرف وہی مواد ڈاؤن لوڈ، محفوظ، یا چلا سکتے ہیں جس تک رسائی اور رکھنے کی آپ کو قانونی اجازت ہے۔ VidoraX آپ کو تیسری پارٹی مواد کے حقوق نہیں دیتا۔',
      },
      contentOwnership: {
        heading: '۳۔ مواد کی ملکیت اور کاپی رائٹ',
        p1: 'VidoraX، بشمول اس کا نام، برانڈنگ، اور ایپ سافٹ ویئر، اپنے حقوق رکھنے والوں کی ملکیت ہے۔ یہ شرائط آپ کو VidoraX کی ملکیت نہیں دیتیں۔',
        p2: 'تیسری پارٹی ویب سائٹس، ویڈیوز، تصاویر، اور دیگر میڈیا اپنے اپنے مالکان کی ملکیت رہتے ہیں۔ کاپی رائٹ اور دیگر دانشورانہ حقوق کا احترام آپ کی ذمہ داری ہے۔',
      },
      userAuthorization: {
        heading: '۴۔ صارف کی اجازت کی ذمہ داری',
        p1: 'جو یو آر ایل آپ کھولتے ہیں، جو لنکس پیسٹ کرتے ہیں، اور جس میڈیا کا تجزیہ، ڈاؤن لوڈ، ذخیرہ، یا پلے کرتے ہیں اس کی ذمہ داری صرف آپ پر ہے۔',
        p2: 'آپ یہ بیان کرتے ہیں کہ VidoraX سے جو مواد پراسیس کرتے ہیں اس تک رسائی اور محفوظ کرنے کی مطلوبہ اجازت آپ کے پاس ہے۔',
      },
      supportedSources: {
        heading: '۵۔ سپورٹ شدہ اور غیر سپورٹ ماخذ',
        p1: 'ہر ویب سائٹ یا میڈیا اسٹریم ڈاؤن لوڈ یا پلے نہیں ہو سکتا۔ دستیابی ماخذ، تکنیکی فارمیٹ، نیٹ ورک حالات، اور پروڈکٹ صلاحیتوں پر منحصر ہے۔',
        p2: 'جب ماخذ غیر سپورٹ، غیر مستحکم، یا غیر مطابقت پذیر ہو تو VidoraX درخواست مسترد، ناکام، یا جزوی طور پر سپورٹ کر سکتا ہے۔ سپورٹ نہ ہونا اسی مواد کو غیر قانونی طریقے سے حاصل کرنے کی اجازت نہیں۔',
      },
      drmLimitations: {
        heading: '۶۔ DRM، انکرپٹڈ، اور محفوظ میڈیا',
        p1: 'VidoraX DRM‑محفوظ، انکرپٹڈ، یا اسی طرح محفوظ میڈیا سپورٹ نہیں کرتا جسے پروڈکٹ قانونی اور تکنیکی طور پر پراسیس نہ کر سکے۔',
        p2: 'آپ DRM، انکرپشن، رسائی کنٹرولز، یا دیگر تکنیکی حفاظتی اقدامات کو بائی پاس کرنے کی کوشش کے لیے VidoraX استعمال نہیں کر سکتے۔',
        p3: 'اگر VidoraX بتائے کہ میڈیا DRM‑محفوظ، انکرپٹڈ، یا غیر سپورٹ ہے تو اسے سخت حد سمجھیں — حفاظتی اقدامات توڑنے کا اشارہ نہیں۔',
      },
      userResponsibilities: {
        heading: '۷۔ صارف کی ذمہ داریاں',
        intro: 'آپ اتفاق کرتے ہیں کہ:',
        itemCredentials: 'VidoraX کو اس توقع کے بغیر استعمال کریں کہ لاگ اِن، پاس ورڈ، یا کلاؤڈ اکاؤنٹ شناخت درکار ہوگی۔',
        itemLawful: 'VidoraX صرف جائز مقاصد اور صرف اس مواد کے ساتھ استعمال کریں جسے ہینڈل کرنے کی اجازت آپ کو ہے۔',
        itemDevice: 'ایپ کے لیے درکار اپنی ڈیوائس اسٹوریج، بیک اپ، اور نیٹ ورک رسائی برقرار رکھیں۔',
        itemAccuracy: 'ڈاؤن لوڈ اور پلے بیک نتائج غور سے دیکھیں؛ تکنیکی تجزیہ نامکمل ہو سکتا ہے۔',
      },
      prohibitedMisuse: {
        heading: '۸۔ ممنوع غلط استعمال',
        intro: 'آپ کو نہیں چاہیے کہ:',
        itemCircumvent:
          'DRM، انکرپشن، پے وال، تصدیقی دروازے، یا دیگر سیکیورٹی یا کاپی رائٹ حفاظتی اقدامات بائی پاس کرنے کی کوشش کریں۔',
        itemAbuse:
          'VidoraX سروسز کا غلط استعمال کریں، بشمول اوور لوڈ، نقصان دہ اسکریپنگ، یا ایسا آٹومیشن جو سروس میں خلل ڈالے۔',
        itemInterfere:
          'ایپ کی سالمیت میں مداخلت، قانون کی خلاف ورزی کر کے محفوظ حصوں کو ریورس انجینئر، یا VidoraX سسٹمز تک غیر مجاز رسائی کی کوشش کریں۔',
        itemUnlawful:
          'VidoraX کو غیر قانونی طور پر مواد ذخیرہ، تقسیم، یا رسائی، یا دوسروں کو ہراساں، استحصال، یا نقصان کے لیے استعمال کریں۔',
      },
      serviceAvailability: {
        heading: '۹۔ سروس کی دستیابی',
        p1: 'مینٹیننس، نیٹ ورک مسائل، ڈیوائس حدود، یا سروس فیصلوں کی وجہ سے VidoraX فیچرز بدل، رک، یا عارضی طور پر دستیاب نہ ہو سکتے ہیں۔',
        p2: 'ہم کسی بھی فیچر کی بلا تعطل، غلطی سے پاک، یا مستقل دستیابی کی ضمانت نہیں دیتے۔',
      },
      accountsSecurity: {
        heading: '۱۰۔ ڈیوائس سیکیورٹی',
        p1: 'جہاں VidoraX نصب ہے اس ڈیوائس کی جسمانی اور لاک‑اسکرین رسائی کی ذمہ داری آپ پر ہے۔ VidoraX اکاؤنٹ کے لیے لاگ اِن یا پاس ورڈ نہیں دیتا۔',
        p2: 'ڈیوائس کا تحفظ (پاس کوڈ، بائیو میٹرکس، او ایس اپڈیٹس) ہی وہ بنیادی طریقہ ہے جس سے مقامی ڈاؤن لوڈز، ہسٹری، اور سیٹنگز تک رسائی محدود رہتی ہے۔',
      },
      localFiles: {
        heading: '۱۱۔ مقامی فائلیں اور اسٹوریج',
        p1: 'ڈاؤن لوڈ شدہ میڈیا اور متعلقہ مقامی ڈیٹا آپ کی ڈیوائس کی جگہ لیتے ہیں۔ اسٹوریج منظم کرنا، غیر ضروری فائلیں حذف کرنا، اور یہ سمجھنا کہ ایپ ان انسٹال مقامی ایپ ڈیٹا ہٹا دیتی ہے آپ کی ذمہ داری ہے۔',
        p2: 'VidoraX آپ کی میڈیا لائبریری کے لیے یقینی بیک اپ سروس نہیں۔ جو اہم ہو اس کی اپنی کاپیاں رکھیں۔',
      },
      deviceLimitations: {
        heading: '۱۲۔ ڈیوائس، کوڈیک، اور نیٹ ورک حدود',
        p1: 'پلے بیک اور ڈاؤن لوڈ کی کامیابی آپ کی ڈیوائس صلاحیتوں، سپورٹ شدہ کوڈیکس، دستیاب اسٹوریج، او ایس اجازتوں، اور نیٹ ورک کوالٹی پر منحصر ہے۔',
        p2: 'غیر سپورٹ کوڈیکس یا فارمیٹس فائل محفوظ ہونے کے باوجود نہ چل سکیں۔ نیٹ ورک رکاوٹیں ٹرانسفر میں تاخیر یا ناکامی لا سکتی ہیں۔',
      },
      limitationOfService: {
        heading: '۱۳۔ سروس کی حد',
        p1: 'VidoraX براؤزر، میڈیا، اور ڈاؤن لوڈ مینیجر کے طور پر ذاتی استعمال کے لیے “جوں دستیاب” بنیاد پر فراہم کیا جاتا ہے۔ قانون کی اجازت کی حد تک، VidoraX اور اس کے آپریٹرز بالواسطہ، اتفاقی، خاص، نتیجتاً، یا تعزیری نقصانات، یا ایپ کے استعمال سے ڈیٹا، میڈیا فائلوں، منافع، یا ساکھ کے نقصان کے ذمہ دار نہیں۔',
        p2: 'ان شرائط میں ایسی ذمہ داری خارج نہیں جو لاگو قانون کے تحت خارج نہ کی جا سکے۔',
      },
      suspension: {
        heading: '۱۴۔ معطل کرنا اور ختم کرنا',
        p1: 'ان شرائط کی سنگین خلاف ورزی، غیر قانونی استعمال، سیکیورٹی خطرہ، یا پروڈکٹ کے غلط استعمال پر ہم VidoraX فیچرز معطل یا بند کر سکتے ہیں۔',
        p2: 'آپ کسی بھی وقت VidoraX استعمال بند کر سکتے ہیں اور ایپ ان انسٹال کر سکتے ہیں۔ ان انسٹال ڈیوائس سے مقامی ایپ ڈیٹا ہٹا دیتا ہے۔ بند کرنے کے لیے کوئی VidoraX اکاؤنٹ نہیں۔',
      },
      updates: {
        heading: '۱۵۔ ان شرائط کی تازہ کاریاں',
        p1: 'پروڈکٹ کی ترقی کے ساتھ ہم یہ شرائط اپڈیٹ کر سکتے ہیں۔ تاریخِ نفاذ اور آخری تازہ کاری اس دستاویز کے اوپر ہیں۔ قانون کی اجازت ہو تو اپڈیٹ کے بعد مسلسل استعمال نظرِ ثانی شدہ شرائط کی قبولیت شمار ہوتا ہے۔',
      },
      contact: {
        heading: '۱۶۔ رابطہ',
        p1: 'اس ایپ بلڈ میں وقف سپورٹ ای میل کنفیگر نہیں۔ ان شرائط کے سوالات کے لیے VidoraX سے متعلق کوئی شائع شدہ رابطہ تفصیل {website} پر دیکھیں۔',
        p2: 'ان شرائط کے عوامی ویب ورژن شائع ہونے پر {termsUrl} پر دستیاب رکھنے کا ارادہ ہے۔',
      },
    },
  },
  appLock: {
    enterPin: 'PIN درج کریں',
    enterPinA11y: 'اپنا 4 ہندسوں کا ایپ لاک PIN درج کریں',
    unlock: 'ان لاک',
    incorrectPin: 'غلط PIN',
    unlockError: 'PIN کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    setPinTitle: 'ایپ لاک PIN سیٹ کریں',
    setPinHint: 'اس ڈیوائس پر VidoraX محفوظ کرنے کے لیے 4 ہندسوں کا PIN منتخب کریں۔',
    setPinA11y: 'نیا 4 ہندسوں کا PIN درج کریں',
    confirmPinHint: 'تصدیق کے لیے وہی 4 ہندسوں کا PIN دوبارہ درج کریں۔',
    confirmPinA11y: 'اپنے 4 ہندسوں کے PIN کی تصدیق کریں',
    pinsDoNotMatch: 'PIN مماثل نہیں',
    pinInvalid: 'درست 4 ہندسوں کا PIN درج کریں',
    recoveryTitle: 'ریکوری کوڈ',
    recoveryHint:
      'یہ ریکوری کوڈ محفوظ جگہ رکھیں۔ PIN بھول جانے پر بعد میں درکار ہو سکتا ہے۔',
    recoveryCodeA11y: 'آپ کا ایپ لاک ریکوری کوڈ',
    copyRecoveryCode: 'ریکوری کوڈ کاپی کریں',
    savedRecoveryConfirm: 'میں نے اپنا ریکوری کوڈ محفوظ کر لیا ہے',
    mustConfirmSaved: 'تصدیق کریں کہ آپ نے ریکوری کوڈ محفوظ کر لیا ہے',
    dataLossWarningTitle: 'اہم',
    dataLossWarningBody:
      'اپنا PIN اور ریکوری کوڈ محفوظ رکھیں۔ اگر آپ PIN اور ریکوری کوڈ دونوں بھول گئے تو آپ کا محفوظ مقامی ایپ ڈیٹا بحال نہیں ہو سکے گا۔',
    dataLossWarningReinstall:
      'آپ کو VidoraX اَن انسٹال کر کے دوبارہ انسٹال کرنی ہوگی، جس سے ایپ کا مقامی ڈیٹا ختم ہو جائے گا۔',
    dataLossWarningCompact:
      'اپنا PIN اور ریکوری کوڈ محفوظ رکھیں۔ دونوں بھول جانے پر محفوظ مقامی ڈیٹا بحال نہیں ہو سکتا — صرف VidoraX دوبارہ انسٹال کرنے سے (جس سے مقامی ڈیٹا ختم ہو جاتا ہے) ایپ لاک ری سیٹ ہوتا ہے۔',
    dataLossAcknowledge:
      'میں سمجھتا/سمجھتی ہوں کہ PIN اور ریکوری کوڈ دونوں کھو دینے سے میرا مقامی ایپ ڈیٹا ضائع ہو سکتا ہے۔',
    mustAcknowledgeDataLoss: 'تصدیق کریں کہ آپ نے اوپر دی گئی تنبیہ سمجھ لی ہے',
    enableAppLock: 'ایپ لاک فعال کریں',
    setupError: 'ایپ لاک فعال نہیں ہو سکا۔ دوبارہ کوشش کریں۔',
    cancelSetupTitle: 'سیٹ اپ منسوخ؟',
    cancelSetupMessage: 'ایپ لاک بند ہی رہے گی۔',
    disableTitle: 'ایپ لاک بند کریں',
    disableHint: 'ایپ لاک بند کرنے کے لیے اپنا موجودہ PIN درج کریں۔',
    disablePinA11y: 'بند کرنے کے لیے موجودہ ایپ لاک PIN درج کریں',
    disableConfirmTitle: 'ایپ لاک بند کریں؟',
    disableConfirmMessage:
      'ایپ پر واپس آنے پر VidoraX PIN نہیں مانگے گی۔',
    disableConfirmAction: 'بند کریں',
    disableError: 'ایپ لاک بند نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    integrityTitle: 'ایپ لاک دستیاب نہیں',
    integrityMessage:
      'اس ڈیوائس پر ایپ لاک ڈیٹا نامکمل یا خراب لگتا ہے۔ نجی مواد لاک رہتا ہے۔ دوبارہ کوشش کریں، یا اگر مسئلہ رہے تو دوبارہ انسٹال کریں۔',
    secureStoreError:
      'محفوظ اسٹوریج پڑھ نہیں سکی۔ نجی مواد لاک رہتا ہے۔ دوبارہ کوشش کریں۔',
    changePinTitle: 'PIN تبدیل کریں',
    enterCurrentPinHint: 'اپنا موجودہ 4 ہندسوں کا PIN درج کریں۔',
    enterCurrentPinA11y: 'موجودہ ایپ لاک PIN درج کریں',
    setNewPinHint: 'نیا 4 ہندسوں کا PIN منتخب کریں۔',
    setNewPinA11y: 'نیا 4 ہندسوں کا PIN درج کریں',
    confirmNewPinHint: 'تصدیق کے لیے نیا PIN دوبارہ درج کریں۔',
    confirmNewPinA11y: 'نئے 4 ہندسوں کے PIN کی تصدیق کریں',
    pinChangedTitle: 'PIN اپڈیٹ ہو گیا',
    pinChangedMessage: 'آپ کا ایپ لاک PIN تبدیل ہو گیا۔ ریکوری کوڈ ویسا ہی ہے۔',
    forgotPin: 'PIN بھول گئے؟',
    forgotPinTitle: 'PIN بھول گئے',
    enterRecoveryCodeHint:
      'نیا PIN سیٹ کرنے کے لیے ریکوری کوڈ درج کریں۔ یہ خود ایپ ان لاک نہیں کرتا۔',
    enterRecoveryCodeA11y: 'ایپ لاک ریکوری کوڈ درج کریں',
    recoveryCodePlaceholder: 'XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XX',
    verifyRecoveryCode: 'جاری رکھیں',
    incorrectRecoveryCode: 'غلط ریکوری کوڈ',
    lostBothWarning:
      'اگر آپ کے پاس PIN اور ریکوری کوڈ دونوں نہیں، VidoraX ایپ ان لاک نہیں کر سکتی۔',
    updateError: 'ایپ لاک اپڈیٹ نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    tooManyAttempts: 'بہت زیادہ کوششیں۔',
    tryAgainShortly: 'جلد دوبارہ کوشش کریں۔',
    tryAgainInSeconds: '{seconds} سیکنڈ میں دوبارہ کوشش کریں۔',
    generateRecoveryTitle: 'نیا ریکوری کوڈ',
    generateRecoveryPinHint: 'نیا ریکوری کوڈ بنانے کے لیے موجودہ PIN درج کریں۔',
    generateRecoveryHint:
      'یہ نیا ریکوری کوڈ محفوظ رکھیں۔ تصدیق کے بعد پرانا ریکوری کوڈ کام نہیں کرے گا۔',
    previousRecoveryWillStop:
      'اسے محفوظ کرنے کے بعد آپ کا پرانا ریکوری کوڈ کام نہیں کرے گا۔',
    savedNewRecoveryConfirm: 'میں نے اپنا نیا ریکوری کوڈ محفوظ کر لیا ہے',
    saveNewRecovery: 'نیا ریکوری کوڈ محفوظ کریں',
  },
  shell: shellUr,
  detection: detectionUr,
  videoPlayer: videoPlayerUr,
};
