export const BOOKMARKS_COPY = {
  title: 'Bookmarks',
  searchPlaceholder: 'Search bookmarks',
  emptyTitle: 'No bookmarks yet',
  emptyDescription: 'Tap the bookmark icon while browsing to save pages here.',
  emptyAction: 'Open browser',
  errorTitle: 'Couldn’t load bookmarks',
  clearTitle: 'Clear all bookmarks?',
  clearMessage: 'This permanently removes every saved bookmark from this device.',
  clearConfirm: 'Clear all',
  clearCancel: 'Cancel',
  deleteTitle: 'Remove bookmark?',
  deleteMessage: 'This page will be removed from your bookmarks.',
  deleteConfirm: 'Remove',
  deleteCancel: 'Cancel',
  loadingAnnouncement: 'Loading bookmarks',
  endOfList: 'You’re all caught up',
  toggleFailed: 'Couldn’t update bookmark. Try again.',
} as const;
